### ISSUE TITLE
Update tool-esptoolpy

### ISSUE THREAD

**Issue by me21** [platformio/platform-espressif32#100]
I have a custom board where STM32 is used as bridge from USB to serial for programming the ESP32 chip.
Tool-esptoolpy v2.3.1 which is installed by Platformio can’t connect to ESP32, but the version v2.4.1 from the tip of master branch in esptool git repo connects.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-espressif32/commit/2100b95f60d0edb380dbea1fcd09fe488ae7b64a.

Please re-test with upstream version http://docs.platformio.org/en/latest/platforms/espressif32.html#upstream
