### ISSUE TITLE
Error using "New project" for ESP32-CAM AI Thinker board with ESP-IDF framework

### ISSUE THREAD

**Issue by AgainPsychoX** [platformio/platform-espressif32#1000]
### Steps
1. Click `New Project` on PIO Home tab:
![image](https://user-images.githubusercontent.com/23557839/210156315-8c31a8d2-9c35-4ab7-b762-b9a4ad9866a9.png)
2. Fill wizard, selecting ESP32-CAM board and esp-idf framework.
![image](https://user-images.githubusercontent.com/23557839/210156326-2945eb9c-1116-40c3-9109-daa122b360ba.png)
3. After long waiting, it ends with error message. The `Report error` button doesn't work, so I created this issue by hand.
<sup>(sorry no picture, forgot and don't want to wait 10 minutes)</sup>

### Platform

VS Code Version: `1.74.2`
OS: `Windows_NT x64 10.0.19045`
PlatformIO extension version: `v2.5.5`
PlatformIO Core version: `6.1.5`

### Logs

* Log in the error window: https://gist.github.com/AgainPsychoX/5a5c83a664f17c1998cb10643cb422bf#file-log-from-the-error-window-log
* Log from `CMakeOutput.log` (mentioned in main log): https://gist.github.com/AgainPsychoX/5a5c83a664f17c1998cb10643cb422bf#file-cmakeoutput-log

### Things I tried
* Cleanly reinstalling whole PlatformIO (uninstalled, restarted VS Code; removed `%USERPROFILE%\.platformio`, installed again; restarted VS Code to enable the extension). Same error appears (but I had no more warning about obsolete PlatformIO Core version or something).

**Comment by valeros** [comment]
Hi @AgainPsychoX ! I don't see any obvious errors in the logs, so let's try debugging it the CLI way. Please open your project in the IDE, then open the terminal via `` ctrl+ shift + ` ``, then clean `pio run -t clean` and build `pio run` your project.

**Comment by AgainPsychoX** [comment]
My issue isn't about code failing to build, its about errors when creating new project.

As far as I remember, it compiles & upload fine for me. It was lacking VS Code generated files (`c_cpp_properties.json`), but I managed to recreate them by using `pio init --ide=vscode`.

**Comment by maxgerhardt** [comment]
Possibly related: https://community.platformio.org/t/creating-new-esp-idf-project-fails-with-modulenotfounderror-no-module-named-idf-component-manager-message/31511?u=maxgerhardt

**Comment by maxgerhardt** [comment]
Even PlatformIO-core CI fails with the same error in the this run: https://github.com/platformio/platformio-core/actions/runs/3913391485/jobs/6689228904

> 'ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: \'D:\\\\a\\\\platformio-core\\\\platformio-core\\\\.tox\\\\testexamples\\\\Lib\\\\site-packages\\\\~harset_normalizer\\\\md.cp39-win_amd64.pyd\'\r\nCheck the permissions.\r\n\r\
>ModuleNotFoundError: No module\r\n  named \'idf_component_manager\')\

What is is up with that `~harset_normalizer` package?

**Comment by maxgerhardt** [comment]
Possibly related too: https://github.com/Ousret/charset_normalizer/issues/253

**Comment by Jason2866** [comment]
Have you tried latest release 6.0?
There are changes, which could solve this issue.
The issue occurred here too https://github.com/platformio/platform-espressif32/actions/runs/3881735765/jobs/6684846018
In later CIs the error is gone

**Comment by maxgerhardt** [comment]
Even if IDFv5 integration in `espressif32@6.0.0` is working, that would mean ESP-IDF in `espressif32@5.3.0` does not work.. ever.

**Comment by Jason2866** [comment]
@maxgerhardt If the reason is known a backport can be down.

**Comment by Jason2866** [comment]
This backport https://github.com/tasmota/platform-espressif32/commit/ded00a7652962ec17350f713d37f71a22a7274f3 from release 6.0.0 seems to fix the issue.
