### ISSUE TITLE
help on debug esp32s3 devkitC-1 not showing any variables

### ISSUE THREAD

**Issue by TalSomech** [platformio/platform-espressif32#1001]
im trying to use vscode to debug using the usb jtag in the esp32s3 , after many errors i've been able to debug the simplest program however im not getting any variables:
![Capture](https://user-images.githubusercontent.com/73115681/211821580-ffe9b2cd-db6c-4db7-b94d-8a098790393c.PNG)
and the ini file:
![Capture](https://user-images.githubusercontent.com/73115681/211821800-22a97946-7988-487b-b855-a3c24f041715.PNG)

**Comment by valeros** [comment]
Hi @TalSomech ! It seems that your code was optimized out by the compiler. You can either add the `volatile` qualifier to one of your variables or compile your project with optimization turned off:
```ini
[env:esp32-s3-devkitc-1]
platform = espressif32
framework = espidf
board = esp32-s3-devkitc-1
debug_build_flags = -O0
```
