### ISSUE TITLE
With v6 (ESP-IDF v5): `ImportError: cannot import name 'rest_of_line' from 'pyparsing'`

### ISSUE THREAD

**Issue by benwills** [platformio/platform-espressif32#1007]
I just upgraded to platform-espressif32 v6 the other day. Everything was working and compiling+uploading fine before the upgrade.

I refactored code based on compile errors I was expecting from the switch to ESP-IDF v5, but am still getting compile errors that seem that they may be related to platform-espressif32.

I'm now stuck on the following error, which seems to be part of the build process:

> Traceback (most recent call last):
>   File "/home/o/.platformio/packages/framework-espidf/tools/ldgen/ldgen.py", line 16, in <module>
>     from ldgen.entity import EntityDB
>   File "/home/o/.platformio/packages/framework-espidf/tools/ldgen/ldgen/entity.py", line 12, in <module>
>     from pyparsing import (Group, Literal, OneOrMore, ParseException, SkipTo, Suppress, White, Word, ZeroOrMore, alphas,
> ImportError: cannot import name 'rest_of_line' from 'pyparsing' (/home/o/.platformio/penv/lib/python3.10/site-packages/pyparsing.py)

This error always occurs near the end of the build process.

----
### Steps I've taken:

Looking through similar errors, some people are able to work around it by doing a full clean, then building. That's not working for me. (Running Clean All, then running Build, both from the PlatformIO interface for my specific boards still fails, as seen below)

I have also completely uninstalled and deleted the platform-espressif32 files in the .pio directory, before doing a reinstall of platform-espressif32. But that also seems to not be working.

----
### System Configuration:

VSCode:
> Version: 1.74.3
> Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
> Date: 2023-01-09T16:57:40.428Z
> Electron: 19.1.8
> Chromium: 102.0.5005.167
> Node.js: 16.14.2
> V8: 10.2.154.15-electron.0
> OS: Linux x64 5.15.0-56-generic snap
> Sandboxed: No

PlatformIO:
> $ pio upgrade
> You're up-to-date!
> PlatformIO 6.1.5 is currently the newest version available.

platform-espressif32
> v6.0.0

OS
> Ubuntu 22.04 (xubuntu)
> $uname -a:
>> Linux xub 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

----
### Output

Two ways of getting the error. First, is when I don't run 'Clean All' before 'Build', and the second is when I do run 'Clean All' before 'Build'

----
### Running 'Build' _without_ first running 'Clean All'

> Processing esp-wrover-kit (board: esp-wrover-kit; platform: espressif32; framework: espidf)
> 
> Verbose mode can be enabled via `-v, --verbose` option
> CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp-wrover-kit.html
> PLATFORM: Espressif 32 (6.0.0) > Espressif ESP-WROVER-KIT
> HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
> DEBUG: Current (ftdi) On-board (ftdi) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
> PACKAGES: 
>  - framework-espidf @ 3.50000.0 (5.0.0) 
>  - tool-cmake @ 3.16.4 
>  - tool-esptoolpy @ 1.40400.0 (4.4.0) 
>  - tool-ninja @ 1.7.1 
>  - toolchain-esp32ulp @ 1.23500.220830 (2.35.0) 
>  - toolchain-xtensa-esp32 @ 11.2.0+2022r1
> Reading CMake configuration...
> LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ soft
> Found 0 compatible libraries
> Scanning dependencies...
> No dependencies
> Building in release mode
> Generating project linker script .pio/build/esp-wrover-kit/sections.ld
> Traceback (most recent call last):
>   File "/home/o/.platformio/packages/framework-espidf/tools/ldgen/ldgen.py", line 16, in <module>
>     from ldgen.entity import EntityDB
>   File "/home/o/.platformio/packages/framework-espidf/tools/ldgen/ldgen/entity.py", line 12, in <module>
>     from pyparsing import (Group, Literal, OneOrMore, ParseException, SkipTo, Suppress, White, Word, ZeroOrMore, alphas,
> ImportError: cannot import name 'rest_of_line' from 'pyparsing' (/home/o/.platformio/penv/lib/python3.10/site-packages/pyparsing.py)
> Archiving .pio/build/esp-wrover-kit/bootloader/esp-idf/micro-ecc/libmicro-ecc.a
> Indexing .pio/build/esp-wrover-kit/bootloader/esp-idf/micro-ecc/libmicro-ecc.a
> Archiving .pio/build/esp-wrover-kit/bootloader/esp-idf/soc/libsoc.a
> *** [.pio/build/esp-wrover-kit/sections.ld] Error 1
> Indexing .pio/build/esp-wrover-kit/bootloader/esp-idf/soc/libsoc.a
> 
> [FAILED] Took 10.83 seconds 
> 
> Environment     Status    Duration
> esp-wrover-kit  FAILED    00:00:10.828

----
### Running 'Clean All' before running 'Build'

> Processing esp-wrover-kit (board: esp-wrover-kit; platform: espressif32; framework: espidf)
> 
> Verbose mode can be enabled via `-v, --verbose` option
> CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp-wrover-kit.html
> PLATFORM: Espressif 32 (6.0.0) > Espressif ESP-WROVER-KIT
> HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
> DEBUG: Current (ftdi) On-board (ftdi) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
> PACKAGES: 
>  - framework-espidf @ 3.50000.0 (5.0.0) 
>  - tool-cmake @ 3.16.4 
>  - tool-esptoolpy @ 1.40400.0 (4.4.0) 
>  - tool-ninja @ 1.7.1 
>  - toolchain-esp32ulp @ 1.23500.220830 (2.35.0) 
>  - toolchain-xtensa-esp32 @ 11.2.0+2022r1
> Reading CMake configuration...
> Generating assembly for certificate bundle...
> LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ soft
> Found 0 compatible libraries
> Scanning dependencies...
> No dependencies
> Building in release mode
> Generating assembly for .pio/build/esp-wrover-kit/api.js.S
> Generating assembly for .pio/build/esp-wrover-kit/app.css.S
> Generating assembly for .pio/build/esp-wrover-kit/app.js.S
> Generating assembly for .pio/build/esp-wrover-kit/favicon.ico.S
> Generating assembly for .pio/build/esp-wrover-kit/favicon-32x32.png.S
> Generating assembly for .pio/build/esp-wrover-kit/favicon-192x192.png.S
> Generating assembly for .pio/build/esp-wrover-kit/index.html.S
> Compiling .pio/build/esp-wrover-kit/src/app_main.o
> Generating LD script .pio/build/esp-wrover-kit/memory.ld
> Compiling .pio/build/esp-wrover-kit/components/Cfg/Cfg.o
> Compiling .pio/build/esp-wrover-kit/components/Cli/Cli.o
> Compiling .pio/build/esp-wrover-kit/components/Cli/CliNet.o
> Compiling .pio/build/esp-wrover-kit/components/Cli/CliStor.o
> Compiling .pio/build/esp-wrover-kit/components/Cli/CliSys.o
> Compiling .pio/build/esp-wrover-kit/components/Cmd/Cmd.o
> Compiling .pio/build/esp-wrover-kit/components/Def/Def.o
> Compiling .pio/build/esp-wrover-kit/components/Dev/Dev.o
> Compiling .pio/build/esp-wrover-kit/components/Dev-z-old/Dev.o
> Compiling .pio/build/esp-wrover-kit/components/Enum/Enum.o
> Compiling .pio/build/esp-wrover-kit/components/Ev/Ev.o
> Compiling .pio/build/esp-wrover-kit/components/Ftp/Ftp.o
> Compiling .pio/build/esp-wrover-kit/components/Log/Log.o
> Compiling .pio/build/esp-wrover-kit/components/Net/Net.o
> Compiling .pio/build/esp-wrover-kit/components/Net/NetConn.o
> Compiling .pio/build/esp-wrover-kit/components/Net/NetEth.o
> Compiling .pio/build/esp-wrover-kit/components/Net/NetEv.o
> Compiling .pio/build/esp-wrover-kit/components/Net/NetIp4Addr.o
> Compiling .pio/build/esp-wrover-kit/components/Net/NetMac.o
> Compiling .pio/build/esp-wrover-kit/components/Net/NetMacAddr.o
> Compiling .pio/build/esp-wrover-kit/components/Net/NetMdns.o
> Compiling .pio/build/esp-wrover-kit/components/Net/NetWifi.o
> Compiling .pio/build/esp-wrover-kit/components/Net/NetWifiAp.o
> Archiving .pio/build/esp-wrover-kit/esp-idf/Log/libLog.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Ftp/libFtp.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Ev/libEv.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Log/libLog.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Enum/libEnum.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Dev-z-old/libDev-z-old.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Ftp/libFtp.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Ev/libEv.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Dev/libDev.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Enum/libEnum.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Dev-z-old/libDev-z-old.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Cli/libCli.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Cmd/libCmd.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Def/libDef.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Dev/libDev.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Cli/libCli.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Cmd/libCmd.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Cfg/libCfg.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Def/libDef.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Cfg/libCfg.a
> Compiling .pio/build/esp-wrover-kit/.pio/build/esp-wrover-kit/api.js.o
> Compiling .pio/build/esp-wrover-kit/.pio/build/esp-wrover-kit/index.html.o
> Compiling .pio/build/esp-wrover-kit/.pio/build/esp-wrover-kit/favicon-192x192.png.o
> Compiling .pio/build/esp-wrover-kit/.pio/build/esp-wrover-kit/favicon-32x32.png.o
> Compiling .pio/build/esp-wrover-kit/.pio/build/esp-wrover-kit/app.css.o
> Compiling .pio/build/esp-wrover-kit/.pio/build/esp-wrover-kit/favicon.ico.o
> Compiling .pio/build/esp-wrover-kit/.pio/build/esp-wrover-kit/app.js.o
> Compiling .pio/build/esp-wrover-kit/components/Net/NetWifiSta.o
> Compiling .pio/build/esp-wrover-kit/components/Ota/Ota.o
> Compiling .pio/build/esp-wrover-kit/components/Ota/OtaJson.o
> Compiling .pio/build/esp-wrover-kit/components/Prod/Prod.o
> Compiling .pio/build/esp-wrover-kit/components/Stor/Stor.o
> Compiling .pio/build/esp-wrover-kit/components/Stor/StorSpiffs.o
> Compiling .pio/build/esp-wrover-kit/components/Stor/StorNvs.o
> Compiling .pio/build/esp-wrover-kit/components/Sys/Sys.o
> Compiling .pio/build/esp-wrover-kit/components/Www/Www.o
> Compiling .pio/build/esp-wrover-kit/components/Www/WwwApi.o
> Compiling .pio/build/esp-wrover-kit/components/Www/WwwApiCall.o
> Archiving .pio/build/esp-wrover-kit/esp-idf/Net/libNet.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Stor/libStor.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Sys/libSys.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Net/libNet.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Stor/libStor.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Ota/libOta.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Sys/libSys.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Ota/libOta.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Prod/libProd.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Prod/libProd.a
> Compiling .pio/build/esp-wrover-kit/components/Www/WwwApiPush.o
> Compiling .pio/build/esp-wrover-kit/components/Www/WwwApiRecv.o
> Compiling .pio/build/esp-wrover-kit/components/Www/WwwApiSend.o
> Compiling .pio/build/esp-wrover-kit/components/Www/WwwEv.o
> Compiling .pio/build/esp-wrover-kit/components/Www/WwwUrl.o
> Compiling .pio/build/esp-wrover-kit/app_trace/app_trace.o
> Compiling .pio/build/esp-wrover-kit/app_trace/app_trace_util.o
> Compiling .pio/build/esp-wrover-kit/app_trace/host_file_io.o
> Compiling .pio/build/esp-wrover-kit/app_trace/gcov/gcov_rtio.o
> Compiling .pio/build/esp-wrover-kit/app_trace/port/port_uart.o
> Compiling .pio/build/esp-wrover-kit/app_update/esp_ota_ops.o
> Compiling .pio/build/esp-wrover-kit/app_update/esp_ota_app_desc.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/bootloader_common.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/bootloader_common_loader.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/bootloader_clock_init.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/bootloader_flash/src/bootloader_flash.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/bootloader_mem.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/bootloader_random.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/bootloader_random_esp32.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/bootloader_utility.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/esp_image_format.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/flash_encrypt.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/secure_boot.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/flash_partitions.o
> Archiving .pio/build/esp-wrover-kit/esp-idf/app_update/libapp_update.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/app_trace/libapp_trace.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/app_update/libapp_update.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/Www/libWww.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/app_trace/libapp_trace.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/Www/libWww.a
> Compiling .pio/build/esp-wrover-kit/bootloader_support/bootloader_flash/src/flash_qio_mode.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/bootloader_flash/src/bootloader_flash_config_esp32.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/bootloader_efuse.o
> Compiling .pio/build/esp-wrover-kit/bootloader_support/src/idf/bootloader_sha.o
> Compiling .pio/build/esp-wrover-kit/cmock/CMock/src/cmock.o
> Compiling .pio/build/esp-wrover-kit/console/commands.o
> Compiling .pio/build/esp-wrover-kit/console/esp_console_repl.o
> Compiling .pio/build/esp-wrover-kit/console/split_argv.o
> Compiling .pio/build/esp-wrover-kit/console/linenoise/linenoise.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_cmd.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_date.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_dbl.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_dstr.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_end.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_file.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_hashtable.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_int.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_lit.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_rem.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_rex.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_str.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/arg_utils.o
> Compiling .pio/build/esp-wrover-kit/console/argtable3/argtable3.o
> Compiling .pio/build/esp-wrover-kit/cxx/cxx_exception_stubs.o
> Compiling .pio/build/esp-wrover-kit/cxx/cxx_guards.o
> Archiving .pio/build/esp-wrover-kit/esp-idf/bootloader_support/libbootloader_support.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/cmock/libcmock.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/bootloader_support/libbootloader_support.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/cmock/libcmock.a
> Compiling .pio/build/esp-wrover-kit/driver/gpio/gpio.o
> Compiling .pio/build/esp-wrover-kit/driver/gpio/rtc_io.o
> Compiling .pio/build/esp-wrover-kit/driver/gptimer.o
> Compiling .pio/build/esp-wrover-kit/driver/i2c.o
> Compiling .pio/build/esp-wrover-kit/driver/ledc.o
> Compiling .pio/build/esp-wrover-kit/driver/sdspi_crc.o
> Compiling .pio/build/esp-wrover-kit/driver/sdspi_host.o
> Compiling .pio/build/esp-wrover-kit/driver/sdspi_transaction.o
> Compiling .pio/build/esp-wrover-kit/driver/spi_common.o
> Compiling .pio/build/esp-wrover-kit/driver/spi_master.o
> Compiling .pio/build/esp-wrover-kit/driver/spi_slave.o
> Compiling .pio/build/esp-wrover-kit/driver/spi_bus_lock.o
> Compiling .pio/build/esp-wrover-kit/driver/uart.o
> Compiling .pio/build/esp-wrover-kit/driver/deprecated/timer_legacy.o
> Compiling .pio/build/esp-wrover-kit/driver/deprecated/adc_legacy.o
> Compiling .pio/build/esp-wrover-kit/driver/deprecated/adc_dma_legacy.o
> Compiling .pio/build/esp-wrover-kit/driver/mcpwm/mcpwm_cap.o
> Compiling .pio/build/esp-wrover-kit/driver/mcpwm/mcpwm_cmpr.o
> Compiling .pio/build/esp-wrover-kit/driver/mcpwm/mcpwm_com.o
> Compiling .pio/build/esp-wrover-kit/driver/mcpwm/mcpwm_fault.o
> Compiling .pio/build/esp-wrover-kit/driver/mcpwm/mcpwm_gen.o
> Compiling .pio/build/esp-wrover-kit/driver/mcpwm/mcpwm_oper.o
> Compiling .pio/build/esp-wrover-kit/driver/mcpwm/mcpwm_sync.o
> Compiling .pio/build/esp-wrover-kit/driver/mcpwm/mcpwm_timer.o
> Compiling .pio/build/esp-wrover-kit/driver/deprecated/mcpwm_legacy.o
> Archiving .pio/build/esp-wrover-kit/esp-idf/console/libconsole.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/console/libconsole.a
> Compiling .pio/build/esp-wrover-kit/driver/sdm.o
> Compiling .pio/build/esp-wrover-kit/driver/deprecated/sigma_delta_legacy.o
> Compiling .pio/build/esp-wrover-kit/driver/rmt/rmt_common.o
> Compiling .pio/build/esp-wrover-kit/driver/rmt/rmt_encoder.o
> Compiling .pio/build/esp-wrover-kit/driver/rmt/rmt_rx.o
> Compiling .pio/build/esp-wrover-kit/driver/rmt/rmt_tx.o
> Compiling .pio/build/esp-wrover-kit/driver/deprecated/rmt_legacy.o
> Compiling .pio/build/esp-wrover-kit/driver/pulse_cnt.o
> Compiling .pio/build/esp-wrover-kit/driver/deprecated/pcnt_legacy.o
> Compiling .pio/build/esp-wrover-kit/driver/sdmmc_transaction.o
> Compiling .pio/build/esp-wrover-kit/driver/sdmmc_host.o
> Compiling .pio/build/esp-wrover-kit/driver/i2s/i2s_common.o
> Compiling .pio/build/esp-wrover-kit/driver/i2s/i2s_std.o
> Compiling .pio/build/esp-wrover-kit/driver/deprecated/i2s_legacy.o
> Compiling .pio/build/esp-wrover-kit/driver/i2s/i2s_pdm.o
> Compiling .pio/build/esp-wrover-kit/driver/twai.o
> Compiling .pio/build/esp-wrover-kit/driver/touch_sensor_common.o
> Compiling .pio/build/esp-wrover-kit/driver/esp32/touch_sensor.o
> Compiling .pio/build/esp-wrover-kit/driver/sdio_slave.o
> Compiling .pio/build/esp-wrover-kit/driver/dac_common.o
> Compiling .pio/build/esp-wrover-kit/driver/deprecated/adc_i2s_deprecated.o
> Compiling .pio/build/esp-wrover-kit/driver/esp32/dac.o
> Compiling .pio/build/esp-wrover-kit/efuse/esp32/esp_efuse_table.o
> Compiling .pio/build/esp-wrover-kit/efuse/esp32/esp_efuse_fields.o
> Compiling .pio/build/esp-wrover-kit/efuse/esp32/esp_efuse_utility.o
> Compiling .pio/build/esp-wrover-kit/efuse/src/esp_efuse_api.o
> Compiling .pio/build/esp-wrover-kit/efuse/src/esp_efuse_fields.o
> Compiling .pio/build/esp-wrover-kit/efuse/src/esp_efuse_utility.o
> Compiling .pio/build/esp-wrover-kit/efuse/src/efuse_controller/keys/without_key_purposes/three_key_blocks/esp_efuse_api_key.o
> Compiling .pio/build/esp-wrover-kit/esp-tls/esp_tls.o
> Compiling .pio/build/esp-wrover-kit/esp-tls/esp-tls-crypto/esp_tls_crypto.o
> Compiling .pio/build/esp-wrover-kit/esp-tls/esp_tls_error_capture.o
> Compiling .pio/build/esp-wrover-kit/esp-tls/esp_tls_mbedtls.o
> Compiling .pio/build/esp-wrover-kit/esp_adc/adc_cali.o
> Archiving .pio/build/esp-wrover-kit/esp-idf/efuse/libefuse.a
> Archiving .pio/build/esp-wrover-kit/esp-idf/cxx/libcxx.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/efuse/libefuse.a
> Indexing .pio/build/esp-wrover-kit/esp-idf/cxx/libcxx.a
> Compiling .pio/build/esp-wrover-kit/esp_adc/adc_cali_curve_fitting.o
> Compiling .pio/build/esp-wrover-kit/esp_adc/adc_oneshot.o
> Compiling .pio/build/esp-wrover-kit/esp_adc/adc_common.o
> Compiling .pio/build/esp-wrover-kit/esp_adc/deprecated/esp_adc_cal_common_legacy.o
> Compiling .pio/build/esp-wrover-kit/esp_adc/adc_continuous.o
> Compiling .pio/build/esp-wrover-kit/esp_adc/esp32/adc_cali_line_fitting.o
> Compiling .pio/build/esp-wrover-kit/esp_adc/deprecated/esp32/esp_adc_cal_legacy.o
> Compiling .pio/build/esp-wrover-kit/esp_app_format/esp_app_desc.o
> Compiling .pio/build/esp-wrover-kit/esp_common/src/esp_err_to_name.o
> Compiling .pio/build/esp-wrover-kit/esp_eth/src/esp_eth.o
> Compiling .pio/build/esp-wrover-kit/esp_eth/src/esp_eth_phy_802_3.o
> Compiling .pio/build/esp-wrover-kit/esp_eth/src/esp_eth_netif_glue.o
> Compiling .pio/build/esp-wrover-kit/esp_eth/src/esp_eth_mac_esp.o
> Compiling .pio/build/esp-wrover-kit/esp_eth/src/esp_eth_phy_dp83848.o
> Compiling .pio/build/esp-wrover-kit/esp_eth/src/esp_eth_phy_ip101.o
> Compiling .pio/build/esp-wrover-kit/esp_eth/src/esp_eth_phy_ksz80xx.o

...trucated to fit 65,536 characters...

> Compiling .pio/build/esp-wrover-kit/bootloader/soc/esp32/pcnt_periph.o
> Compiling .pio/build/esp-wrover-kit/bootloader/soc/esp32/rmt_periph.o
> Compiling .pio/build/esp-wrover-kit/bootloader/soc/esp32/sdmmc_periph.o
> Compiling .pio/build/esp-wrover-kit/bootloader/soc/esp32/spi_periph.o
> Compiling .pio/build/esp-wrover-kit/bootloader/soc/esp32/timer_periph.o
> Traceback (most recent call last):
>   File "/home/o/.platformio/packages/framework-espidf/tools/ldgen/ldgen.py", line 16, in <module>
>     from ldgen.entity import EntityDB
>   File "/home/o/.platformio/packages/framework-espidf/tools/ldgen/ldgen/entity.py", line 12, in <module>
>     from pyparsing import (Group, Literal, OneOrMore, ParseException, SkipTo, Suppress, White, Word, ZeroOrMore, alphas,
> ImportError: cannot import name 'rest_of_line' from 'pyparsing' (/home/o/.platformio/penv/lib/python3.10/site-packages/pyparsing.py)
> Compiling .pio/build/esp-wrover-kit/bootloader/soc/esp32/sdio_slave_periph.o
> Compiling .pio/build/esp-wrover-kit/bootloader/soc/esp32/rtc_io_periph.o
> Compiling .pio/build/esp-wrover-kit/bootloader/soc/esp32/touch_sensor_periph.o
> Compiling .pio/build/esp-wrover-kit/bootloader/soc/esp32/uart_periph.o
> Generating partitions .pio/build/esp-wrover-kit/partitions.bin
> Generating an empty partition .pio/build/esp-wrover-kit/ota_data_initial.bin
> *** [.pio/build/esp-wrover-kit/sections.ld] Error 1
> 
> [FAILED] Took 28.25 seconds
> 
> Environment     Status    Duration
> esp-wrover-kit  FAILED    00:00:28.254

**Comment by benwills** [comment]
A similar issue was raised about a year ago in the esp-idf repo here: https://github.com/espressif/esp-idf/issues/8489

The ["resolution"](https://github.com/espressif/esp-idf/issues/8489#issuecomment-1289681866) was to run `idf.py fullclean` before a build.

I'm assuming that's what 'Clean All' does.

**Comment by valeros** [comment]
Hi @benwills ! There is a chance that the pyparsing package is broken for some reason. Could you please open a new terminal window directly in the IDE:
![image](https://user-images.githubusercontent.com/886732/213695876-5343dd2b-fba4-4a69-ba51-38401a0b2bcb.png)

And run `python -m pip install -U pyparsing --force-reinstall`

**Comment by benwills** [comment]
Hey @valeros. Thank you! That seems to have fixed it.

I really appreciate the help on that.
