### ISSUE TITLE
using espressif 5.0 in platformio w framework=arduino

### ISSUE THREAD

**Issue by MrSniffer** [platformio/platform-espressif32#1010]
I have a need of the latest 5.0 APIs from espressif with framework=arduino. 
I can compile, upload, etc. but my APIs are not supported at ESP32-S3 Release 5.0. They are at V4.4. How can I utilize the latest supported espressif APIs in plaformi.io? (Using ESP-IDF is not a solution for me!)

**Comment by Jason2866** [comment]
You can't, as long there is no Arduino esp32 based on IDF 5.0 done from espressif.
Platformio is in no way related in this.

**Comment by valeros** [comment]
The latest Arduino core v2.0.6 is based on IDF v4.4.3, API from v5.0 will be available in Arduino v3.0.
