### ISSUE TITLE
esp32-s3-devkitc-1 Boot Loop Issue

### ISSUE THREAD

**Issue by seulater** [platformio/platform-espressif32#1012]
Using the esp32-s3-devkitc-1 and IDF. 
PlatformIO Core 6.1.6 / Home 3.4.3

Created a new IDF project with the following. 

```
#include <stdio.h>

void app_main() 
{
    printf("Hi!\r\n");
}
```

When run, I get boot loop issues when using the following platforms. 
platform = espressif32@5.3.0
or
platform = espressif32@5.2.0

This is the output, and it just keeps repeating this:

> ESP-ROM:esp32s3-20210327
> Build:Mar 27 2021
> rst:0x1 (POWERON),boot:0xa (SPI_FAST_FLASH_BOOT)
> SPIWP:0xee
> mode:QIO, clock div:1
> load:0x3fce3808,len:0x164c
> ets_loader.c 78
> ESP-ROM:esp32s3-20210327
> Build:Mar 27 2021
> rst:0x7 (TG0WDT_SYS_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
> Saved PC:0x400454d5
> SPIWP:0xee
> mode:QIO, clock div:1
> load:0x3fce3808,len:0x164c
> ets_loader.c 78
> ESP-ROM:esp32s3-20210327
> Build:Mar 27 2021
> rst:0x7 (TG0WDT_SYS_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
> Saved PC:0x400454d5
> SPIWP:0xee
> mode:QIO, clock div:1
> load:0x3fce3808,len:0x164c
> ets_loader.c 78
> ESP-ROM:esp32s3-20210327
> Build:Mar 27 2021
> rst:0x10 (RTCWDT_RTC_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
> SPIWP:0xee
> mode:QIO, clock div:1
> load:0x3fce3808,len:0x164c
> ets_loader.c 78
> ESP-ROM:esp32s3-20210327
> Build:Mar 27 2021
> rst:0x7 (TG0WDT_SYS_RST),boot:0xa (SPI_FAST_FLASH_BOOT)

It works when I use the following
platform = espressif32 ( which is 6.0.0)
or
platform = espressif32@5.1.1

Platform.ini file 
```
[env:esp32-s3-devkitc-1]
;platform = espressif32
platform = espressif32@5.2.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
```

I need to use 5.1.1 because in 6.0.0 they removed mDNS, which I need.

**Comment by Jason2866** [comment]
Reason is using mode `mode:QIO` for bootloader. This is not possible.
Bootloader has to use mode `DOUT` or `DIO`.

**Comment by Jason2866** [comment]
Guess work will not help. You need to know exactly which flash type your board has.
Standard or OPI flash? Does it have PSRAM? If yes which flash Type?
And the correct flash size of your board is needed too.
If you have all this Infos, we will make it work :-)

**Comment by Jason2866** [comment]
This is not the real reason/fix, just a workaround.
