### ISSUE TITLE
Documentation for Adafruit QT Py ESP32-C3 says no internal debugger, yet Windows Device Manager reports USB JTAG

### ISSUE THREAD

**Issue by RufusVS** [platformio/platform-espressif32#1014]
The PlatformIO documentation page for the Adafruit QT Py ESP32-C3 says an external debugger is required, yet when I plug in my board, a USB JTAG serial device is reported.   Is this a documentation error or is the JTAG serial port unusable?_

**Comment by Jason2866** [comment]
The inbuilt jtag device does work. No need for an extra external jtag debugging device.

**Comment by RufusVS** [comment]
@Jason2866 Thanks, that what I thought.  Now my problem is: How do I configure VSCODE/PlatformIO/GDB/OpenOCD/Expressif to recognize the internal jtag and use it?

**Comment by Jason2866** [comment]
An ocd debug env example
```
[env:debug32c3cdc-ocd]
build_type              = debug
board                   = adafruit_qtpy_esp32c3
debug_tool              = esp-builtin
upload_protocol         = esp-builtin
debug_init_break        = tbreak setup
```

**Comment by RufusVS** [comment]
It turns out to be an incorrect driver that windows chooses.    You can get the tool installer [here.](https://dl.espressif.com/dl/esp-idf/?idf=4.4)   Then make sure to select: WinUSB support for JTAG.   After the driver is installed, go to device manager and select the JTAG device (under USB Serial Bus Devices).   Right-click and select Update Driver/Search automatically.  It should find the new driver called USB JTAG debug unit or something like that.  Install the new driver.  When I checked Properties/Driver I got this:
![image](https://user-images.githubusercontent.com/6877082/215308673-80ee9a42-75b9-40f5-9395-94e795f73df8.png)
