### ISSUE TITLE
Can't compile Arduino as an ESP-IDF component when using PIO release v5.3.0

### ISSUE THREAD

**Issue by GKFernandes** [platformio/platform-espressif32#1031]
Hello everyone,

So, I've been trying to make a blank code example work using Arduino as an ESP-IDF Component inside Platformio.

I've followed the guidelines at: https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/esp-idf_component.html 

I intend to build this project to work with ESP32-C3, I'll leave a picture of my platformio.ini file, as well as the current error message when trying to build.

![inifile](https://user-images.githubusercontent.com/87312710/218812752-33d52c20-9afe-4021-95ca-523f9b973433.png)
![cmakefile1](https://user-images.githubusercontent.com/87312710/218812790-cc500661-c9cb-4638-afb5-9b17aff047ee.png)
![errorcode1](https://user-images.githubusercontent.com/87312710/218812816-b96c139a-cc00-4f53-8a56-a84cfa02c695.png)

Edit 1: I see now that Python dependencies may be an issue as well, I know that release 6.0 fixes that, but unfortunately I can't use release 6.0 with Arduino as a component.

Edit 2: Running Menuconfig for the project works fine.

Many thanks!

**Comment by Jason2866** [comment]
Your setup is wrong
```
framework = arduino, espidf
```
You can look at the examples how it should look like https://github.com/platformio/platform-espressif32/tree/develop/examples

**Comment by GKFernandes** [comment]
Hello there @Jason2866 ,

Thank you for the response.

I've changed my setup, now it seems some Arduino function references are not being 'pulled' by the framework, Arduino setup() and loop() functions seem to not be found.

By the way, this same error was happening when using only  framework = espidf

![undef_reference](https://user-images.githubusercontent.com/87312710/218857410-bf758fc5-de99-4def-b6d7-d1893eaff821.png)

**Comment by Jason2866** [comment]
> In my project, main.cpp includes the same files as the Blink.cpp in the examples, but without the rest of the code, only the includes.

It is not the way it works. Look at the examples.

**Comment by GKFernandes** [comment]
> > In my project, main.cpp includes the same files as the Blink.cpp in the examples, but without the rest of the code, only the includes.
> 
> It is not the way it works. Look at the examples.

Sorry, which part doesn't work? The file is almost exactly the same as the blink example.

I've tried build the espidf-arduino-blink example using framework = arduino, espidf, it compiles just fine, but I see it does not add the components/arduino folder, like the ESP-IDF documentation mentions.

In a previous project, I managed to use arduino as a component by creating a component folder inside the project directory and placing the Arduino libraries inside the include folder, I was using release espressif32@3.2.1 at the time and framework = espidf.

Guess I will try to use some IDF functions/properties and menuconfig to see if it works.

**Comment by valeros** [comment]
> I've tried build the espidf-arduino-blink example using framework = arduino, espidf, it compiles just fine, but I see it does not add the components/arduino folder, like the ESP-IDF documentation mentions.

The Arduino component is added automatically when you specify `framework = arduino, espidf`.

> In a previous project, I managed to use arduino as a component by creating a component folder inside the project directory and placing the Arduino libraries inside the include folder, I was using release espressif32@3.2.1 at the time and framework = espidf.

Again, PlatformIO handles downloading and importing Arduino core as an IDF component when you specify `framework = arduino, espidf` in your `platformio.ini`. Your previous approach is completely possible, but in that case you're on your own as we cannot help debug your custom setup.

The recommendation here is to build your project on the basis of available examples.

**Comment by DrakoPOD** [comment]
I have a problem when add arduino to framework, I use an idf components "REQUIRES esp_driver_i2c" results in an error

````
fatal: not a git repository (or any of the parent directories): .git
CMake Error at C:/Users/<userName>/.platformio/packages/framework-espidf@3.40407.240606/tools/cmake/build.cmake:201 (message):
  Failed to resolve component 'esp_driver_i2c'.
````

My CMakeList is:

```
FILE(GLOB_RECURSE app_sources ${CMAKE_SOURCE_DIR}/src/*.*)

idf_component_register(
  SRCS ${app_sources}
  REQUIRES esp_driver_i2c
)
```

**Comment by Jason2866** [comment]
Arduino needs the IDF component `esp_driver_i2c` which is not found. I don't see this driver in IDF 4.4.x so the error is as expected
