### ISSUE TITLE
why does program compile larger in platformiO than in Arduino?

### ISSUE THREAD

**Issue by wegunterjr** [platformio/platform-espressif32#104]
When I compile with PlatformIO i get a program of almost 1.9MB, but when I compile with arduino I get only 1.37....

**Comment by ivankravets** [comment]
Do you use the latest Arduino Core with Arduino IDE?

**Comment by wegunterjr** [comment]
l think so. I pulled in the latest from the github and ran the get.exe How can i verify? 
WHat should I expect to see in regards to difference in size.

**Comment by ivankravets** [comment]
Please provide screenshots with memory usage from Arduino IDE and PIO IDE.

**Comment by wegunterjr** [comment]
Arduino 1.8.4
![image](https://user-images.githubusercontent.com/624637/42218620-76a6b9c6-7e86-11e8-90de-7bd07463dbce.png)

Same program compiled in Platformio
DATA:    [==        ]  24.2% (used 71444 bytes from 294912 bytes)
PROGRAM: [========= ]  90.5% (used 1778762 bytes from 1966080 bytes)

**Comment by ivankravets** [comment]
Do you use the latest version of dev/platform v1.1.0? PIO IDE > PIO Home > Platforms

**Comment by wegunterjr** [comment]
I am running PlatformIO 3.6.0a4

**Comment by wegunterjr** [comment]
![image](https://user-images.githubusercontent.com/624637/42218870-2fb75308-7e87-11e8-87eb-1542b390f7c5.png)

and this version of PlatformIO:  You're up-to-date!
PlatformIO 3.6.0a4 is currently the newest version available.

**Comment by ivankravets** [comment]
Thanks! Could you provide a simple project to reproduce this issue? Or pack it to archive and send to me@ikravets.com? We will not share it in public.

**Comment by wegunterjr** [comment]
@ivankravets  will do.  Sent.

**Comment by wegunterjr** [comment]
@ivankravets i saw in the Espressif/arduino-esp32 gitter some conversations this morning about a recent update also causing someone else a problem...no resolution in the channel.

**Comment by ivankravets** [comment]
See the latest messages in https://gitter.im/espressif/arduino-esp32
