### ISSUE TITLE
Tracing back to esp-idf change

### ISSUE THREAD

**Issue by softwaregravy** [platformio/platform-espressif32#1040]
Bit of a newbie question.

I am hitting hangs at the outset of OTA with large binary sizes. This seems to be the same as these issues: https://github.com/espressif/esp-idf/issues/6723 and https://github.com/espressif/esp-idf/issues/4916 

This issue has supposedly been fixed in https://github.com/espressif/esp-idf/pull/5246 

I'm trying to check that I have these fixes available to me to eliminate it as a cause of my errors. I'm trying to trace which version of esp-idf I have in my project given I am running [v5.2.0](https://github.com/platformio/platform-espressif32/releases/tag/v5.2.0
) of this platform. Which I think has [v4.4.2](https://github.com/espressif/esp-idf/releases/tag/v4.4.2) of ESP-IDF? which includes that [PR](https://github.com/espressif/esp-idf/commit/3cb655eaabd136700071c9225f33715ea4915917)? or no?  

Thank you in advance.

**Comment by valeros** [comment]
Hi @softwaregravy ! That fixes should be available since v4.2, so yes v4.4.2 should contain them as well:
![image](https://user-images.githubusercontent.com/886732/220357622-a61734ab-8fa4-49c2-9195-0b0a92c15d86.png)
