### ISSUE TITLE
AT commands with Platformio

### ISSUE THREAD

**Issue by RitaAJ** [platformio/platform-espressif32#1043]
Hello everyone, I Am using ESP32C3/Mini in my small project. I want to replicate or copy all AT commands supported by ESP's own IDF framework in Platformio. Is it any way to do it so that I can use the same ESP32C3 HAVING AT commands for my other functionalities. Our other the way how AT commands can be used with platformio framwork.

**Comment by valeros** [comment]
Hi @RitaAJ ! This repository is not the right place for such questions, please forward to https://community.platformio.org/
