### ISSUE TITLE
v6.1.0 - esptool v.4.5.0 - esp32-s3 - A fatal error occurred: Packet content transfer stopped

### ISSUE THREAD

**Issue by BlueAndi** [platformio/platform-espressif32#1051]
fyi: https://github.com/espressif/esptool/issues/857

According to the info in the esptool issue, the esptool v4.5.1 fixes the problem.

**Comment by valeros** [comment]
Hi @BlueAndi, thanks for reporting, the latest v4.5.1 has been uploaded to the registry. You can specify the latest version directly in your platformio.ini:
```ini
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
platform_packages = 
    tool-esptoolpy @ ~1.40501.0
```
