### ISSUE TITLE
Does not change CONFIG_PARTITION_TABLE_OFFSET

### ISSUE THREAD

**Issue by butaikis** [platformio/platform-espressif32#1056]
Hi I have a problem with the CONFIG_PARTITION_TABLE_OFFSET parameter

`\packages\framework-arduinoespressif32\tools\sdk\esp32\qio_qspi\include\sdkconfig.h`

I built a bootloader with a table offset of 0xB000, and the program assembled in platformio does not start. 
I changed CONFIG_PARTITION_TABLE_OFFSET in `sdkconfig.h` (qio_spi) but it didn't give any result.

Please tell me how can I change this parameter?

By the way, if you build a bootloader with a table offset of 0x8000 (by default), then everything works.

The last lines of my program's error

```
E (1058) esp_core_dump_flash: No core dump partition found!
E (1065) partition: No MD5 found in partition table
E (1069) partition: load_partitions returned 0x105

assert failed: esp_ota_get_running_partition esp_ota_ops.c:553 (it != NULL)
```

**Comment by Jason2866** [comment]
The offset is hard coded. `sdkconfig.h` is the info of the values used. You can't change anything here.

**Comment by butaikis** [comment]
Hello, @Jason2866. Thanks for the advice.
` ("0x8000", join(env.subst("$BUILD_DIR"), "partitions.bin")),`
But this parameter only affects the download using esptool.py , it does not affect compilation in any way. I checked.

**Comment by Jason2866** [comment]
yes, compilation is NOT the problem at all. You can flash the compiled code at any address.
During flashing with esptool.py it needs placing at the place where it is expected.
So this part is mandatory.

**Comment by butaikis** [comment]
Please tell me how to solve this problem, I have been trying to do this for a long time.

1. bootloader is built separately (esp-idf) with CONFIG_PARTITION_TABLE_OFFSET 0x8000
2. I load the table with an offset of 0x8000
3. I upload the application separately assembled in platformio to the ota_0 (0x10000) section

Everything works!

1. Now I have a larger bootloader size, then the CONFIG_PARTITION_TABLE_OFFSET parameter is 0xB000
2. I load the table with an offset of 0xB000
3. I upload the application separately assembled in platformio to the ota_0 (0x10000) section

The app is not working.

> E (1058) esp_core_dump_flash: No core dump partition found!
> E (1065) partition: No MD5 found in partition table
> E (1069) partition: load_partitions returned 0x105
> 
> assert failed: esp_ota_get_running_partition esp_ota_ops.c:553 (it != NULL)

**Comment by butaikis** [comment]
It's decided. Transferring the project to ESP-ID PlatformIO, using 
`framework = esp-idf, arduino`
