### ISSUE TITLE
ESP32 Flash Write Freeze (SPIFFS and EEPROM)

### ISSUE THREAD

**Issue by savejeff** [platformio/platform-espressif32#1062]
I'm experiencing very weird behavior with flash writes. 

I've already posted on the espressif Arduino core repo but I'm starting to think this might be a platformio related problem as the same code works fine with the Arduino ide

here is the issue: https://github.com/espressif/arduino-esp32/issues/8001

it looks to me as if some gcc command building is different from the Arduino ide ones that cause this.
random code changes toggle the freeze. even changing comments has an effect on the freezes

could somebody from the platformio team check out the repo I published and check if they can reproduce this?
here is the small repo with the demo code: https://github.com/savejeff/ESP32_Flash_Freeze_Demo

**Comment by valeros** [comment]
Resolved in https://github.com/espressif/arduino-esp32/issues/8001
