### ISSUE TITLE
firmware.map: Invalid argument

### ISSUE THREAD

**Issue by litian85734** [platformio/platform-espressif32#1068]
HI, Sir:
     I meet a  build issue that happen "firmware.map: Invalid argument" when I set " platform = espressif32 "  in plagformio.ini file.   as below
     plagformio.ini  file:

```ini
 [env:esp wrover kit]
 platform = espressif32    
```
build information:
```=================================================================================
    c:/users/tommy/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32- 
      elf/bin/ld.exe: cannot open map file F:/TestPlatformIOV1.6/.pio/build/esp wrover kit/firmware.map: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      *** [.pio\build\esp wrover kit\firmware.elf] Error 1
    ====================================================================================
```
![image](https://user-images.githubusercontent.com/20023789/229967911-33852a89-888d-4f56-8c45-b3835a5eab5b.png)

But if set "espressif32 @ ~3.5.0" the build is ok,
```ini
[env:esp wrover kit]
platform = espressif32 @ ~3.5.0
```
May  I know how to fix this issue when I use latset espressif32 vserion?

Thanks

**Comment by valeros** [comment]
There are non-ascii characters in the project path on the screenshot. Try to move the project to a folder with only English letters in path.

**Comment by jasonwang01** [comment]
I meet the same issue in stm32 platformio

c:/users/jason/.platformio/packages/toolchain-gccarmnoneeabi@1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/ld.exe: cannot open map file 'D:\Personal\Desktop\public\github\bootloader\src\.pio\build\flash_2400/firmware.map': Invalid argument
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\flash_2400\firmware.elf] Error 1

**Comment by QFFS** [comment]
> I meet the same issue in stm32 platformio
> 
> c:/users/jason/.platformio/packages/toolchain-gccarmnoneeabi@1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/ld.exe: cannot open map file 'D:\Personal\Desktop\public\github\bootloader\src.pio\build\flash_2400/firmware.map': Invalid argument collect2.exe: error: ld returned 1 exit status *** [.pio\build\flash_2400\firmware.elf] Error 1

I also meet this problem in stm32 platformio, Did you solve it?
