### ISSUE TITLE
Memory leakage with WiFi.mode()

### ISSUE THREAD

**Issue by muhdRiz07** [platformio/platform-espressif32#1069]
`#include "WiFi.h"

void setup()
{
    Serial.begin(115200);

    // Set WiFi to station mode and disconnect from an AP if it was previously connected
    Serial.println("\nFree heap : " + String(ESP.getFreeHeap()));
    Serial.println("Free min heap : " + String(ESP.getMinFreeHeap()));
    WiFi.mode(WIFI_STA);
    Serial.println("\nFree heap : " + String(ESP.getFreeHeap()));
    Serial.println("Free min heap : " + String(ESP.getMinFreeHeap()));
    WiFi.disconnect();
    delay(100);

    Serial.println("Setup done");
}

void loop()
{
    Serial.println("scan start");

    // WiFi.scanNetworks will return the number of networks found
    int n = WiFi.scanNetworks();
    Serial.println("scan done");
    if (n == 0) {
        Serial.println("no networks found");
    } else {
        Serial.print(n);
        Serial.println(" networks found");
        for (int i = 0; i < n; ++i) {
            // Print SSID and RSSI for each network found
            Serial.print(i + 1);
            Serial.print(": ");
            Serial.print(WiFi.SSID(i));
            Serial.print(" (");
            Serial.print(WiFi.RSSI(i));
            Serial.print(")");
            Serial.println((WiFi.encryptionType(i) == WIFI_AUTH_OPEN)?" ":"*");
            delay(10);
        }
    }
    Serial.println("");

    // Wait a bit before scanning again
    delay(5000);
}`

Hi, here I am trying WiFi scanning but facing reduction in memory after scanning. Before WiFi.mode(WIFI_STA) the heap size is 311588 but after WiFi.mode(WIFI_STA) the free heap size reduces to 265932, consumes 45656 bytes of memory. May I know why it is consumes this much memory and how to solve it??

Thanks in advance.

**Comment by valeros** [comment]
Hi @muhdRiz07 ! This repository is not the right place for such questions, please forward your question to https://github.com/espressif/arduino-esp32
