### ISSUE TITLE
Board "LilyGo T-Display-S3" fails to initialize

### ISSUE THREAD

**Issue by brha8286** [platformio/platform-espressif32#1071]
When creating a new project with board [LilyGo T-Display-S3](https://docs.platformio.org/en/latest/boards/espressif32/lilygo-t-display-s3.html?utm_source=platformio&utm_medium=piohome#id1), `Error: Unknown board ID 'lilygo-t-display-s3'` appears.  Attempted on multiple machines, VSCode up-to-date.

**Comment by valeros** [comment]
Hi @brha8286, are you sure you're using the latest version of the platform v6.1.0? Please run `pio pkg update -g -p espressif32` in the IDE terminal.

**Comment by cyberman54** [comment]
Wrong board name. The correct one is:
lilygo_t_display_s3

**Comment by valeros** [comment]
Closing as no further information was given, feel free to reopen if you still need help.

**Comment by xbmcnut** [comment]
> Hi @brha8286, are you sure you're using the latest version of the platform v6.1.0? Please run `pio pkg update -g -p espressif32` in the IDE terminal.

Thanks so much. This helped me build [this](https://github.com/rzeldent/esp32-flightradar24-ttgo/tree/feature/lilygo-t-display-s3) project which was throwing up the same error.

**Comment by pixelwave** [comment]
> Hi @brha8286, are you sure you're using the latest version of the platform v6.1.0? Please run `pio pkg update -g -p espressif32` in the IDE terminal.

That solved the issue!

**Comment by fightforlife** [comment]
I still get this error after trying everything above.
Vscode on Windows with platformio: Core 6.1.15·Home 3.4.4

```
[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
```

````
Processing lilygo-t-display-s3 (platform: espressif32; board: lilygo-t-display-s3; framework: arduino)
---------------------------------------------------------------------------------------------------------------
UnknownBoard: Unknown board ID 'lilygo-t-display-s3'
````
