### ISSUE TITLE
ccache settings does not apply to pio

### ISSUE THREAD

**Issue by dibalavs** [platformio/platform-espressif32#1073]
I am tryint to use ccache to sppedup re-compilation of project. But all my attempts was failed. 

**Attempt 1.**
Try to enable CCACHE_ENABLE in CMake flags:
in platformio.ini I added next line:
board_build.cmake_extra_args = -DCCACHE_ENABLE=ON
and re-build project. (pio run -v)
I am able to see status of ccache in cmake verbose log:

`-- ccache will be used for faster recompilation
`

Also I checked ninja file (rules.Ninja at .pio/build/heltec_wifi_lora_32_V2)

`  command = ccache C:\Users\dybala\.platformio\packages\toolchain-xtensa-esp32\bin\xtensa-esp32-elf-gcc.exe $DEFINES $INCLUDES $FLAGS -MD -MT $out -MF $DEP_FILE -o $out   -c $in  
`

It shout be used. But actually it looks like pio replace compiler line and remove ccache mention.

**Attempt2.**
I found that pio override env CC/CXX/AS with different values. My idea was to use post script to add ccache 
in platformio.ini I wrote:
`extra_scripts =
    ;pre:use_ccache.py
    post:use_ccache.py
`

content of use_ccache.py:
`Import("env")

env.Replace(AS="ccache " + env.get("AS"))
env.Replace(CC="ccache " + env.get("CC"))
env.Replace(CXX="ccache " + env.get("CXX"))
`
Idea - is just add ccache prefix. 

Actually pio is executing my script (I can see debug logs). But it does not apply env settings.

**Attempt 3**
I found, where original variables (AS, CC, CXX) was set  and try to add ccache prefix at %USER%/.platformio/platforms/expressif32/builder/main.py:
`    AR="%s-elf-ar" % toolchain_arch,
     AS="ccache %s-elf-as" % toolchain_arch, 
     CC="ccache %s-elf-gcc" % toolchain_arch,                                                                                                     
     CXX="ccache %s-elf-g++" % toolchain_arch,  
    GDB="%s-elf-gdb" % toolchain_arch, 
`

But scons has some magic transormation.  It command line too long, it save arguments to temporary file and launch first (cmd[0]) with @path/to/file , as a result next command will be executed:
`ccache @ c:\path\to\temporary\file`
Actually ccache does not expect such turn. And compilation fails.

**Attempt 4**
ccache can operate with symlinks. 
So you need to add fake compilers which points to ccache executable:
```
xtensa-esp32-elf-as.exe -> ccache.exe
xtensa-esp32-elf-gcc.exe -> ccache.exe
xtensa-esp32-elf-g++.exe -> ccache.exe
```

And put them to directory which pointed by PATH environment variable.
Actual result - pio does not call such compilers.  This is because pio adds path to real compiler at fist place of PATH env instead of last place:
`PATH:C:\Users\dybala\.platformio\packages\toolchain-xtensa-esp32\bin;C:\Users\dybala\.platformio\packages\toolchain-esp32ulp\bin;C:\Users\dybala\.platformio\packages\tool-esptoolpy;C:\Users\dybala\.platformio\penv\Scripts;C:\Users\dybala\.platformio\penv;C:\Users\dybala\.platformio\python3;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Work\bin;C:\Users\dybala\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\dybala\AppData\Local\Programs\Python\Python310\;C:\Users\dybala\AppData\Local\Microsoft\WindowsApps;C:\Users\dybala\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\dybala\AppData\Local\Programs\Git\cmd`

Path with ccache and fake compilers  - C:\Work\bin
Path with actual compilers - C:\Users\dybala\.platformio\packages\toolchain-xtensa-esp32\bin

The issue is that PIO add paths at fist place instead of last place.

Please fix using of ccache, currently pio prevents using it in all ways.

**Comment by tomaszduda23** [comment]
Something like this would do https://github.com/platformio/platform-nordicnrf52/pull/193
