### ISSUE TITLE
ESP32 Logging 

### ISSUE THREAD

**Issue by meakashrao** [platformio/platform-espressif32#1085]
<img width="669" alt="Img 1" src="https://user-images.githubusercontent.com/120377875/234522540-35f86b8b-f0b8-4f90-ae78-780bf0924657.png">

As can be seen I am trying to set ESP Logging by using (build_flags = -DCORE_DEBUG_LEVEL = ARDUHAL_LOG_LEVEL_INFO) but some it fails because of some file not being present but if build_flags = -DCORE_DEBUG_LEVEL=3 sometimes I am able to compile and make it work and sometimes the same error as in the above image is present.
<img width="636" alt="Img 2" src="https://user-images.githubusercontent.com/120377875/234522749-0659d98e-e3ef-4a1d-a67d-c2d6c3f79e71.png">

and the output is generated as follows: 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/120377875/234521180-3ac355d6-d594-4326-95ff-723d129379b9.png">

Can someone help me out with what's wrong when I try to use ARDUHAL_LOG_LEVEL_INFO as I also want to use colors for different types of logs and how to do that

**Comment by valeros** [comment]
Hi @meakashrao , please remove redundant whitespaces between the name and value of your macro, it should be
```cpp
build_flags =
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
```
