### ISSUE TITLE
6.2.0 cannot convert 'const char*' to 'const __FlashStringHelper*'

### ISSUE THREAD

**Issue by MikolajO** [platformio/platform-espressif32#1089]
Relese 6.2.0 gives me an wall of errors when using F("string from progmem")

cannot convert 'const char*' to 'const __FlashStringHelper*'

C:/Users/<user>/.platformio/packages/framework-arduinoespressif32/cores/esp32/WString.h:38:28: note: in definition of macro 'F'
 #define F(string_literal) (string_literal)

Had to switch in .ini: platform = espressif32@6.1.0
to work it again correctly. If You need more details to find error let me know.

**Comment by Jason2866** [comment]
This is a Arduino issue, not a Platformio one. Please close and go to https://github.com/espressif/arduino-esp32/issues
