### ISSUE TITLE
Issue with Special Characters and ESP32

### ISSUE THREAD

**Issue by nh1628** [platformio/platform-espressif32#1097]
When trying to compile an ESP32-S3 through my onedrive folder containing a "-" and a "," it has issues with generating firmware map files and compiling. When creating a new project and compiling in a folder without spaces and special characters everything generates and compiles correctly. Copying the generated files to the onedrive folder will also not work.

**Comment by Jason2866** [comment]
Using special chars in path is always a bad idea.

**Comment by valeros** [comment]
Hi @nh1628 , I'm not sure about the `-` character in paths, but `,` is definitely not desirable, please don't use such special characters in the path to you project. As for the Onedrive folder,  please share here the error message.
