### ISSUE TITLE
ESP-IDF version is not right in 6.3.1

### ISSUE THREAD

**Issue by swortain** [platformio/platform-espressif32#1114]
hi, I got wrong esp-idf version when use the latest version(6.3.1).
this is the log when i compile my project.

    Processing ESP32-S3 (platform: espressif32; board: esp32-s3-devkitc-1; framework: espidf)
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
    CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-s3-devkitc-1.html
    PLATFORM: Espressif 32 (6.3.1) > Espressif ESP32-S3-DevKitC-1-N8 (8 MB QD, No PSRAM)
    HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
    DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
    PACKAGES:
    - framework-espidf @ 3.50002.230512 (5.0.2)
    - tool-cmake @ 3.16.4
    - tool-esptoolpy @ 1.40501.0 (4.5.1)
    - tool-idf @ 1.0.1
    - tool-mconf @ 1.4060000.20190628 (406.0.0)
    - tool-ninja @ 1.9.0
    - toolchain-esp32ulp @ 1.23500.220830 (2.35.0)
    - toolchain-riscv32-esp @ 11.2.0+2022r1
    - toolchain-xtensa-esp32s3 @ 11.2.0+2022r1
    Reading CMake configuration...
    LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
    LDF Modes: Finder ~ chain, Compatibility ~ soft
    Found 0 compatible libraries
    Scanning dependencies...
    No dependencies       
    Building in debug mode
    Retrieving maximum program size .pio\build\ESP32-S3\firmware.elf
    Checking size .pio\build\ESP32-S3\firmware.elf
    Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
    RAM:   [=         ]   9.2% (used 30052 bytes from 327680 bytes)  
    Flash: [=======   ]  71.6% (used 751029 bytes from 1048576 bytes)
    ========================================================================================================= [SUCCESS] Took 19.32 seconds =========================================================================================================

but I got the log from esp32s3 after burn the code in it through serial. which declare itself is running at v5.0.1

    ESP-ROM:esp32s3-20210327
    Build:Mar 27 2021
    rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
    Saved PC:0x403761c1
    SPIWP:0xee
    mode:DIO, clock div:1
    load:0x3fce3810,len:0x1658
    load:0x403c9700,len:0xbe0
    load:0x403cc700,len:0x2d9c
    entry 0x403c9900
    I (29) boot: ESP-IDF 5.0.1 2nd stage bootloader
    I (29) boot: compile time 15:42:48
    I (29) boot: chip revision: v0.1
    I (31) boot.esp32s3: Boot SPI Speed : 80MHz
    I (36) boot.esp32s3: SPI Mode       : DIO
    I (40) boot.esp32s3: SPI Flash Size : 8MB
    I (45) boot: Enabling RNG early entropy source...
    I (51) boot: Partition Table:
    I (54) boot: ## Label            Usage          Type ST Offset   Length
    I (61) boot:  0 nvs              WiFi data        01 02 00009000 00006000
    I (69) boot:  1 phy_init         RF data          01 01 0000f000 00001000
    I (76) boot:  2 factory          factory app      00 00 00010000 00100000
    I (84) boot: End of partition table
    I (88) esp_image: segment 0: paddr=00010020 vaddr=3c080020 size=2313ch (143676) map
    I (122) esp_image: segment 1: paddr=00033164 vaddr=3fc96500 size=035bch ( 13756) load
    I (125) esp_image: segment 2: paddr=00036728 vaddr=40374000 size=098f0h ( 39152) load
    I (137) esp_image: segment 3: paddr=00040020 vaddr=42000020 size=7eaf4h (518900) map
    I (230) esp_image: segment 4: paddr=000beb1c vaddr=4037d8f0 size=08bdch ( 35804) load
    I (246) boot: Loaded app from partition at offset 0x10000
    I (246) boot: Disabling RNG early entropy source...
    I (257) cpu_start: Pro cpu up.
    I (258) cpu_start: Starting app cpu, entry point is 0x403757ac
    I (0) cpu_start: App cpu up.
    I (272) cpu_start: Pro cpu start user code
    I (272) cpu_start: cpu freq: 160000000 Hz
    I (272) cpu_start: Application information:
    I (275) cpu_start: Project name:     230520_esp32s3_keyboard_bluetoo
    I (282) cpu_start: App version:      1
    I (287) cpu_start: Compile time:     May 20 2023 15:41:05
    I (293) cpu_start: ELF file SHA256:  bc84493dbd9fc985...
    I (299) cpu_start: ESP-IDF:          5.0.1
    I (303) cpu_start: Min chip rev:     v0.0
    I (308) cpu_start: Max chip rev:     v0.99 
    I (313) cpu_start: Chip rev:         v0.1
    I (318) heap_init: Initializing. RAM available for dynamic allocation:
    I (325) heap_init: At 3FC9DA68 len 0004BCA8 (303 KiB): DRAM
    I (331) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
    I (338) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
    I (344) heap_init: At 600FE010 len 00001FF0 (7 KiB): RTCRAM
    I (351) spi_flash: detected chip: generic
    I (355) spi_flash: flash io: dio
    I (360) coexist: coexist rom version e7ae62f
    I (364) cpu_start: Starting scheduler on PRO CPU.
    I (0) cpu_start: Starting scheduler on APP CPU.
    I (413) HID_DEV_DEMO: [nvsconfig_init]Opening Non-Volatile Storage (NVS) handle... 
    I (413) HID_DEV_DEMO: setting hid gap, mode:1
    I (423) BT_INIT: BT controller compile version [80abacd]
    I (423) phy_init: phy_version 540,a5d905b,Oct 20 2022,19:36:11
    I (473) system_api: Base MAC address is not set
    I (473) system_api: read default base MAC address from EFUSE
    I (473) BT_INIT: Bluetooth MAC: 60:55:f9:f5:5c:a2

**Comment by valeros** [comment]
Hi @swortain, seems like a leftover from a previous package, try deleting the following file:

`c:\Users\YOUR_USER\.platformio\packages\framework-espidf\version.txt`

**Comment by swortain** [comment]
ok，thx a lot
