### ISSUE TITLE
ESP32 partition table will not work and results in a bootloop

### ISSUE THREAD

**Issue by boura0013** [platformio/platform-espressif32#1115]
I am using platformIO with an ESP32 devkit board and 1MB of app size on default file partitions is not enough for my app so I made this custom partition.csv file that will be compiled and flashed to the board through platformIO but will result in a SW_RESET bootloop. Can someone tell me what is wrong with this partition table or if something else is the issue?
```
# Name, type, subtype, offset, size, flags
#partition table with spiffs
nvs, data, nvs, 0x9000, 0x24000,
otadata, data, ota, 0x2D000, 0x2000,
ota_0, app, ota_0, 0x30000, 0x190000,
storage, data, spiffs, 0x1C0000, 0xA0000,
ota_1, app, ota_1, 0x260000, 0x190000,
```
The bootloop:
```
rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
ets Jul 29 2019 12:21:46
```

**Comment by valeros** [comment]
Hi @boura0013, I'm afraid the issue tracker in this repo is not the right place to look for help with specific projects.

**Comment by timf34** [comment]
I'm facing this same issue - seems like this is more common than a specific project. 

This issue was also not resolved here: https://community.platformio.org/t/esp32-boot-loop-when-changing-partition-table-using-default-8m-csv/28818/14
