### ISSUE TITLE
Support for ESP32-C6

### ISSUE THREAD

**Issue by TimmyRB** [platformio/platform-espressif32#1116]
Support for ESP32-C6, ESP32-C6-WROOM-1 and ESP32-C6-DevKitC-1

**Comment by Jason2866** [comment]
Currently the ESP32-C6 is not supported in a release version of IDF nor Arduino.

**Comment by lboue** [comment]
ESP32-c6 is now supported via ESP-IDF 5.1
https://github.com/espressif/esp-idf/releases/tag/v5.1
