### ISSUE TITLE
New Board Request: Olimex ESP32-PRO

### ISSUE THREAD

**Issue by StuartRothrock** [platformio/platform-espressif32#115]
Please add the board definition, libs, etc for the Olimex ESP32-PRO - Here is a link to the product.
https://www.olimex.com/Products/IoT/ESP32-PRO/open-source-hardware

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-espressif32/commit/7c046e4a175fad49807c4cb3cf40a65680acaeed
