### ISSUE TITLE
Got the unrecognized status code '404' when downloaded 

### ISSUE THREAD

**Issue by osboy** [platformio/platform-espressif32#1164]
After completing the installation, compile for the first time.

IDE terminal show:
Resolving esp32dev-ble dependencies...
Tool Manager: Installing platformio/framework-arduinoespressif32 @ ~3.20007.0
Tool Manager: Warning! Package Mirror: Got the unrecognized status code '404' when downloaded https://dl.registry.ns3.platformio.org/tools/1e/cb/39ed81df991fcbfebb10c7c1e38050cafad9dcb5910a3ec114b49cf1d405/framework-arduinoespressif32-3.20007.0.tar.gz

**Comment by ivankravets** [comment]
Thanks, fixed!

**Comment by osboy** [comment]
It works now ,Thank you
