### ISSUE TITLE
Support for esp-idf 5.1 and 5.0.3

### ISSUE THREAD

**Issue by western-hoolock** [platformio/platform-espressif32#1174]
I'm looking to try esp-idf 5.1 and esp-idf 5.0.3. Seeing some odd bugs that, by looking at the esp-idf release notes, might be fixed in those versions. Unfortunately platform-espressif32 only goes up to 5.0.2 yet.
Is there a guide I can follow or an easy way for me to manually replace the esp-idf with 5.0.3 or 5.1? If not, any estimates for when 5.1/5.0.3 will be supported?

**Comment by Jason2866** [comment]
Latest development version supports IDF 5.1

**Comment by western-hoolock** [comment]
Missed that, that should work, thanks.
