### ISSUE TITLE
Core-0 Time for a particular Task

### ISSUE THREAD

**Issue by meakashrao** [platformio/platform-espressif32#1177]
So, I have defined a core 0 task with
xTaskCreatePinnedToCore(MotorCurrent_TaskCode, "MotorCurrent_Task",  2000, NULL, tskIDLE_PRIORITY, &MotorCurrent_Task, 0); 

and I have made sure with the .ini file that everything runs on core-1, as I also have BLE in the code (I checked, notify does use Core-1 in BLECharacteristic.cpp and other library files )
<img width="451" alt="image" src="https://github.com/platformio/platform-espressif32/assets/120377875/e09cc063-78b7-480e-9b3f-941bb2837456">

Now, 
void MotorCurrent_TaskCode(void *pvParameters)
{
    esp_timer_handle_t timer = NULL;
    uint64_t startTime, endTime;
     uint64_t executionTimeMicros;

    esp_timer_create_args_t timer_config = {
        .callback = NULL,
        .name = "task_timer"
    };
    esp_timer_create(&timer_config, &timer);

    for (;;)
    {
        startTime = esp_timer_get_time();
        motor_protection.read_Current_Sense();
        endTime = esp_timer_get_time();
    
        executionTimeMicros = endTime - startTime;
        Serial.printf("Core 0 Execution Time: %llu microseconds\n", executionTimeMicros);
    }
}

Now, the Output
<img width="369" alt="image" src="https://github.com/platformio/platform-espressif32/assets/120377875/d55e50b7-d09b-423c-ba2c-2847d6e9445d">

What I am trying to find is, why this difference in the Execution Time

This is a very time sensitive task, I have a window of 4 ms and I need to take maximum samples of Motor Current.
Also, 
<img width="590" alt="image" src="https://github.com/platformio/platform-espressif32/assets/120377875/2162feec-81be-40f5-bb48-53085f4182bc">
This time data is when the Motor was not running, so it will just check the if loop and exit is what I believe

please help me with wherever I am wrong

**Comment by valeros** [comment]
Hi @meakashrao ! Unfortunately, this repository is not the right place to ask generic questions about frameworks. You'd better ask for help in the official Arduino ESP32 resources like https://esp32.com/index.php
