### ISSUE TITLE
When I was using platformio, I found an error when I used esp32 -2.0.3. How can I solve it?

### ISSUE THREAD

**Issue by LuBaker34** [platformio/platform-espressif32#1187]
Can you help me solve it? I just want to execute my arduino program with version 2.0.3. If it is settled, I am willing to pay a certain fee. Thank you very much.
![image](https://github.com/platformio/platform-espressif32/assets/136065546/ddf0f870-dcdc-4827-9e0c-80094254e5f7)
![image](https://github.com/platformio/platform-espressif32/assets/136065546/5d4950d8-dd7f-4886-946d-8b0500ff1a54)

**Comment by LuBaker34** [comment]
![image](https://github.com/platformio/platform-espressif32/assets/136065546/67c3ae88-47fb-4447-8a1e-025696982199)
This is the content of the esp32-s3-devkitc-1-myboard file.

**Comment by valeros** [comment]
Hi @LuBaker34, support for the Arduino core v2.0.3 was added in [v4.0.3](https://github.com/platformio/platform-espressif32/releases/tag/v4.3.0) of this platform, so your `platformio.ini` should look something like this (without additional `platform_packages`):
```ini
[env:esp32-s3-devkitc-1-myboard]
platform = espressif32 @ ~4.3.0
framework = arduino
board = esp32-s3-devkitc-1-myboard
...
```

**Comment by Jason2866** [comment]
Why you want to use core 2.0.3? There are several bugs solved in later/latest core.

**Comment by LuBaker34** [comment]
> 

If I write like you said, I will use version 2.0.11, but I will use version 2.0.3, because my screen only works normally under version 2.0.3, and other versions will display anomalies. I am also surprised at this phenomenon.

**Comment by LuBaker34** [comment]
> Why you want to use core 2.0.3? There are several bugs solved in later/latest core.

Because my screen only works normally in version 2.0.3, other versions will display anomalies, which is also very strange to me.
