### ISSUE TITLE
Add commit hashes of the different source components

### ISSUE THREAD

**Issue by bmeisels** [platformio/platform-espressif32#120]
Could you please add the commit hash for the different source components in the package (Especially for the Arduino framework).

I have spi code that works until platform version 1.0.2 and breaks on later versions. When looking at the version of the Arduino framework i see a version jump from 1.5.3 to 1.6.0 but I can't find a commit hash these versions correspond to.

If I am wrong this exists already please point me to it.

**Comment by ivankravets** [comment]
See release notes https://github.com/platformio/platform-espressif32/releases

Also, https://github.com/espressif/arduino-esp32/releases
