### ISSUE TITLE
Increase flash size to 4 MB on esp32 idf framework

### ISSUE THREAD

**Issue by mohamedSadfi** [platformio/platform-espressif32#1204]
I am doing a esp32 project on platform.io and my esp32 has 4MB of flash size but the default flash size seems to be 1 MB. How can I change that ? I tried the partition table and it didnt work since I am not using the arduino development framework. 
![image_2023-10-03_150212140](https://github.com/platformio/platform-espressif32/assets/92552027/f51970b6-8813-4953-bc6a-6cd64e9b624f)

**Comment by valeros** [comment]
This size is dynamically calculated according to the `app` partition in your partition table. More info here https://docs.platformio.org/en/latest/platforms/espressif32.html#partition-tables
