### ISSUE TITLE
Component Versions

### ISSUE THREAD

**Issue by avidNewb** [platformio/platform-espressif32#1223]
Version 6.4.0 with arduino as a component

Why do I get the latest examples in the esp-idf folders (assuming 5.1.1) but not the latest components to be used with them?  

Example:
Wifi provisioning examples can't be used with the included components because protocomm doesn't have events added (old version).

Is there any plan to update this or am I doing something wrong?

**Comment by valeros** [comment]
> Why do I get the latest examples in the esp-idf folders (assuming 5.1.1) but not the latest components to be used with them?

That's expected, the currently available Arduino package is based on IDF v4.4.5, you cannot use it as a component with IDF v5 until Arduino core v3.0 is released.
