### ISSUE TITLE
Unknown Board ID ESP32_C3_DevkitC_02

### ISSUE THREAD

**Issue by andychess** [platformio/platform-espressif32#1227]
Hi,
Not sure if I'm missing something obvious, but I'm getting an error using the Espressif ESP32C# DevkitC 02.

I copy pasted the board info from the supported boards list.  All other boards work fine.

Any help greatly appreciated.

pio --version
PlatformIO Core, version 6.1.12a1

 prun
Processing esp32-c3-devkitc-02 (platform: espressif32; board: esp32-c3-devkitc-02)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
UnknownBoard: Unknown board ID 'esp32-c3-devkitc-02'

[env:Heltec_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = espidf
monitor_speed = 115200
board_build.partitions = /Users/andy/Documents/PlatformIO/Projects/Talisman-ESP-IDF/partition_talisman.csv
board_build.filesystem = fatfs
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++23
  -D Heltec_V3

[env:Seeed]
platform = espressif32
board = seeed_xiao_esp32c3
framework = espidf
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
monitor_speed = 115200
board_build.partitions = /Users/andy/Documents/PlatformIO/Projects/Talisman-ESP-IDF/partition_talisman.csv
board_build.filesystem = fatfs
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++23
  -D Seeed

[env:ESP32_C3_DevKitC_02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = espidf
board_build.f_cpu = 160000000L
monitor_speed = 115200
board_build.partitions = /Users/andy/Documents/PlatformIO/Projects/Talisman-ESP-IDF/partition_talisman.csv
board_build.filesystem = fatfs
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++23
  -D C3_DeviKit_02

**Comment by valeros** [comment]
Hi @andychess, you're probably using an outdated dev-platform, just run the `pio pkg update -g -p espressif32` command in the IDE terminal.
