### ISSUE TITLE
How do I check the arduino version of my program?

### ISSUE THREAD

**Issue by hzhh110** [platformio/platform-espressif32#1229]
How do I check the arduino version of my program? Or is there any way to print it out? For example, ESP.getSdkVersion()

**Comment by hzhh110** [comment]
I can only know the idf version, but I can't get the arduino version. Is there any way to get it?

**Comment by valeros** [comment]
This repository is not the right place for such generic questions. But you can take a look at several macros defined in the `esp_arduino_version.h` header file, for example https://github.com/espressif/arduino-esp32/blob/2.0.14/cores/esp32/esp_arduino_version.h
