### ISSUE TITLE
ESP32-C6, espidf, error when using components folder, led_strip,h

### ISSUE THREAD

**Issue by andychess** [platformio/platform-espressif32#1243]
I have recently started porting a project to the ESP32-C6. Today I got the followng error which I traced back to an instance of a class that implements the RGB-LED component from espressif.

**_A fatal error occurred: Contents of segment at SHA256 digest offset 0xb0 are not all zero. Refusing to overwrite._**

https://stackoverflow.com/questions/77165764/esp-idf-platformio-build-contents-of-segment-at-sha256-digest-offset-0xb0-are-n

**Comment by Jason2866** [comment]
esptool tries to patch the magic header which is rejected because there is a checksum over the whole file which would be invalid by doing this.
This happens normally when the provided flash size in settings does not match the real size of the device (the real size is detected from esptool)

**Comment by andychess** [comment]
I wondered if the flash might have something to do with it, but in that case, why does it happen just on this particular build and not on every one?

**Comment by andychess** [comment]
Here is the verbose output:
 
<img width="1660" alt="Bildschirmfoto 2023-12-01 um 14 23 49" src="https://github.com/platformio/platform-espressif32/assets/87867152/f3dab454-7cb9-4e4f-b2c3-adc150c5b5b8">

<img width="1675" alt="Bildschirmfoto 2023-12-01 um 14 48 48" src="https://github.com/platformio/platform-espressif32/assets/87867152/c9284695-3a61-469b-8505-a1979fe4aa1b">

**Comment by andychess** [comment]
Thanks for your help Jason:-).  I forgot to mention that the physical board is the Waveshare  ESP32-C6-DEV-KIT-N8.  I tried with both devkits in platformio (esp32-c6-devkitm-1 and esp32-c6-devkitc-1) and got the same behaviour with both.

**Comment by Jason2866** [comment]
Mhh, strange. Can you try this setup:
```
platform = https://github.com/tasmota/platform-espressif32/releases/download/2023.11.11/platform-espressif32.zip
platform_packages = framework-espidf @ https://github.com/tasmota/esp-idf/releases/download/v5.1.2-org/esp-idf-v5.1.2-org.zip
```

**Comment by andychess** [comment]
Interesting.  At first the suggestions above didn't work, but then I reset platform.ini to the original settngs and suddenly it now works.

Whilst looking through the sdkconfig, I did notice this:

<img width="944" alt="Bildschirmfoto 2023-12-01 um 17 51 41" src="https://github.com/platformio/platform-espressif32/assets/87867152/f33b1e6c-ce70-4c09-9774-a66991def81c">

Is the CONFIG_ESPTOOLPY_FLASHSIZE_2MB=y correct?

This is the latest output:

<img width="892" alt="Bildschirmfoto 2023-12-01 um 17 57 15" src="https://github.com/platformio/platform-espressif32/assets/87867152/6cb2b304-17d7-4039-b57a-5b0dadb5ed68">

**Comment by andychess** [comment]
The only problem now is that the upload isn't working.

<img width="1650" alt="Bildschirmfoto 2023-12-01 um 18 10 59" src="https://github.com/platformio/platform-espressif32/assets/87867152/949e16e0-b2b4-4ae4-ba13-7adf02c007eb">

**Comment by Jason2866** [comment]
No esptool flashsize should be 8MB for your device. Probably the reason why it failed at first.
Why it now does not flash? Idk. Can you post you Platformio.ini?
You have configured the C6 before with `platformio run -t menuconfig`?

**Comment by Jason2866** [comment]
You can try my example LittleFS project. https://github.com/Jason2866/Arduino_IDF_LittleFS/tree/test_51
Verified working. Just use as the C6 board the `esp32-c6-devkitc-1`

**Comment by andychess** [comment]
I checked menuconfig and the 8MB was set there.  I made no changes.  Now I get some new error messages:

<img width="1674" alt="Bildschirmfoto 2023-12-02 um 12 25 43" src="https://github.com/platformio/platform-espressif32/assets/87867152/c2ef7b56-69c7-4f61-a24b-8d5bdcc38c68">

Platformio.ini looks like this at the moment:

<img width="972" alt="Bildschirmfoto 2023-12-02 um 12 28 34" src="https://github.com/platformio/platform-espressif32/assets/87867152/b6b3cda2-172c-42fe-b0bb-c1b9d49c0d6b">

I realised that I don't know anywhere near enough about esptool.py.  I've been happy so far that it just worked.  I found this video from Devcon22 which I would recommend to anyone who hasn't seen it aleady.

https://www.youtube.com/watch?v=GjWGKzu3XTk

**Comment by Jason2866** [comment]
Your code is probably to blame. Your c6 env is a bit weird too. No need to specify the MCU type. It is defined in the boards.json.  Why fiddling around with c++ version? When running in issues such stuff should be removed. If you have a working setup you can try.

**Comment by andychess** [comment]
Quite a few issues there.  

I did use your suggested setup (see above) and this partially worked but wouldn't upload.  Then I spotted the problem in the sdkconfig which I think has solved the problem.  I just ran menuconfig and saved without making any changes, having checked the flash size was indeed 8MB.

The reference to the MCU comes straight out of the platformio board documentation and I only added the specific references when this problem appeared.

The C++ version is simply there because I write in C++ ;-).  The project has been running for over a year and only recently did I start to port to the C6 having been working on the Heltec V3 LoRa board until now.

Anyway.  I just cleaned everything, ran menuconfig and can now upload to the board, so the problem seemed to be the incorrect entry in the sdkconfig.

I really appreciate your help in getting to the bottom of this and for the additional information provided.

**Comment by Jason2866** [comment]
There are errors in Pio docu too. The entry of MCU is redundant and not needed.

**Comment by valeros** [comment]
Closing as solved.

**Comment by ss89** [comment]
@valeros how was it solved? i'm stumbling across the same issue using esphome, so not really writing any code. refs: https://github.com/esphome/issues/issues/5938
