### ISSUE TITLE
ESP-IDF out of date: v3.1 released

### ISSUE THREAD

**Issue by MisterRager** [platformio/platform-espressif32#125]
ESP-IDF v3.1 [is out](https://github.com/espressif/esp-idf/releases)!

Is there a way I can submit pull requests for the [manifest](http://dl.platformio.org/packages/manifest.json) where framework packages are listed? I'd be happy to help speed things along.

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-espressif32/commit/bcfc6a4913463c5ab434e742b7d3208e393ede51
