### ISSUE TITLE
Add M5Stack ATOM Lite Board

### ISSUE THREAD

**Issue by barndawgie** [platformio/platform-espressif32#1258]
I've been using the [M5Stack ATOM Lite](https://docs.m5stack.com/en/core/atom_lite). Currently, I'm using the `m5stack-atom` board setting in my configs, but at least from the specs it looks like the ATOM Lite has 520KB of RAM while the `m5stack-atom` config specifies only 320KB.

**Comment by valeros** [comment]
520KB is the overall RAM size on ESP32, 320KB is available for the end user, so you're safe with the `m5stack-atom` configuration.
