### ISSUE TITLE
Erase Flash Sketch + Wifi Settings

### ISSUE THREAD

**Issue by j0hncc** [platformio/platform-espressif32#127]
In arduino IDE there is option for 

![image](https://user-images.githubusercontent.com/11875156/45855951-20165780-bd18-11e8-9ffb-4f7c739a8dfd.png)

What is the corresponding way to do those in platformio?  I am using VSCode IDE

Thanks!

**Comment by vshymanskyy** [comment]
@ivankravets same comment. It could be implemented by having different upload targets

**Comment by vshymanskyy** [comment]
@ivankravets this is also needed for ESP8266

**Comment by atatistcheff** [comment]
Also having this issue.  I have to go back to the Arduino IDE to clear these settings on the Wemos D1 (ESP-8266).

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/platforms/espressif32.html#erase-flash

**Comment by ivankravets** [comment]
Please note that you will need to use [upstream version](https://docs.platformio.org/en/latest/platforms/espressif32.html#upstream) of dev/platformio while it has not been released yet.

**Comment by richard-scott** [comment]
I've just tried this with Platformio-3.6.6 in VS Code and now I get this when trying to upload:
```
AVAILABLE: espota, esptool
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: COM5
Uploading C:\Users\rscott\AppData\Local\Temp\pio-build\c70d26bfa2\build\nodemcuv2\firmware.bin
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
*** [upload] Error 2
```

Does anyone have a link to the fix as my Google Foo isn't working for me right now ;-(

**Comment by NavadeepGaneshU** [comment]
PS C:\Users\HP1> esptool.py erase_flash
esptool.py v2.8
Found 1 serial ports
Serial port COM4
Connecting........_____....._____....._____....._____....._____....._____....._____
COM4 failed to connect: Failed to connect to Espressif device: Invalid head of packet (0x48)

A fatal error occurred: Could not connect to an Espressif device on any of the 1 available serial ports.
PS C:\Users\HP1>


Unable to erase the flash at all. ESP-32 CAM board
Can anyone help me here?

**Comment by richard-scott** [comment]
Do you have GPIO0 connected to GND before connecting 5V?
This puts the board into Flashing mode.


![](http://acoptex.com/uploads/ESP32CAMtroubleshooting_pro4.jpg)

**Comment by NavadeepGaneshU** [comment]
Oh, Yes. I realise i made a mistake there ! . But, even after correcting, it shows the below error, Giving default partition shows sketch too large and my partition scheme is huge app (3MB no OTA). 
----------------------------------------------------------------------------------------
Warning: Could not auto-detect Flash size (FlashID=0x0, SizeID=0x0), defaulting to 4MB
Compressed 8192 bytes to 47...

Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 3449.3 kbit/s)...

A fatal error occurred: Timed out waiting for packet header
A fatal error occurred: Timed out waiting for packet header

**Comment by richard-scott** [comment]
Maybe this to your "[env]" in platformio.ini

```
board_build.partitions = min_spiffs.csv
```

Look in here for other partiton csv files (assuming your on Windows):
C:\Users\\%USERNAME%\\.platformio\packages\framework-arduinoespressif32\tools\partitions

Can you post your platformio.ini so we can see what you are using to build with?

**Comment by NavadeepGaneshU** [comment]
platformio config file : 
-----------------------------------------------------------------------------
[platformio]
src_dir = .
lib_dir = ../..

[env:nano32]
platform = espressif32@1.9.0
board = nano32
framework = arduino
board_build.partitions = partition-table.csv
build_flags =
    -DNO_GLOBAL_EEPROM
    -DDEBUG_EEPROM32_ROTATE_PORT=Serial

**Comment by NavadeepGaneshU** [comment]
platformio config  file :+1: 
-------------------------------------------------------------------------------------------
`[platformio]
src_dir = .
lib_dir = ../..

[env:nano32]
platform = espressif32@1.9.0
board = nano32
framework = arduino
board_build.partitions = partition-table.csv
build_flags =
    -DNO_GLOBAL_EEPROM
    -DDEBUG_EEPROM32_ROTATE_PORT=Serial
`

**Comment by richard-scott** [comment]
Why do you set your own partitions?
It should work fine without that?

**Comment by NavadeepGaneshU** [comment]
Sorry, I didn't understand that . 
So, how can I fix this now ?

**Comment by richard-scott** [comment]
comment out this line in your platformio.ini:

```
board_build.partitions = partition-table.csv
```

**Comment by NavadeepGaneshU** [comment]
Tried it and I see the same error again. 

There were 3 files with name "platformio.ini" in 
D: >> Arduino >> Libraries >> EEPROM32_Rotate>> Examples>> basic , dump and info locations. 

Commented that line in all 3 files.

Can I get some of your other contact details so that I can reach to you soon to fix this issue? 
E-Mail me at navadeepganesh.ngu@gmail.com 
Please help me In fixing this issue.

**Comment by richard-scott** [comment]
That folder structuer is wrong for PlatformIO.
If I were you, I'd create a new project in PlatformIO and base that on the 'MakerAsia Nano32' board.

Don't add any new code to that, but try and build and upload what the IDE gives you as a template.
Only once that works, start adding more custom code.

I'm sorry, but I can't provide help outside of this issue.

**Comment by NavadeepGaneshU** [comment]
Ok, thank you. 
So ,if I try the same (to upload code) on another PC (Other Arduino IDE), it should work fine right ? 
There isn't any issue on ESP32 CAM side right ?

**Comment by nilipta** [comment]
![https://user-images.githubusercontent.com/11875156/45855951-20165780-bd18-11e8-9ffb-4f7c739a8dfd.png]

Can you please teach me why there are 3 options are there to erase flash ?
What are the benefits to use them ?
