### ISSUE TITLE
Board config for ESP32-C3-Zero

### ISSUE THREAD

**Issue by jonnytest1** [platformio/platform-espressif32#1276]
- [x ] **Feature Request**.
     missing board https://www.waveshare.com/esp32-c3-zero.htm

     freq:160MHz
     4MB of onboard Flash
     400KB of SRAM and 384KB ROM (not sure what this eans exactly with the 4MB rom flash ^^)

**Comment by valeros** [comment]
It seems you can get around with a similar board, for example `esp32-c3-devkitc-02`.

**Comment by jonnytest1** [comment]
thats what i did so far yes , but it seems to have "unique" sizes for ram which could potentially mean some firmwares could be blocked when they shouldnt (or the other way round)

**Comment by jonnytest1** [comment]
![image](https://github.com/platformio/platform-espressif32/assets/13507796/cbd36bc9-a7e9-4c58-a7fb-765adac8ee26)

did i miss something ?

**Comment by Jason2866** [comment]
> thats what i did so far yes , but it seems to have "unique" sizes for ram which could potentially mean some firmwares could be blocked when they shouldnt (or the other way round)

RAM is same for all C3 MCUs. If you find different settings it mentions overall RAM against useable one.

**Comment by valeros** [comment]
@jonnytest1 

> did i miss something ?

You're probably using an old platform version, just run `pio pkg update -g -p espressif32` in the IDE terminal to install the latest version v6.5.0.
