### ISSUE TITLE
esp-wrover-kit RAM size reverted?

### ISSUE THREAD

**Issue by davidjade** [platformio/platform-espressif32#129]
It seems that back in May 2018, the PSRAM size was update for the ESP-WROVER-KIT board to take advantage of the 4Mb of PSRAM (540925efccf77df42e3f70beaea73b61c5c25f28). Now it looks like it was reverted in June 2018 in this commit: e61786cac1e7c28c6341120bb602ec99380cbc28 

Is there a reason for this? When using this board with PIO, it seems you can not access the 4mb of PSRAM now.

Also, at startup the monitor does not show the PSRAM as being detected so I am not even sure that PIO is enabling it for the WROVER board like it should.

**Comment by davidjade** [comment]
I wanted to add, that in order to get the extra 4Mb of PSRAM in a WROVER board to work when using the ESP IDF framework, you additionally have to define all of this. This is a collection of required and sensible options when using PSRAM.

CONFIG_SPIRAM_SUPPORT 1
CONFIG_SPIRAM_TYPE_ESPPSRAM32 1
CONFIG_SPIRAM_SIZE 4194304
CONFIG_SPIRAM_SPEED_40M 1
CONFIG_SPIRAM_CACHE_WORKAROUND 1
CONFIG_SPIRAM_BOOT_INIT 1
CONFIG_SPIRAM_MEMTEST 1
CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL 16384
CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL 32768
CONFIG_SPIRAM_USE_MALLOC 1
CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY 1
CONFIG_SUPPORT_STATIC_ALLOCATION 1

In addition, this is a safe one to also add and would keep the kernel from faulting if the PSRAM was missing or unusable:
CONFIG_SPIRAM_IGNORE_NOTFOUND 1

If you add these as extra flags (and fix the board RAM size), then the extra PSRAM in a WROVER then becomes usable via malloc.

**Comment by TD-er** [comment]
I get this error when linking:

```
*** [.pioenvs\m5stack-core-esp32\firmware.elf] Implicit dependency `C:\users\gijs\.platformio\platforms\espressif32\builder\1' not found, needed by target `.pioenvs\m5stack-core-esp32\firmware.elf'.
```

Any idea what I am missing in my PlatformIO config?
I already removed this define `CONFIG_SPIRAM_SIZE 4194304` since it was already difined elsewhere.

**Comment by ivankravets** [comment]
The value has been updated according to https://github.com/espressif/arduino-esp32/blob/master/boards.txt#L113

Also, macro `BOARD_HAS_PSRAM` was added.

P.S: We use `upload.maximum_ram_size` only for the information aims.

**Comment by ivankravets** [comment]
Please reopen if you still need help
