### ISSUE TITLE
Error: Detected a whitespace character in project paths

### ISSUE THREAD

**Issue by Gisbert12843** [platformio/platform-espressif32#1290]
Bug is not resolved. Can not create/compile !!!ANY!!! projects.

Project Name "Test"
Location set as C:/test, Folder opened via VS Code being "C:/Test
Board being ESP32 C3 Dev KitC 02 (doesnt matter which one tried various)
Framework ESPIDF
Version 3.3.3 updated on 27.01.2024

Also tried fully deleting VS Code including deletion of %APPDATA%\Code and %USERPROFILE%\.vscode . Nothing helped.

Error 1:

PIO Core Call Error: "The following files/directories have been created in C:\\test\\test\\test\r\ninclude - Put project header files here\r\nlib - Put project specific (private) libraries here\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nResolving esp32-c3-devkitc-02 dependencies...\r\nAlready up-to-date.\r\nUpdating metadata for the vscode IDE...\r\n\n\nUserSideException: Processing esp32-c3-devkitc-02 (platform: espressif32; board: esp32-c3-devkitc-02; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-c3-devkitc-02.html\r\nPLATFORM: Espressif 32 (6.5.0) > Espressif ESP32-C3-DevKitC-02\r\nHARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf @ 3.50102.240122 (5.1.2) \r\n - tool-cmake @ 3.16.4 \r\n - tool-esptoolpy @ 1.40501.0 (4.5.1) \r\n - tool-idf @ 1.0.1 \r\n - tool-mconf @ 1.4060000.20190628 (406.0.0) \r\n - tool-ninja @ 1.9.0 \r\n - tool-riscv32-esp-elf-gdb @ 11.2.0+20220823 \r\n - tool-xtensa-esp-elf-gdb @ 11.2.0+20230208 \r\n - toolchain-esp32ulp @ 1.23500.220830 (2.35.0) \r\n - toolchain-riscv32-esp @ 12.2.0+20230208\r\nError: Detected a whitespace character in project paths.\r\n========================== [FAILED] Took 0.87 seconds =========================="

-
-

Another example same folder but happens on whatever folder.

-
-

Resolving featheresp32-s2 dependencies...
Already up-to-date.
Updating metadata for the vscode IDE...
UserSideException: Processing featheresp32-s2 (platform: espressif32; board: featheresp32-s2; framework: espidf)

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/featheresp32-s2.html
PLATFORM: Espressif 32 (6.5.0) > Adafruit ESP32-S2 Feather Development Board
HARDWARE: ESP32S2 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-espidf @ 3.50102.240122 (5.1.2) 
 - tool-cmake @ 3.16.4 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - tool-idf @ 1.0.1 
 - tool-mconf @ 1.4060000.20190628 (406.0.0) 
 - tool-ninja @ 1.9.0 
 - tool-riscv32-esp-elf-gdb @ 11.2.0+20220823 
 - tool-xtensa-esp-elf-gdb @ 11.2.0+20230208 
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0) 
 - toolchain-riscv32-esp @ 12.2.0+20230208 
 - toolchain-xtensa-esp32s2 @ 12.2.0+20230208
Error: Detected a whitespace character in project paths.
========================== [FAILED] Took 0.86 seconds ==========================

-
-

another one from a cloned working project, uncompileable same bug.

-
-

Library Manager: lvgl@8.3.10+sha.06b7101 has been installed!
Updating metadata for the vscode IDE...
UserSideException: Processing esp32 (platform: espressif32; board: az-delivery-devkit-v4; framework: espidf)

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/az-delivery-devkit-v4.html
PLATFORM: Espressif 32 (6.5.0) > AZ-Delivery ESP-32 Dev Kit C V4
HARDWARE: ESP32 240MHz, 520KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-espidf @ 3.50102.240122 (5.1.2) 
 - tool-cmake @ 3.16.4 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - tool-idf @ 1.0.1 
 - tool-mconf @ 1.4060000.20190628 (406.0.0) 
 - tool-ninja @ 1.9.0 
 - tool-riscv32-esp-elf-gdb @ 11.2.0+20220823 
 - tool-xtensa-esp-elf-gdb @ 11.2.0+20230208 
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0) 
 - toolchain-xtensa-esp32 @ 12.2.0+20230208
Error: Detected a whitespace character in project paths.
========================== [FAILED] Took 0.96 seconds ==========================

**Comment by valeros** [comment]
Known issue, see a workaround in the documentation https://docs.platformio.org/en/latest/frameworks/espidf.html#limitations
