### ISSUE TITLE
The Espressif ESP32-C3 should have 512KB ram not 320KB ram

### ISSUE THREAD

**Issue by 19e2k67** [platformio/platform-espressif32#1292]
![image](https://github.com/platformio/platform-espressif32/assets/102461738/9237b5b3-b842-4c94-a97b-2c31ac153e8e)
![Snipaste_2024-01-28_19-34-10](https://github.com/platformio/platform-espressif32/assets/102461738/681f30aa-5a8f-43c9-9cc5-6913f9516cee)
Enquiry through this webpage：
https://products.espressif.com/#/product-selector?language=en&names=

**Comment by Jason2866** [comment]
Yes it has 512k but useable are only 320k
