### ISSUE TITLE
Added missing identifiers in esp_vfs_littlefs_conf_t #9046  fix not in 6.5.0

### ISSUE THREAD

**Issue by xgnata** [platformio/platform-espressif32#1293]
New warning  in 6.5.0 because this patch did not find its way in the 6.5.0 release : 
https://github.com/espressif/arduino-esp32/pull/9046/commits/a290acfea6704b474cfeee7c09c43914fc762bc6

**Comment by Jason2866** [comment]
Platform 6.5.0 uses release core 2.0.14. This commit is done after release of core 2.0.14.

**Comment by valeros** [comment]
Closing as the issue originates from the Arduino framework.
