### ISSUE TITLE
Fixes set pins return value in 2.0.13 #8644 not part of 6.5.0

### ISSUE THREAD

**Issue by xgnata** [platformio/platform-espressif32#1294]
New warning in 6.5.0 because this patch is missing:
https://github.com/espressif/arduino-esp32/pull/8644/commits/81b82f1dcfbd0161fa59e140d7ac63d08dbea615

**Comment by Jason2866** [comment]
Platform 6.5.0 uses release core 2.0.14. This commit is done after release of core 2.0.14.

**Comment by xgnata** [comment]
Yes indeed. So, t's not a platform issue as platform relies on upstream version of arduino core.
Let's wait for core >2.0.14 and a next release of Platform (and apply the patch in my machine on the meantime).

**Comment by valeros** [comment]
Closing as the issue originates from the Arduino framework.
