### ISSUE TITLE
Support software breakpoints in ESP32 

### ISSUE THREAD

**Issue by NikhilMJ** [platformio/platform-espressif32#130]
Starting with ESP-IDF v3.1, software breakpoints are being supported by the esp-idf. 
Seems that the arduino core has also migrated to this latest version.

Seems like currently are able to set only 2 breakpoints. These are hardware breakpoints. Get the following warning when trying to set the third break point. 
> Warn : xtensa_add_breakpoint: max slot reached, slot=2
![image](https://user-images.githubusercontent.com/18152543/46838620-fd072280-cd6e-11e8-9d22-d41f2b398048.png)

Was support for software breakpoints added to pio for vsc? If not, could this be added.

**Comment by ivankravets** [comment]
What is your OS? Could you try the latest version of openOCD from https://github.com/espressif/openocd-esp32/releases

Please replace files in `~/.platformio/packages/tool-openocd-esp32` and keep `package.json` without changes.

Does it work?

**Comment by NikhilMJ** [comment]
It didn't. I now get this error. 
** OpenOCD init failed **
shutdown command invoked

As an fyi, I am using the wrover kit with the below ini config: 
```[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
upload_port=COM5
debug_port=COM4```

**Comment by ivankravets** [comment]
Please remove this `debug_port=COM4````

**Comment by NikhilMJ** [comment]
Apologies for the delayed response. I was messing around with the settings when I sent that ini config. Never got back to getting this working.

**Comment by ivankravets** [comment]
Please open PIO IDE and upgrade PIO Core to 3.6.1. Also, please update all packages using "VSCode > Left sidebar > PlatformIO(icon) > Update packages..."

Do software breakpoints work now?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by NikhilMJ** [comment]
Not yet Ivan. Got this running again. Am able to set a breakpoint and then step from there, but still can't set additional software breakpoints. I updated the core and the various packages. I'm on pio version 3.6.2a2.

Some screenshots of error: 
![image](https://user-images.githubusercontent.com/18152543/48667336-4cd0bc00-ea88-11e8-8aa3-05bd713e5625.png)

**Comment by ivankravets** [comment]
I've just tested software breakpoints and they work for me. Please try the next:

1. Launch debug session
2. Do "Step Over" to `initArduino();`
3. Set breakpoint on `void loopTask(void *pvParameters)`, we need to stop when `loopTask` will be inited
4. Now, you can set as many breakpoints as you need in arduino code. They should work.

![screen shot 2018-11-24 at 15 58 36](https://user-images.githubusercontent.com/1760209/48969068-d68d0600-f001-11e8-8b23-d527b16d0d64.png)

**Comment by ivankravets** [comment]
Please reopen if you still need help
