### ISSUE TITLE
How overide lib precompiled file spi_master

### ISSUE THREAD

**Issue by mmar22** [platformio/platform-espressif32#1300]
PIO is excelent , but i require customize precompiled functions.
How is best simple way todo this ?
Perfectly for spi_master.c file in framework-arduinoespressif32 , but ...

**Comment by valeros** [comment]
Hi @mmar22, If you mean the `spi_master.c` file from the ESP-IDF framework (which serves as the base for Arduino) then the only way is to compile your application as a mixed Arduino/IDF project, take a look at an example [here](https://github.com/platformio/platform-espressif32/tree/develop/examples/espidf-arduino-wifiscan).
