### ISSUE TITLE
Add support for "ESP32-C3 SuperMini" board

### ISSUE THREAD

**Issue by barsikus007** [platformio/platform-espressif32#1306]
### Information

- <https://microsoft.github.io/devicescript/devices/esp32/esp32c3-supermini>
- <https://aliexpress.com/item/1005006371542813.html?sku_id=12000036934095950>

**Comment by valeros** [comment]
Hi @barsikus007, there is no official variant for this board, so a proper variant header should be added to this repo https://github.com/espressif/arduino-esp32 in the first place.

**Comment by sparky8512** [comment]
Looks like it already exists as variants `makergo_c3_supermini` and `nologo_esp32c3_super_mini`. Not sure if Maker go was the original designer and the "nologo" one is for clones/resellers, or what. They look essentially the same to me.

**Comment by barsikus007** [comment]
> Looks like it already exists as variants `makergo_c3_supermini` and `nologo_esp32c3_super_mini`. ~Not sure if Maker go was the original designer and the "nologo" one is for clones/resellers, or what~ (apparently, Nologo is an actual manufacturer). They look essentially the same to me.

thanks, but I haven't these boards in platformio
how to add them?

**Comment by valeros** [comment]
The boards will be added once a new stable version of the framework is released.

**Comment by barsikus007** [comment]
thanks, I'll just wait for release and will use `nologo_esp32c3_super_mini` one

**Comment by faizannazir** [comment]
> Author

I have a esp32 c3 super mini board but i am not able to flash it

**Comment by vbguyny** [comment]
Does anyone know when there will be an update available with support for the super mini?

**Comment by valeros** [comment]
@vbguyny It will be added once a new stable release of Arduino core is published.

**Comment by sparky8512** [comment]
I wouldn't count on that happening any time soon, though. Neither of the above-mentioned board variants is present in the v2.x release branch of arduino-esp32, and it looks like 3.0.0 is still in pre-release. I have no insight into the release schedule for that, but even once released, there seems to be [some uncertainty](https://github.com/platformio/platform-espressif32/issues/1225) around getting that version supported by platformio.

In the meantime, you can pretty much use any of the existing ESP32-C3 variants that don't have a separate USB serial chip on the board (I use `lolin_c3_mini`), as long as you don't use the board-specific Arduino pin macros like LED_BUILTIN, etc. And if you really need those, I think you can copy one of the `pins_arduino.h` files that got added in arduino-esp32 (from [here](https://github.com/espressif/arduino-esp32/blob/master/variants/nologo_esp32c3_super_mini/pins_arduino.h) or [here](https://github.com/espressif/arduino-esp32/blob/master/variants/makergo_c3_supermini/pins_arduino.h)) into your project somewhere in the `-I` header include path.

**Comment by pablomuri** [comment]
Hi any news on this? PlatformIO is already using the esp32 v3.x, isn't it?

**Comment by mhaberler** [comment]
> Hi any news on this? PlatformIO is already using the esp32 v3.x, isn't it?

no it isnt
#1225

**Comment by pcace** [comment]
Hi, is there any way now to use these in plattformIO?

thanks a lot!

**Comment by Michelingumman** [comment]
@pcace Im wondering this aswell!!

**Comment by louis-lau** [comment]
For anyone reading this, board support isn't actually required to use a supported chip with platformio.

Just use the generic esp32c3 board, make it use usb, and redefine the led at the top of your sketch (if you want).

```ini
[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
framework = arduino
```

```cpp
#undef LED_BUILTIN
#define LED_BUILTIN 8
```
