### ISSUE TITLE
Add support for Heltec Wireless Tracker

### ISSUE THREAD

**Issue by motorics** [platformio/platform-espressif32#1307]
Dear Team,

Please add support for the Heltec Wireless Tracker board.

https://heltec.org/project/wireless-tracker/
Official GitHUB repo: https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series
The MCU is ESP32s3.

Thank you !

**Comment by valeros** [comment]
Duplicate https://github.com/platformio/platform-espressif32/issues/1148
