### ISSUE TITLE
espidf arduino blink example

### ISSUE THREAD

**Issue by timmornYE** [platformio/platform-espressif32#1310]
https://github.com/platformio/platform-espressif32/blob/b0a7f56bcde9fa332b40111b1423482d8f7cbc77/examples/espidf-arduino-blink/src/Blink.cpp#L65

Does this line make sense? `void blink_task(void *pvParameter)` has infinite loop, so Arduino `void loop()` will never be called.

**Comment by valeros** [comment]
Hi @timmornYE, `blink_task` is just an example how to start a new task, the `loop` function is still being executed in the `loopTask` task implemented directly in [the framework](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/main.cpp#L95).
