### ISSUE TITLE
Add Debugger support for WEMOS LOLIN32 Lite

### ISSUE THREAD

**Issue by DrGlaucous** [platformio/platform-espressif32#1312]
This board is confirmed to work with the esp-prog programming tool for debugging, but the `.json` file needs to be updated to reflect this.
This is a minor 3 line change, and I didn't think it was worth it to create a complete fork for said change *(which was just adding the debug field to the json file)*.

Additionally, the wiki should be updated to reflect this information as well, but that is in a separate repository. It would be easier if an administrator copied over the section from the lolin32 (non-lite) or any other "debug supported" esp32 board than if I created an entire fork and a second pull request.

[Link to lolin32 wiki entry](https://github.com/platformio/platformio-docs/blob/develop/boards/espressif32/lolin32.rst)
[Link to lolin32-lite wiki entry](https://github.com/platformio/platformio-docs/blob/develop/boards/espressif32/lolin32_lite.rst)

This is the altered file, [`/boards/lolin32_lite.json`](https://github.com/platformio/platform-espressif32/blob/master/boards/lolin32_lite.json).
```
{
  "build": {
    "arduino":{
      "ldscript": "esp32_out.ld"
    },
    "core": "esp32",
    "extra_flags": "-DARDUINO_LOLIN32_LITE",
    "f_cpu": "240000000L",
    "f_flash": "40000000L",
    "flash_mode": "dio",
    "mcu": "esp32",
    "variant": "lolin32-lite"
  },
  "connectivity": [
    "wifi",
    "bluetooth",
    "ethernet",
    "can"
  ],
  "debug": {
    "openocd_board": "esp-wroom-32.cfg"
  },
  "frameworks": [
    "arduino",
    "espidf"
  ],
  "name": "WEMOS LOLIN32 Lite",
  "upload": {
    "flash_size": "4MB",
    "maximum_ram_size": 327680,
    "maximum_size": 4194304,
    "require_upload_port": true,
    "speed": 460800
  },
  "url": "https://diyprojects.io/wemos-lolin32-lite-compact-revision-lolin32-4-90/",
  "vendor": "WEMOS"
}
```

**Comment by Jason2866** [comment]
Or you open a PR to provide the changes.
