### ISSUE TITLE
ADC not available on ESP32-S3

### ISSUE THREAD

**Issue by marcopyre** [platformio/platform-espressif32#1316]
I need ADC for analog microphone input but the package sets the ADC as unavailable, pins are defined but there is just the config missing to turn it on, the ESP32-S3 documentation says that the board supports it,

![image](https://github.com/platformio/platform-espressif32/assets/74605395/36191c4f-a7a1-440b-9bd9-013ee5530389)
![image](https://github.com/platformio/platform-espressif32/assets/74605395/9b9c03af-9de0-4985-b610-b46a7369f4ac)

**Comment by Jason2866** [comment]
Not related to Platformio. Issues regarding Arduino espressif32 has to be open there.
