### ISSUE TITLE
tone() not working

### ISSUE THREAD

**Issue by BigRocha234** [platformio/platform-espressif32#132]
works fine on Arduino IDE but the function tone() not exists on Platform IDE..

**Comment by ivankravets** [comment]
Could you provide a simple project to reproduce the issue?

**Comment by BigRocha234** [comment]
sorry for the waiting.. i lost my project, i tried to run a tone example, just copy and paste from arduino IDE, it will runs fine on arduino IDE but dont run on Platformio (sorry for my bad english)

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by FelixLuciano** [comment]
I have the same issue.

**Comment by thijstriemstra** [comment]
`tone` is working nowadays, this can be closed afaik.
