### ISSUE TITLE
using custom arduino core

### ISSUE THREAD

**Issue by umerm64** [platformio/platform-espressif32#1322]
I want to use a custom sdk (arduino core) for my project.
How do I specify the custom one?

I tried to update the `platform.json` file like this:
```
"framework": {
"arduino": {
      "package": "framework-arduinoespressif32",
      "script": "builder/frameworks/arduino.py",
      "url": "https://github.com/myprofile/arduino-esp32.git"
    },
```

but this doesnt download my custom sdk.

I need help in this regard please.

Thank you.

**Comment by Jason2866** [comment]
You can't provide a git repo here. You have to pack (example zip) and provide the link to the package

**Comment by valeros** [comment]
See https://docs.platformio.org/en/latest/projectconf/sections/env/options/platform/platform_packages.html
