### ISSUE TITLE
Help regarding Enabling Logs for Second Stage Bootloader 

### ISSUE THREAD

**Issue by meakashrao** [platformio/platform-espressif32#1324]
I tried a lot but I am not able to enable second stage bootloader logs for ESP32

**Comment by valeros** [comment]
Hi @meakashrao, what framework are you using?

**Comment by meakashrao** [comment]
PIO Core 6.1.13 and Home 3.4.4
Espressif 6.4.0

I am using Platfrom IO in VS Code

**Comment by meakashrao** [comment]
Arduino
