### ISSUE TITLE
Help regarding the correct Bootloader Version

### ISSUE THREAD

**Issue by meakashrao** [platformio/platform-espressif32#1335]
I am using PIO Core 6.1.13, Home 3.4.4, Espressif 6.4.0 and Arduino as framework. I need to know the bootloader file link and bootloader version.

**Comment by valeros** [comment]
Hi @meakashrao, I'm not sure what you mean by the bootloader version, but Espressif 6.4.0 uses Arduino core v2.0.11, which is based on ESP-IDF v4.4.5. As for the bootloader file, just run the upload command in verbose mode and you will see the full path to the bootloader binary.
