### ISSUE TITLE
adafruit_qtpy_esp32s3_nopsram board unknown

### ISSUE THREAD

**Issue by ChuckVanzant** [platformio/platform-espressif32#1364]
The board adafruit_qtpy_esp32s3_nopsram is listed as a supported board but when saving the platformio.ini file, the following error message appears:

**Resolving adafruit_qtpy_esp32s3_nopsram dependencies...
UnknownBoard: Unknown board ID 'adafruit_qtpy_esp32s3_nopsram'**

This is what I have specified in my platformio.ini:

**[env:adafruit_qtpy_esp32s3_nopsram]
platform = espressif32
board = adafruit_qtpy_esp32s3_nopsram
framework = arduino**

![QtPy2](https://github.com/platformio/platform-espressif32/assets/12755346/6a105fd3-a14e-4a85-ab93-6e5b988fb348)

![QtPy](https://github.com/platformio/platform-espressif32/assets/12755346/39a94b59-0034-4607-87f5-1ebe134fde9c)

![QtPy3](https://github.com/platformio/platform-espressif32/assets/12755346/59d16e62-285b-4d3c-9c0a-bab0bec827e7)

**Comment by valeros** [comment]
Hi @ChuckVanzant, what version of the `espressif32` development platform are you using? This board was added in v6.5.0, so please run `pio pkg update -g -p espressif32` directly in the IDE terminal.

**Comment by ChuckVanzant** [comment]
Updated and the board is now recognized. Thanks!

I was just confused as to why the board could have been listed through the Board Explorer and directed to

Adafruit QT Py ESP32-S3 No PSRAM — PlatformIO v6.1 documentation<https://docs.platformio.org/en/latest/boards/espressif32/adafruit_qtpy_esp32s3_nopsram.html?utm_source=platformio&utm_medium=piohome>

when the development platform in use was not correct.

Thanks again!

________________________________
