### ISSUE TITLE
When will Arduino latest and idf latest be available together?

### ISSUE THREAD

**Issue by hitecSmartHome** [platformio/platform-espressif32#1365]
Hi!

I'M using Arduino as a component of IDF.
Currently Arduino is on 2.0.14, IDF is on 4.4.6 if I specify both in the ini file.
`framework = arduino, espidf`
The latest from Arduino is v3.0.0 with IDF 5.1

**Comment by valeros** [comment]
3.0.0 is not yet stable. The progress is tracked here https://github.com/platformio/platform-espressif32/issues/1225

**Comment by hitecSmartHome** [comment]
Oh god. This is really sad news. Thank you for the answer.
