### ISSUE TITLE
ESP32-C3 Brownout event Halt with no recovery.

### ISSUE THREAD

**Issue by brunofgc** [platformio/platform-espressif32#1371]
Hi there!
I'm using the ESP32-C3 with the Arduino Framework.

The system uses a battery as backup for AC Power Source, and it works okay. However, when the battery drains too much, the system stops working. Additionally, when the AC Power is restored, it recharges the battery, but the system doesn't resume working. I need to completely turn off and turn on again in order to back working. "Hardware Reset".

Do you know of any system functions or calls that can detect when the system halts/fails for any reason? Perhaps I could detect a "brownout event" and take some actions accordingly?

Thank you in advance.

**Comment by valeros** [comment]
Hi @brunofgc, the issue tracker in this repository is not the right place to ask project-specific questions, please forward it to https://github.com/espressif/arduino-esp32
