### ISSUE TITLE
update to ardunio core 2.0.16

### ISSUE THREAD

**Issue by craiglink** [platformio/platform-espressif32#1372]
release v2.0.15 has a bug it it do to a mistaken merge from the v3 branch -  

This project should be updated to v.2.0.16 to avoid the defect in v2.0.15

more details here: https://github.com/espressif/arduino-esp32/releases/tag/2.0.16

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-espressif32/commit/eb6d7c539049b33d3b9d9d05f4d5fde3573dfdc7
