### ISSUE TITLE
not find Analog Continuous mode API in "esp32-hal-adc.h"

### ISSUE THREAD

**Issue by stardust-an** [platformio/platform-espressif32#1382]
When I move a project from Arduino IDE to PlatformIO, there is no Analog Continuous mode API in platform-espressif32-Arduino  v6.7.0  "esp32-hal-adc.h" ，how to slove it？Thank you very much！
![Screenshot 2024-05-22 103824](https://github.com/platformio/platform-espressif32/assets/101502687/6338b305-09fd-4024-8452-9e5b66c5cd86)

![{26B40E07-6B41-47E0-A637-9F0F21EB2CB7}](https://github.com/platformio/platform-espressif32/assets/101502687/f2e8f599-f185-49d2-9aba-94127163722f)

**Comment by valeros** [comment]
Hi @stardust-an, this feature is only available in the Arduino core v3.0 which is not yet released and not supported by PlatformIO.
