### ISSUE TITLE
FR: Update to bug fix Arduino core 2.0.17

### ISSUE THREAD

**Issue by Jason2866** [platformio/platform-espressif32#1385]
@valeros :-)

**Comment by Abasz** [comment]
Yes, this would be great as auto bootloader mode does not work with Arduino Core 2.0.16 on ESP32S3 so I need to use 6.6.0 of espriff32 platform.

**Comment by Jason2866** [comment]
Thx! Could you change too, to use IDF 3.40407.240606 for Arduino 2.0.17?

**Comment by valeros** [comment]
> @valeros Thx! Could you change too, to use IDF 3.40407.240606 for Arduino 2.0.17?

I believe it's default behaviour, just update your packages and new mixed Arduino/IDF projects should use the latest versions.

**Comment by Jason2866** [comment]
Tested, yes it uses latest build. Thx!
