### ISSUE TITLE
wrong ESP IDF version in release 6.7.0 notes?

### ISSUE THREAD

**Issue by caco3** [platformio/platform-espressif32#1388]
The release [v6.7.0](https://github.com/platformio/platform-espressif32/releases/tag/v6.7.0) refers to ESP-IDF `v5.1.2`.
How ever release [v6.6.0](https://github.com/platformio/platform-espressif32/releases/tag/v6.6.0) already refers to ESP-IDF `v5.2.1`.

I think it both should refer to ESP-IDF `v5.2.1`.

**Comment by Jason2866** [comment]
Yeah, it is a typo.

**Comment by valeros** [comment]
Thanks, fixed.
