### ISSUE TITLE
Windows and Anaconda cannot upload sketch to ESP32

### ISSUE THREAD

**Issue by I-himawari** [platformio/platform-espressif32#140]
When I uploaded sketch, I cannot uploaded sketch.
I guess. Anaconda with Windows cannot call esptool to "esptool.py" but "esptool" is done because ".py" is not linked.
I think, If user use windows, platformio could fix "esptool.py" from to "esptool".

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by I-himawari** [comment]
Very sorry, I was tried same environment agein but don't happen this error.
