### ISSUE TITLE
Cannot modify watch values in Debug

### ISSUE THREAD

**Issue by masm31** [platformio/platform-espressif32#1403]
How to modify a variable that shows on the watch list in online debug?
<img width="265" alt="image" src="https://github.com/platformio/platform-espressif32/assets/76566408/eddc4f83-29a2-4b8a-adcb-2fa7db60d74a">

**Comment by valeros** [comment]
Hi @masm31, unfortunately, you cannot modify the value of the watch expression from the GUI. Although it's possible via CLI of the debug window: 
<img src="https://github.com/platformio/platform-espressif32/assets/886732/f0d8e93c-e935-4edd-abc9-41061d600a14" width="70%" height="70%">
