### ISSUE TITLE
Will there be a release on Arduino v3.0.1 (ESP-IDF v5.1.4)

### ISSUE THREAD

**Issue by butaikis** [platformio/platform-espressif32#1404]
Hello. Is it even possible to plan a release based on Arduino version 3.0.1 based on ESP-IDF version 5.1.4?

**Comment by Jason2866** [comment]
See #1225

**Comment by cziter15** [comment]
Is that really that big problem to make community-based support in platformio?
I don't think it's  that hard to get it working.

**Comment by Jason2866** [comment]
@cziter15 No, it isn't. Did a core 3.0.1 based for for Tasmota. BUT the main work is to maintain.

**Comment by butaikis** [comment]
It turns out that you can not wait for the new version in PlatformIO?

**Comment by valeros** [comment]
Duplicate of https://github.com/platformio/platform-espressif32/issues/1225
