### ISSUE TITLE
Issues with OTA - cannot flash new firmware

### ISSUE THREAD

**Issue by wegunterjr** [platformio/platform-espressif32#143]
I have used the example OTA from the esp-idf github.  I was able to successfully download and install OTA, but I am unable to flash new OTA (using PlatformIO in VSCode).

I was able to flash using the esp-idf and program new firmware, but cannot do it in the IDE.

I am using this command to try and clear the flash to try again:
`platformio run --target erase`
It fails with:
`*** Do not know how to make File target `erase' `
Thoughts?

https://github.com/espressif/esp-idf/blob/b4b1b361da4a9dd0f7f9be0187c3cdaecb8da43a/examples/system/ota/native_ota_example/main/native_ota_example.c

##UPDATE###   TEMP SOLUTION
Problem: After flash OTA, platformio cannot flash new code to esp32.
Still can do OTA to OTA, no issues.
If needed, flash sample code to esp32 using esp-idf, then switch back to platformio.

**Comment by ivankravets** [comment]
> Do not know how to make File target erase

You need the latest upstream version https://docs.platformio.org/en/latest/platforms/espressif32.html#upstream

Does it work now?

**Comment by ivankravets** [comment]
Fixed in https://www.reddit.com/r/esp8266/comments/ah5f0g/weird_ota_issue_with_platformio/
