### ISSUE TITLE
Support last esp-idf v4.4 patch

### ISSUE THREAD

**Issue by QuadroKnoX** [platformio/platform-espressif32#1431]
Hey there,

is it possible to support the latest fix [v4.4.8](https://github.com/espressif/esp-idf/releases/tag/v4.4.8) of esp-idf, which was released in June, as it is fixing some bugs for the v4.4 version and seems to be the last patch for that version as it is now EOL? Unfortunately there is no released version for `platformio/framework-espidf@3.40408.0` yet but it would be great to have them without the need to directly upgrade to v5.

**Comment by valeros** [comment]
Hi @QuadroKnoX, v4.4.8 has been uploaded to the registry https://registry.platformio.org/tools/platformio/framework-espidf/versions
