### ISSUE TITLE
ESP32-POE-ISO-WROVER board definition

### ISSUE THREAD

**Issue by solexious** [platformio/platform-espressif32#1437]
Looking to have a board definition made for the ESP32-POE-ISO-WROVER. There is one for the ESP32-POE-ISO but the board i'm targeting uses a different esp32 with different ROM RAM and Ethernet pins etc.

Details can be found on this page (-WROVER isn't the default option on this page): https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO/open-source-hardware

**Comment by valeros** [comment]
Hi @solexious, a variant header file with proper pin definitions in the official [Arduino core](https://github.com/espressif/arduino-esp32) is required.

**Comment by solexious** [comment]
> Hi @solexious, a variant header file with proper pin definitions in the official [Arduino core](https://github.com/espressif/arduino-esp32) is required.

Ok thanks, will file an issue there.
