### ISSUE TITLE
LittleFs rmdir fails if the folder is not empty

### ISSUE THREAD

**Issue by hitecSmartHome** [platformio/platform-espressif32#1457]
Is this intentional?
If I call rmdir on a folder which has subfolders or files inside, it will fail.

Isn't rmdir supposed to be recursive?

**Comment by Jason2866** [comment]
Not a Platformio issue. Question should be asked in espressif Arduino github.

**Comment by hitecSmartHome** [comment]
Oh yeah, sorry. Wrong platform.

**Comment by hitecSmartHome** [comment]
> or on a linux forum.
> But anyways, rm -r is recursive. rmdir intentionally is not

Well. I have made a recursive version. Thanks for the answer
