### ISSUE TITLE
Add support for Waveshare ESP32-S3-Touch-LCD-1.69 board

### ISSUE THREAD

**Issue by billmaterial** [platformio/platform-espressif32#1468]
Please add support for the Waveshare ESP32-S3-Touch-LCD-1.69 board. I have tried all ESP32-S3 variants and none seem to work correctly.

https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-1.69

**Comment by valeros** [comment]
See https://github.com/platformio/platform-espressif32/issues/1468
