### ISSUE TITLE
GoogleTest does not work with `framework = espidf`

### ISSUE THREAD

**Issue by olicooper** [platformio/platform-espressif32#1475]
### Description of problem

I am unable to get the test suite to build when using googletest with espidf framework.

I have also tried building for esp32s3 and modifying build parameters etc. as can be seen in the `platformio.ini` below

This could be related to the recent googletest version bump as noted here: https://github.com/platformio/platform-espressif32/issues/1476

#### Steps to Reproduce

1. Use example code from here: https://github.com/platformio/platformio-examples/tree/develop/unit-testing/googletest
2. modify to use `framework = espidf`

### Actual Results

Build error as follows:

```log
Building & Uploading...
.pio/libdeps/esp32dev/googletest/googletest/src/gtest.cc: In member function 'virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart(const testing::UnitTest&, int)':
.pio/libdeps/esp32dev/googletest/googletest/src/gtest.cc:3431:72: error: '%s' directive argument is null [-Werror=format-overflow=]
 3431 |     ColoredPrintf(GTestColor::kYellow, "Note: This is test shard %d of %s.\n",
      |                                                                        ^~
cc1plus.exe: some warnings being treated as errors
*** [.pio\build\waveshare_s3_nano\lib828\googletest\googletest\src\gtest.o] Error 1
Uploading stage has failed, see errors above. Use `pio test -vvv` option to enable verbose output.
```

### Expected Results

Tests build and run on esp32

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:native]
platform = native
test_framework = googletest

[env:esp32dev]
platform = platformio/espressif32
;platform = platformio/espressif32@6.8.1
framework = espidf
board = esp32dev
test_framework = googletest
;debug_build_flags= -O0 -Wno-error=format-truncation
;build_type = debug
```

**Source file to reproduce issue:**
```cpp
#include <gtest/gtest.h>

TEST(DummyTest, ShouldPass)
{
    EXPECT_EQ(1, 1);
}

#if defined(IDF_VER)
void app_main() {
  ::testing::InitGoogleTest();
  if(RUN_ALL_TESTS()){}
}
#else
int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  if(RUN_ALL_TESTS());
  return 0;
}
#endif
```

**Comment by valeros** [comment]
Hi @olicooper, thanks for reporting. Similarly to #1476, the default IDF build flags are not compatible with sources from the GoogleTest package. In this case, the reason is the `-Werror=all` flag which implicitly enables `-Werror=format-overflow`. As a workaround, you can manually disable this flag using the [build_unflags](https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_unflags.html) option, for example:

```ini
[env:esp32dev]
platform = platformio/espressif32
framework = espidf
board = esp32dev
test_framework = googletest
build_unflags = -Werror=all
```
