### ISSUE TITLE
GoogleTest not building for ESP32

### ISSUE THREAD

**Issue by olicooper** [platformio/platform-espressif32#1476]
### Description of problem

Test suite fails to build for the esp32 because the arduino platform version is based on c++11 and googletest 1.15.2 requires c++14

googletest package updated recently here: https://github.com/platformio/platformio-core/commit/eeb5ac456eff19a8f1e2bb46397ce486be7d2a72

#### Steps to Reproduce

Use example code from here: https://github.com/platformio/platformio-examples/tree/develop/unit-testing/googletest

### Actual Results

Output on console is as follows
```log
#error C++ versions less than C++14 are not supported.
```

### Expected Results

Should build and run tests on the ESP32 device

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:native]
platform = native
test_framework = googletest

[env:esp32dev]
platform = platformio/espressif32
framework = arduino
board = esp32dev
test_framework = googletest
```

**Source file to reproduce issue:**
```cpp
#include <gtest/gtest.h>

TEST(DummyTest, ShouldPass)
{
    EXPECT_EQ(1, 1);
}

#if defined(ARDUINO)
#include <Arduino.h>
void setup() {
    // should be the same value as for the `test_speed` option in "platformio.ini"
    // default value is test_speed=115200
    Serial.begin(115200);
    ::testing::InitGoogleTest();
}

void loop() {
	// Run tests
	if (RUN_ALL_TESTS()){}
	// sleep 1 sec
	delay(1000);
}
#else
int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
	if (RUN_ALL_TESTS()){}
	// Always return zero-code and allow PlatformIO to parse results
	return 0;
}
#endif
```

**Comment by valeros** [comment]
Hi @olicooper, thanks for reporting. Indeed the latest GoogleTest package requires at least C++14. The Arduino core v2 for ESP32 uses C++11 by default which basically is the reason for this issue. As a workaround I'd recommend updating the default C++ standard using the combination of [build_unflags](https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_unflags.html) and [build_flags](https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_flags.html) , for example:
```
[env:esp32dev]
platform = platformio/espressif32
framework = arduino
board = esp32dev
test_framework = googletest
build_unflags = -std=gnu++11
build_flags = -std=gnu++14
```
