### ISSUE TITLE
Support for ESP32-S3-WROOM-1U-N8R8?

### ISSUE THREAD

**Issue by seansimmons74** [platformio/platform-espressif32#1495]
I am wanting to use this board on PlatformIO and don't see it in their boards menu and was told to check here.  I see others mention the N16R8 variant, so do I need to just change some fields on that file?  

For reference, here is the board I purchased: https://www.digikey.com/en/products/detail/espressif-systems/ESP32-S3-DEVKITC-1U-N8R8/16162636

Thanks in advance.

**Comment by valeros** [comment]
Duplicate https://github.com/platformio/platform-espressif32/issues/989
