### ISSUE TITLE
missing borad Espressif ESP32S3 Dev Module

### ISSUE THREAD

**Issue by GePo00** [platformio/platform-espressif32#1497]
currently there is only a board "Espressif ESP32 Dev Module". A board def for the S3 variant would be great.... ESP32S3 Dev Module

**Comment by valeros** [comment]
Hi @GePo00, there are several S3-based devkits from Espressif available, for example:
- [Espressif ESP32-S3-DevKitC](https://docs.platformio.org/en/latest/boards/espressif32/esp32-s3-devkitc-1.html)
- [Espressif ESP32-S3-DevKitM](https://docs.platformio.org/en/latest/boards/espressif32/esp32-s3-devkitm-1.html)
