### ISSUE TITLE
Is interrupt watchdog enabled?

### ISSUE THREAD

**Issue by MikhailNatalenko** [platformio/platform-espressif32#155]
There is an interrupt watchdog, that described in this DOC 
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/wdts.html

It says that i can turn it on with `make menuconfig` Is there any analog in platformio?

**Comment by valeros** [comment]
Closing as the latest espressif32 platform supports `menuconfig` target  https://docs.platformio.org/en/latest/frameworks/espidf.html#configuration-for-4-0
