### ISSUE TITLE
Dependency Finder for libraries: Update or DNSServer

### ISSUE THREAD

**Issue by alvarolb** [platformio/platform-espressif32#156]
Why platformio cannot find library dependencies for built-in libraries like Update or DNSServer, but it can easily find FS, SPIFFS or WiFi? The error is like the following:

```bash
.piolibdeps/ThingerCore32/src/main.cpp:1:20: fatal error: Update.h: No such file or directory
```
So, I have to manually set Update dependency in the ini, and then it works.

Thanks!

**Comment by valeros** [comment]
Should be fixed in the latest version of the dev-platform. Please reopen if the problem persists.
