### ISSUE TITLE
Compiling Size compared to Arduino

### ISSUE THREAD

**Issue by alvarolb** [platformio/platform-espressif32#157]
Hi, I have been compiling both with Arduino IDE and Platformio, and I started to notice binary size differences.

When compiling a basic sketch with just `setup` and `loop`, like;:

```cpp
void setup() {
}

void loop() {
}
```

The Arduino (with ESP32 1.0.1 installed) generates the following output:

```
Sketch uses 157952 bytes (12%) of program storage space. Maximum is 1310720 bytes.
Global variables use 10652 bytes (3%) of dynamic memory, leaving 284260 bytes for local variables. Maximum is 294912 bytes.
```

When compiling the same code with espressif@1.5.0

```
DATA:    [          ]   4.1% (used 13396 bytes from 327680 bytes)
PROGRAM: [=         ]  13.5% (used 176861 bytes from 1310720 bytes)
```

And compiling the same code with platform espressif@1.6.0

```
DATA:    [          ]   3.9% (used 12616 bytes from 327680 bytes)
PROGRAM: [=         ]  14.6% (used 191493 bytes from 1310720 bytes)
```

It is even more noticeable with large projects, i.e.:

```
Sketch uses 837570 bytes (63%) of program storage space. Maximum is 1310720 bytes.
Global variables use 39056 bytes (13%) of dynamic memory, leaving 255856 bytes for local variables. Maximum is 294912 bytes.
```

vs

```
DATA:    [=         ]  11.8% (used 38768 bytes from 327680 bytes)
PROGRAM: [========  ]  75.9% (used 995099 bytes from 1310720 bytes)
```

So, there is a huge difference between environments. Not sure if it is related to a different SDK configuration, or Platformio using different libraries... I have tried to disable all logs and assertions from sdkconfig.h, but it does not work at all.

Any hint? Thanks!

**Comment by TheSimple** [comment]
I too am facing the same issue, after updating to latest AtmelAVR updates, my program has increased over 100%. Now I cannot upload the code to my Arduino. Someone please help!

**Comment by pierreverbakel** [comment]
I am a me too I am afraid. Got a project with 97% in use in Arduino IDE, in PlatformIO (as Extension installed in VS Code) I get to 1.6 Megabytes 125% (!). So, where is the slack produced. I can only imagine it must be unused libraries linked as dead code. I have a problem to solve using the space, but even using another partition layout rules out the use of OTA, which is a big shame. 
So something is a bit slugish with memory. Having worked with the Nano and Mega, where every byte counts, this seems to be completely out of control.
The Question: What in the setup makes they ESP32 under Platformio so hungry for Flash-space, and more importantly then, what to do about it. 
In Verbose mode I see loads of stuff being compiled. I am clueless to know what actually went into my binary. There seem to be a python script for the ESP-IDF to disassemble the .elf file but I do not know how to do that within the PlatformIO environment. 
It would be very good to have  listing in -v verbose mode to understand what was compiled in. 

Ideas, pointers, hints? All is welcome!

===== Arduino IDE: ===========
Sketch uses 1292702 bytes (98%) of program storage space. Maximum is 1310720 bytes.
Global variables use 66828 bytes (22%) of dynamic memory, leaving 228084 bytes for local variables. Maximum is 294912 bytes.

==== PlatformIO inside VSCode: =======
DATA:    [==        ]  21.0% (used 68936 bytes from 327680 bytes)*** [checkprogsize] Explicit exit, status 1
PROGRAM: [==========]  123.8% (used 1623294 bytes from 1310720 bytes)
esptool.py v2.6

**Comment by CriPstian** [comment]
Switching to esp32 version sky rocketed the size of my `.bin` file three times.
Are there any opinions on this for why is this happening?
I have the exact same code running on one **esp8266** and one **esp32** but a 3x difference in size.
The only fix for continuing OTA uploads is by rethinking the partitions on the device.
Has anyone got to fix it?

**Comment by HamzaHajeir** [comment]
It's very important thing to be fixed! I just had compiled a similar code to Arduino IDE which yielded a difference of  +400kB !!

What's going wrong here ?

**Comment by HamzaHajeir** [comment]
> Switching to esp32 version sky rocketed the size of my `.bin` file three times.
> Are there any opinions on this for why is this happening?
> I have the exact same code running on one **esp8266** and one **esp32** but a 3x difference in size.
> The only fix for continuing OTA uploads is by rethinking the partitions on the device.
> Has anyone got to fix it?

@CriPstian 
To be accurate : ESP32 Arduino core is build on top of RTOS, RTOS is built on top of HAL, So it's like 3 huge layers on top of each others. That lets the binary code goes 800k+ for a blank arduino sketch.

But the issue is that the same code on same target is different between building on Arduino IDE and PlatformIO IDE.

**Comment by davidgiga1993** [comment]
Anyone got any solutions? I'm facing a similar issue where the exact same code (and same libs) have different sizes:
Arduino IDE: 
```
20092 bytes (65%)
```
platformio: 
```
Error: The program size (36472 bytes) is greater than maximum allowed (30720 bytes)
Flash: [==========]  118.7% (used 36472 bytes from 30720 bytes)
```

**Comment by HamzaHajeir** [comment]
Hi

Double check libs and core versions, beside compilation defines, and lastly
compilation flags.

**Comment by aly-fly** [comment]
In Feb 2024 this has still not been resolved.
Project with all freshly updated libraries and core for ESP32, transferred to PlatformIO,  yields this:
Arduino (v1.8): 1040501 bytes.
PlatformIO: 1325369 bytes.
That is approx. +30% or +280kB of the precious space that must be taken away from my file system. Not good.

Tried with all sorts of -O switches for the compiler, but the google search reveals that `-Os` should be already active on both platforms.

**Comment by Jason2866** [comment]
@aly-fly Which core used for ArduinoIDE and which Platform for Platformio?
I do not see any relevant size difference comparing core 2.0.14 and platform 6.5.0 (= core 2.0.14 too)

**Comment by aly-fly** [comment]
It is weird. 
In one simple project I used "Import Arduino" function. Moved local libraries to the .\lib folder. And got size difference listed above.
Another, complex project, I manually created the PIO project and manually moved all files into the .\src folder. Here the compiled code is about the same size.
Then, made empty projects in both and got about the same code size.
PIO.ini file has same contents on both projects, and partitions are the same too.  Core and Libraries are the most recent in all cases. I have no clue why this happened. Maybe the "import arduino" makes something strange in the background.

**Comment by ramiss** [comment]
Following.  this is a huge resource issue.

**Comment by aly-fly** [comment]
@ramiss try to follow my steps. I was able to get same code size.

**Comment by ramiss** [comment]
> @ramiss try to follow my steps. I was able to get same code size.

I'm confused by your steps and your outcomes.  Are you saying you moved 3rd party libraries under the \lib folder to get smaller binary or larger binary? You mentioned the Import Arduino but then I don't see a step to influence that side of it.

**Comment by aly-fly** [comment]
I manually created the PIO project and manually moved all source files into the .\src folder.
External libraries are defined in platformio.ini and downloaded before compilation by PIO.
.\lib folder is empty.
