### ISSUE TITLE
ESP32-ADF and ESP32-IOT

### ISSUE THREAD

**Issue by srini1948** [platformio/platform-espressif32#158]
Will you be adding support for the above in addition to the existing ESP32-IDF?

Thanks

**Comment by maxgerhardt** [comment]
I am currently supporting ESP-ADF as a community project in https://github.com/maxgerhardt/pio-esp-adf-example, though in parallel there is https://github.com/sean6541/PIO-ESP-ADF from @sean6541 with an older version of ESP-ADF but a more complete set of include flags for all the sub-libraries.

**Comment by valeros** [comment]
ESP-IDF components are now supported https://docs.platformio.org/en/latest/frameworks/espidf.html#esp-idf-components
