### ISSUE TITLE
ESP32-IDF and CAN (Control Area Network) modules

### ISSUE THREAD

**Issue by thomasonw** [platformio/platform-espressif32#159]
Hello,

The CAN files from ESP-IDF Release v3.1.2 seem to have been removed when porting over to PlatformIO.  Is this correct?  Is there a reason / is there a way I can add them in manually?

Thank you,

**Comment by maxgerhardt** [comment]
Was also noticed here: https://community.platformio.org/t/having-trouble-using-esp-idf-can-driver-in-platformio/6840 @ivankravets missing file?

**Comment by ivankravets** [comment]
See https://community.platformio.org/t/having-trouble-using-esp-idf-can-driver-in-platformio/6840/4?u=ivankravets
