### ISSUE TITLE
Upgrade to ESP32-IDF v3.2

### ISSUE THREAD

**Issue by cyberman54** [platformio/platform-espressif32#167]
https://github.com/espressif/esp-idf/releases/tag/v3.2

**Comment by cyberman54** [comment]
https://github.com/espressif/arduino-esp32/commit/7b5cd47d07353747aa4b92bb9ac212d18371da20

ping @ivankravets

**Comment by ivankravets** [comment]
Please re-test with the latest upstream version http://docs.platformio.org/en/latest/platforms/espressif32.html#upstream

**Comment by valeros** [comment]
Hi @cyberman54 ! ESP-IDF package has been updated. Please re-test with the latest upstream version http://docs.platformio.org/en/latest/platforms/espressif32.html#upstream

**Comment by cyberman54** [comment]
Thanks! I will test it.
