### ISSUE TITLE
AWS IOT Error - aws_iot: failed! mbedtls_net_connect returned -0x52

### ISSUE THREAD

**Issue by csvke** [platformio/platform-espressif32#170]
- I am trying out the AWS IOT examples for ESP32.
- Got the platformio.ini file edited for my development board (Heltec Lora Wifi 32)
- Got the wifi details in _subscribe_publish_sample.c_ (wifi connection is fine)
- Followed the official documentation and get all the certificates, keys, things, policy set up in AWS console
- Renamed and copied the _certificate.pem.crt_ and _private.pem.key_ into the _src_
 folder

Complied fine. But not working. Serial monitor output as follows:

```
␛[0;31mE (12450) subpub: Error(-23) connecting to :8883␛[0m
␛[0;31mE (13540) aws_iot: failed! mbedtls_net_connect returned -0x52␛[0m
```

Sorry about the lack of information, but I cannot get much more. Thanks a lot

**Comment by valeros** [comment]
We've updated `esp-idf` package to the latest available. Please retest your project with the [upstream version of the platform](http://docs.platformio.org/en/latest/platforms/espressif32.html#upstream)
