### ISSUE TITLE
Extend PSRAM documentation

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-espressif32#175]
Currently, [the documentation](https://docs.platformio.org/en/latest/platforms/espressif32.html#external-ram-psram) regarding activating PSRAM for ESP-IDF is really sparse. It just tells you to look elsewhere and the set of given `build_flags` is not enough to get it running. 

In [this comment](https://github.com/platformio/platform-espressif32/issues/129#issuecomment-426179809), some options were already recommended. For first-time ESP-IDF users it may however be difficult to find that comment and come up with the set of flags for themselves, by searching through the [other documentation](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/kconfig.html#config-spiram-use) and maybe the [Kconfig](https://github.com/espressif/esp-idf/blob/master/components/esp32/Kconfig).

This is why the documentation should be extended with at least one complete set of flags for a specific board. 

I find these set of flags quite general (auto-detect flash type, 40MHz PSRAM): 

```
[platformio]
env_default = esp-wrover-kit-with-psram

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = espidf

[env:esp-wrover-kit-with-psram]
platform = espressif32
board = esp-wrover-kit
framework = espidf
build_flags =
	-mfix-esp32-psram-cache-issue
	-D CONFIG_SPIRAM_CACHE_WORKAROUND=1
	-D CONFIG_SPIRAM_SUPPORT=1
	-D CONFIG_SPIRAM_BOOT_INIT=1
	-D CONFIG_SPIRAM_TYPE_AUTO=1
	-D CONFIG_SPIRAM_SIZE=-1
	-D CONFIG_SPIRAM_SPEED_40M
	-D CONFIG_SPIRAM_MEMTEST=1
	-D CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768
	-D CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
	-D CONFIG_SPIRAM_USE_MALLOC=1
	-D CONFIG_SUPPORT_STATIC_ALLOCATION=1
	-D CONFIG_PICO_PSRAM_CS_IO=10
	-D CONFIG_SPIRAM_OCCUPY_VSPI_HOST
```

Test e.g. with the firmware 

```c
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "sdkconfig.h"

void app_main()
{
	printf("=== app_main() ====\n");
	printf("Free heap size: %d\n", (int) xPortGetFreeHeapSize());
}
```

Output for first env.:

```
Free heap size: 298540
```

second environment (+4MB):

```
Free heap size: 4459764
```

**Comment by valeros** [comment]
Hi @maxgerhardt ! Starting with ESP-IDF v4.0 we use the native configuration system. Could you please try your project with the upstream version of the platform, for example:
```
[env:esp32dev]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32dev
framework = espidf
```
Also take a look at updated docs for ESP-IDF:
https://docs.platformio.org/en/latest/frameworks/espidf.html

Thanks!
