### ISSUE TITLE
Set different sdkconfig params in platformio.ini

### ISSUE THREAD

**Issue by exocode** [platformio/platform-espressif32#183]
I am working with different ESP32 boards (Heltec, DEVKITV1,…) I found out, that Heltec needs different crystal speed (needs 26Mhz).

So when I change that in sdkconfig.h from

#define CONFIG_ESP32_XTAL_FREQ 40

to

#define CONFIG_ESP32_XTAL_FREQ 26

then this is only valid for Heltec boards. But not for the others which need 40 MHz.

How can I solve that challenge?

Thank you in advance

**Comment by ivankravets** [comment]
See https://community.platformio.org/t/set-different-sdkconfig-params-in-platformio-ini/7828/4?u=ivankravets
