### ISSUE TITLE
[upload] Error 2 whle trying to uplad a program

### ISSUE THREAD

**Issue by JaviRuiz314** [platformio/platform-espressif32#194]
Hi,  I have platformIO recently updated to the latest version (pio update with the upstream of the platform) but it seems I cant upload programs to my DOIT DevKit v1 no matter what I do

Any ideas?

**Comment by Ede2016** [comment]
I had the same error when I uploaded the this in PlatformIO when the SD-Card was connected.
I temporarily disconnected the VCC and GND from the card and then I could upload without error.

**Comment by valeros** [comment]
Please reopen the issue if you still need any help.
