### ISSUE TITLE
espidf: conditional compile BT/AWS/etc

### ISSUE THREAD

**Issue by atanisoft** [platformio/platform-espressif32#198]
Currently almost all IDF components are compiled even if they are disabled via sdkconfig.h. It would be ideal to drop compilation entirely for BT/AWS if they are not enabled via sdkconfig.h (IE: CONFIG_BT_ENABLED 0 or not defined, CONFIG_AWS_IOT_SDK 0 or not defined)

**Comment by valeros** [comment]
Closing the issue as we now rely on the native CMake build system.
