### ISSUE TITLE
Question : make menuconfig with platformio

### ISSUE THREAD

**Issue by c0degeekPL** [platformio/platform-espressif32#201]
Hi guys! Quick question, how to run on Mac make menuconfig with platformio? There are many references to his function in expamples but I don't know how to use it.

**Comment by valeros** [comment]
Hi @c0degeekPL ! Unfortunately, it's not possible at the moment as there is no cross-platform solution for this issue. You can manually generate `sdkconfig.h` in ESP-IDF environment and then copy it to your PlatformIO project.

**Comment by c0degeekPL** [comment]
Ok, thanks!
