### ISSUE TITLE
> > As Platformio only supports espidf and I need to get my Arduino project working on idf the best way i've found is to use Arduino as a component o espidf as mentioned in this issue. I get the same error than @anilanilb, Arduino cant be found on platformIO build.

### ISSUE THREAD

**Issue by sajeel-ahmed** [platformio/platform-espressif32#207]
> > As Platformio only supports espidf and I need to get my Arduino project working on idf the best way i've found is to use Arduino as a component o espidf as mentioned in this issue. I get the same error than @anilanilb, Arduino cant be found on platformIO build.
> 
> Start with an IDF only app in PIO and use the sdkconfig.h from arduino-esp32 only. Apply my PR #193 to your local copy and build as a normal IDF project in PIO.
> 
> If you see failures in resolving arduino specific libraries try `lib_compat_mode=strict` in your platformio.ini file.

Hi @MikeDunston, I am in need of your help. I have made project in Arduino IDE using Arduino core of esp32. Actually i am working on esp32. Now i am shifting my code to PlatformIO and I have to use ESP-IDF framework. Actually, in Arduino IDE i have all the libraries which I have used in my code. 

I am copying all libraries in PlatformIO and it is not worth doing it. Is there any way I can use Arduino esp32 core in ESP-IDF Framework?? means so i can use libraries easily while working with esp-idf framework in PlatformIO. 

Thank you for your time and consideration. You help will definitely solve my problem. I was reading your previous discussion on this topic but I could not understand as i am learning PlatformIO.

Best regards
Sajeel Ahmed

_Originally posted by @sajeel-ahmed in https://github.com/platformio/platform-espressif32/issues/24#issuecomment-513575409_

**Comment by valeros** [comment]
Duplicate #206
