### ISSUE TITLE
When can we expect to see ESP-IDF v3.3 ?

### ISSUE THREAD

**Issue by versamodule** [platformio/platform-espressif32#224]
ESP-IDF LTS v3.3 is out. when can we expect an update ?

**Comment by pfeerick** [comment]
Link: https://github.com/espressif/esp-idf/releases/tag/v3.3

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-espressif32/commit/f4b9153ec1d58552a340529923047186425fdac5
