### ISSUE TITLE
1.10.0 bug regarding abs() function

### ISSUE THREAD

**Issue by exige81** [platformio/platform-espressif32#229]
After upgrading to the 1.10.0, I've notice a compile error in a project that had previously worked under 1.9.0.   Switching back to 1.9.0 confirms no error.

Under version 1.9.0, the following example code compiles:

```c++
uint16_t x = -100;
uint16_t y = abs(x) >> 5;
```

Under 1.10.0, the following error is generated

```c++
error: invalid operands of types '__gnu_cxx::__enable_if<true, double>::__type {aka double}' and 'int' to binary 'operator>>'
uint16_t y = abs(x) >> 5;
                       ^
```

It looks like 1.9.0 uses stdlib, while 1.10.0 uses cmath

Wondering if this is a bug or if it's intentional

**Comment by valeros** [comment]
Hi @exige81! I'm not sure that this issue is specific only to PlatformIO. What framework are you using? Have you tried compiling your project in Arduino IDE?

**Comment by exige81** [comment]
@valeros I'm using the arduino framework.

I just confirmed that the code compiles on the latest version of the Arduino IDE (1.8.10).

**Comment by valeros** [comment]
Hm, what version of the board package is installed in Arduino IDE? I just tried v1.0.3 in Arduino IDE and it also fails with the same error.

**Comment by exige81** [comment]
Oops..  had the wrong board package version installed.

Works with arduino-esp32 v1.0.2,  fails with v1.0.3.    I'll go ahead and submit the issue with espressif

**Comment by exige81** [comment]
For anyone else, the issue opened with espressif can be found [here](https://github.com/espressif/arduino-esp32/issues/3231)
