### ISSUE TITLE
Gr eiainErr oe0pnce Itrutwttmoto P0) Error. and broken character

### ISSUE THREAD

**Issue by wjm0621** [platformio/platform-espressif32#23]
I'm Using Sparkfun ESP32 Thing. and sending websocket message.
At the shown image, I met Gr eiainErr oe0pnce Itrutwttmoto P0) Error....

It is not always raised. just somtime shown.
I can't find this at google.

What is this Error means??

And some character is broken. (broken character is English character)
At shown image, code line 146. It will print "TCP handshaking with Server Connected. "
But below the Code, at word "handshaking", 'k', 'n' are broke.
How can i fix this problem??

![esp error](https://cloud.githubusercontent.com/assets/4524843/26753167/75ce4cac-489b-11e7-92f7-d83fa0395b5e.png)
![esp_error_wifi_connecting](https://cloud.githubusercontent.com/assets/4524843/26753169/7e4f8bac-489b-11e7-994c-b725754f5e2c.png)

**Comment by ImanolGo** [comment]
Were you able to solve it? I have exactly the same issue!

**Comment by valeros** [comment]
Hi @wjm0621 @ImanolGo !
Which version of framework do you use? Stable or staging? Do you observe the same behavior in Arduino IDE?

**Comment by wjm0621** [comment]
I'm using Atom 1.17.2 version. and espressif32 package 0.7.4 version(latest).

**Comment by ImanolGo** [comment]
I'm using the Arduino core for the ESP32

https://github.com/espressif/arduino-esp32

**Comment by ivankravets** [comment]
Could you reproduce this issue again?

**Comment by ivankravets** [comment]
Please reopen if you still need help
