### ISSUE TITLE
HTTPS client broken in 1.10.0

### ISSUE THREAD

**Issue by cyberman54** [platformio/platform-espressif32#234]
Due to bug in arduino-esp32 code HTTPS client is broken in 1.10.0.
This has already been fixed:

https://github.com/espressif/arduino-esp32/commit/4ce2cc3c1d1e80d5de5d1c43fed69bbf6ee74394

Since this is a major issue, could you make maintenance patch on 1.10.0?

**Comment by valeros** [comment]
As a workaround you can use [staging version of the platform]( http://docs.platformio.org/en/latest/platforms/espressif32.html#using-arduino-framework-with-staging-version).
