### ISSUE TITLE
Debug Support for AI Thinker ESP32-CAM

### ISSUE THREAD

**Issue by PeterNJackson** [platformio/platform-espressif32#235]
What kind of issue is this?

- looking for debug support for "AI Thinker ESP32-CAM"
- PlatformIO IDE
- AI Thinker ESP32-CAM
-DEBUG support

**Comment by valeros** [comment]
Hi @PeterNJackson ! Could you please explain what the problem is? esp32cam board is already supported. What debug probe do you use?

**Comment by PeterNJackson** [comment]
I tried PIO Debug and in the debug console it said that "AI thinker ESP32-CAM" is not supported yet.
