### ISSUE TITLE
Malformed mkspiffs filepath with "framework = espidf, arduino"

### ISSUE THREAD

**Issue by boarchuz** [platformio/platform-espressif32#244]
If "framework = espidf, arduino", then "Upload File System image" fails with:

> '"mkspiffs_espressif32_espidf arduino"' is not recognized as an internal or external command, operable program or batch file.

See:
https://github.com/platformio/platform-espressif32/blob/develop/builder/main.py#L161

**Comment by valeros** [comment]
Hi @boarchuz ! Looks like that the current build script is not able to handle such case. What version of `mkspiffs` tool (for arduino or esp-idf) should we use when two frameworks specified? Would it be OK if we take the first one from `platformio.ini`?

**Comment by boarchuz** [comment]
Regardless of the order, Arduino will be used as a component of esp-idf, so I think esp-idf should always take precedence if it appears anywhere.
ie:
if "espidf" in $PIOFRAMEWORK
    use esp-idf (default)
else
    use $PIOFRAMEWORK
