### ISSUE TITLE
Source `huge_app.csv' not found when board = esp32cam

### ISSUE THREAD

**Issue by mentarus** [platformio/platform-espressif32#248]
Trying to compile the basic hello world with board = esp32cam and framework = espidf and getting:
`*** [.pio\build\esp32cam\partitions.bin] Source `huge_app.csv' not found, needed by target `.pio\build\esp32cam\partitions.bin'.`
Builds, uploads and monitors fine with board = m5stack-core-esp32

Configuration issue?

Visual Studio code: 1.39.1
Windows 10.0.18632
PIO 1.9.3
Espressif platform 1.90

**Comment by valeros** [comment]
Hi @mentarus ! Thanks for the report. Looks like `huge_app.csv` partition is only supported in Arduino framework. Could you please try to adding the following line to your `platformio.ini`
```
board_build.partitions = partitions_singleapp.csv
```

**Comment by haniffm** [comment]
> Hi @mentarus ! Thanks for the report. Looks like `huge_app.csv` partition is only supported in Arduino framework. Could you please try to adding the following line to your `platformio.ini`
> 
> ```
> board_build.partitions = partitions_singleapp.csv
> ```

This solution worked for me. Thanks!
