### ISSUE TITLE
Adding a library doesn't add the headers to c_cpp_properties.json

### ISSUE THREAD

**Issue by mrmowgli** [platformio/platform-espressif32#255]
I'm running PlatformIO on VS Code, on Ubuntu 18.04 Linux.

platformio.ini
```
[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
```

I created a new project and added the library for `FastLED/FastLED` which worked correctly and that library is placed in `~/.platformio/lib/FastLED_ID126` . The library code compiles correctly and the firmware is uploaded to the device.  VS Code complains that it can't resolve `FastLED.h` 

```
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (/home/andre/Documents/PlatformIO/Projects/esp32Blink/src/main.cpp).
cannot open source file "FastLED.h"
```

Expected behavior:
Adding a library with PlatformIO would add relevant header files to c_cpp_properties.json so that includes can be resolved in the editor.

**Comment by valeros** [comment]
Hi @mrmowgli ! You can manually trigger rebuild of intellisense index https://docs.platformio.org/en/latest/librarymanager/quickstart.html?highlight=rebuild#project-dependencies
Feel free to reopen the issue if you still need any help.
