### ISSUE TITLE
cannot open source file "Arduino.h"

### ISSUE THREAD

**Issue by sekt1953** [platformio/platform-espressif32#275]
What kind of issue is this?

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

I get this error after running today's update 22/1/2020
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (/home/sekt/Documents/PlatformIO/Projects/ESP32_UltraSonic/src/main.cpp).
cannot open source file "Arduino.h"
cannot open source file "Wire.h"
cannot open source file "Adafruit_GFX.h"
cannot open source file "Adafruit_SSD1306.h"
cannot open source file "Sonar.h"

the code had no problim befor running platformio update today 22/1/2020

**Comment by ivankravets** [comment]
Does project build without issues?

**Comment by sekt1953** [comment]
Yes, but when Write Serial.print it do not make spell complement

sekt

Den ons. 22. jan. 2020 kl. 20.11 skrev Ivan Kravets <
notifications@github.com>:

**Comment by ivankravets** [comment]
Could you run `VSCode > View > Command Palette... > C/C++: Reset IntelliSense Databse` ? Wait some time when VScode rebuilds project.

**Comment by sekt1953** [comment]
I still get the same fail
sekt

Den ons. 22. jan. 2020 kl. 20.15 skrev Ivan Kravets <
notifications@github.com>:

**Comment by ivankravets** [comment]
@valeros does it work for you on Ubuntu?

**Comment by sekt1953** [comment]
I am running Ubuntu 18.04

I can Build and upload it to the processor, but the file main.cpp is stil
shown in red color, and the problem bar show the errors after build, but
Build say SUCCESS

Den ons. 22. jan. 2020 kl. 20.20 skrev Ivan Kravets <
notifications@github.com>:

**Comment by sekt1953** [comment]
how do I list the latest update i did on platformio

Den ons. 22. jan. 2020 kl. 20.23 skrev Svenn-Erik Krengelund Thomsen <
sekt1953@gmail.com>:

**Comment by valeros** [comment]
Couldn't reproduce this issue on Ubuntu 18.04.
@sekt1953 Could you please upload your project somewhere?

**Comment by sekt1953** [comment]
Hej
I have bean at cancer treatment to I will try tomorrow, I am to sleappy for
now
Sek.thomsen

tor. 23. jan. 2020 kl. 13.15 skrev Valerii Koval <notifications@github.com>:

**Comment by ivankravets** [comment]
@sekt1953 Oh, no! :( Get well!

**Comment by sekt1953** [comment]
Hej
if i open a new project everything is fine but i open a project that was
created before i updated i get error
here is an older project and a printscreen

Svenn-Erik
 ESP32_UltraSonic.x
<https://drive.google.com/file/d/1oGbgQNlyr_8EkukrYEIKvWkE5_BlBpBA/view?usp=drive_web>

Den fre. 24. jan. 2020 kl. 12.04 skrev Ivan Kravets <
notifications@github.com>:

**Comment by sekt1953** [comment]
Hej
the ESP32_UltraSonic.x is a zip file

Svenn-Erik

Den søn. 26. jan. 2020 kl. 14.18 skrev Svenn-Erik Krengelund Thomsen <
sekt1953@gmail.com>:

**Comment by sekt1953** [comment]
Hej
I did Edit
intelliSenseMode to default valur for linux
saved
removed .vscode
run platormio Rebuild inteilliSense index
closed VSC and reopen and it see to work

but I have to do it for all old project

Svenn-Erik K. Thomsen


Den søn. 26. jan. 2020 kl. 14.19 skrev Svenn-Erik Krengelund Thomsen <
sekt1953@gmail.com>:

**Comment by valeros** [comment]
Feel free to reopen the issue if you still need any help.

**Comment by btvd** [comment]
I got this problem today. Can't fix it though... So I could build, but in my case:

#include "Ardusino.h" 

brings me error. 

"#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit 
cannot open source file "Ardusino.h""

**Comment by MagnusErler** [comment]
> Ardusino



> I got this problem today. Can't fix it though... So I could build, but in my case:
> 
> #include "Ardusino.h"
> 
> brings me error.
> 
> "#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit cannot open source file "Ardusino.h""

Maybe you spelt "Arduino.h" wrong?
