### ISSUE TITLE
Ignoring commented out "#include Arduino.h" when compiling

### ISSUE THREAD

**Issue by danielcrowley** [platformio/platform-espressif32#28]
I'm debugging a bigger problem that I've whittled down to this example
Description:
Compiler ignores commenting in the line `//#include "Arduino.h"` and tries to include it anyway

Reproduce:
 - Take the espidf_httprequest example code (should work with any)
 - Add a header file in a private library (in this case lib/Common/Common.h)
 - Add single include `#include "Arduino.h"` (this fails as in #24, although it says it can't find common.h)
 - Change the line to `//#include "Arduino.h"` (This should still fail)
 - Only compiles again when the line is deleted.

![image](https://user-images.githubusercontent.com/4719443/27985607-4bad3c92-6431-11e7-8cb6-3e27ce0da126.png)

**Comment by ivankravets** [comment]
This is a bug of PIO Core. Please move this issue to https://github.com/platformio/platformio-core/issues

**Comment by ivankravets** [comment]
Could you reproduce this issue with the latest version?

**Comment by ivankravets** [comment]
Please reopen if you still need help
