### ISSUE TITLE
Enable CONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID

### ISSUE THREAD

**Issue by BlueAndi** [platformio/platform-espressif32#289]
Please enable CONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID to be able to get which task is pinned to which core in the TaskStatus_t structure of FreeRTOS.

**Comment by valeros** [comment]
Hi @BlueAndi ! Sorry for the late reply. If you're using ESP-IDF you can use a special command `pio run -t menuconfig` to select required configuration. In case with Arduino, we don't have control over configuration flags set in the `sdkconfig.h`.

**Comment by BlueAndi** [comment]
Hi @valeros, no problem. Does platformio uses for the Arduino framework precompiled libs? Where is the source fir them on github?

**Comment by valeros** [comment]
@BlueAndi We use precompiled libraries shipped with Arduino from here https://github.com/espressif/arduino-esp32/tree/master/tools/sdk. The sources for that libs can be found in the official ESP-IDF repository https://github.com/espressif/esp-idf

**Comment by BlueAndi** [comment]
@valeros Thanks.
