### ISSUE TITLE
Is there an Arduino framework for the ESP32-S module?

### ISSUE THREAD

**Issue by hzhh110** [platformio/platform-espressif32#309]
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  18.3% (used 59812 bytes from 327680 bytes)
Flash: [==========] Error: The program size (1442010 bytes) is greater than maximum allowed (1310720 bytes)

platformio.ini
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

**Comment by valeros** [comment]
Hi @hzhh110 ! It looks like the default partition table is not suitable for your project. You can try other options, for example `huge_app.csv`. More info [here](https://docs.platformio.org/en/latest/platforms/espressif32.html#partition-tables).

BTW, does it work in Arduino IDE?

**Comment by hzhh110** [comment]
![image](https://user-images.githubusercontent.com/19906209/79630091-1fa6a280-8181-11ea-8c05-7172582fbc4d.png)
![image](https://user-images.githubusercontent.com/19906209/79630122-41a02500-8181-11ea-81e5-e3f249705ffc.png)

How should I configure the partition?
Mine is esp32-s 36m flash!

**Comment by hzhh110** [comment]
esp32s 用 board_build.partitions = default.csv

**Comment by hzhh110** [comment]
default_16MB.csv,Now the chip is 32m, how to set it better?

**Comment by davidkjackson54** [comment]
I am also now getting this after adding a few more functions to my code. 
ESP32 4 Meg of Flash.
Using PlatformIO.  Core 5.0.1 Home 3.3.0 
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  18.7% (used 61132 bytes from 327680 bytes)
Error: The program size (1514324 bytes) is greater than maximum allowed (1310720 bytes)
Flash: [====*** [checkprogsize] Explicit exit, status 1
======]  115.5% (used 1514324 bytes from 1310720 bytes)
![Capture](https://user-images.githubusercontent.com/46171060/93277787-9919df80-f777-11ea-83bd-09827e7b2811.PNG)


I would appreciate any help on how I might be able to address this - if it is possible .  I am not familiar with how to override a default size with huge_app.csv for example (as mentioned above).

**Comment by DennisSchm** [comment]
Hey @davidkjackson54, I don't know if you still need help but if I am correct using huge_app.csv adds flashspace by taking space reserved for over the air programming. So if you are not using this feature you are losing nothing.
