### ISSUE TITLE
Flash: [==========] Error: The program size (1442010 bytes) is greater than maximum allowed (1310720 bytes)

### ISSUE THREAD

**Issue by hzhh110** [platformio/platform-espressif32#310]
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM: [== ] 18.3% (used 59812 bytes from 327680 bytes)
Flash: [==========] Error: The program size (1442010 bytes) is greater than maximum allowed (1310720 bytes)

platformio.ini
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

**Comment by valeros** [comment]
Duplicate #309

**Comment by jinu2984** [comment]
hey hzhh110 i am also getting the same error but i have esp32 board. When i am trying to run the same code on windows using arduino ide then it is compiled but here i am using macOS and PlatformIO and i am getting error. Try running on different ide.
