### ISSUE TITLE
When I use WiFi and Bluetooth at the same time, it will appear

### ISSUE THREAD

**Issue by hzhh110** [platformio/platform-espressif32#311]
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM: [== ] 18.3% (used 59812 bytes from 327680 bytes)
Flash: [==========] Error: The program size (1442010 bytes) is greater than maximum allowed (1310720 bytes)

platformio.ini
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

**Comment by valeros** [comment]
Duplicate #309
