### ISSUE TITLE
CMake Files not updating after CMakeLists.txt edit

### ISSUE THREAD

**Issue by fabianpedd** [platformio/platform-espressif32#313]
Hi,

I am using Platformio to build a simple project running on an ESP32. I am using the “new” CMake build system.

When adding a new source file in the `src` directory, immediately after adding the source file to the `CMakeLists.txt` file (more specifically the `idf_component_register` command) and then running `platformio run`, Platformio updates the CMake files, rebuilds the project and everything works fine.

When adding a new source file in the `src` directory and then NOT immediately adding the source file to the the `CMakeLists.txt` and then running `platformio run`, the linker at the end of the build process obviously complains about undefined references (provided I am referencing some symbol from that new source file somewhere in my code).

However, when I now update my `CMakeLists.txt` file to include the new source file and invoke `platformio run` again, the linker still complains about undefined references.

It seems like Platformio is not “updating” its CMake files, when ONLY the contents of the `CMakeLists.txt` file change.

Is there a command that one can use to force Platformio to update the CMake files. Deleting the hidden .pio directory or manually running CMake does not seem to be the most elegant solution.

I am using:
Ubuntu @ 18.4.4
Platformio Core @ 4.3.1
Espressif 32 @ 1.12.0

Thank you for any advice
Fabian

PS: This started as a community post. However, I was advised to open a issue here.

**Comment by valeros** [comment]
Hi @fabianpedd ! PlatformIO creates a default `CMakeLists.txt` only once if there is no such file (mostly for legacy projects). After that user is responsible for synchronizing `CMakeLists.txt`. The only reason why don't we automatically update `CMakeLists.txt` is that there is a chance that a user has modified this file in unpredictable way: added custom functions, enabled ULP, etc. 
So it's a good idea to keep your project compatible with the original build system used with ESP-IDF.
