### ISSUE TITLE
Support for WROVER 32

### ISSUE THREAD

**Issue by barde** [platformio/platform-espressif32#32]
Is there any planned support for the Espressif dev board WROVER 32 for PlatformIO?

Currently I get some weird issues with the partition table when using board = esp32dev:

> --- Enter port index or full name: 2
> --- Miniterm on COM7  115200,8,N,1 ---
> --- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
> ets Jun  8 2016 00:22:57
> 
> rst:0x1 (POWERON_RESET),boot:0x3e (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0x00
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:1
> load:0x3fff0008,len:8
> load:0x3fff0010,len:3472
> load:0x40078000,len:7804
> load:0x40080000,len:252
> entry 0x40080034
> ␛[0;32mI (43) boot: ESP-IDF 2.200.0 2nd stage bootloader␛[0m
> ␛[0;32mI (43) boot: compile time 22:37:02␛[0m
> ␛[0;32mI (53) boot: Enabling RNG early entropy source...␛[0m
> ␛[0;32mI (60) boot: SPI Speed      : 20MHz␛[0m
> ␛[0;32mI (72) boot: SPI Mode       : DIO␛[0m
> ␛[0;32mI (85) boot: SPI Flash Size : 4MB␛[0m
> ␛[0;31mE (97) flash_parts: partition 1 invalid magic number 0x102a␛[0m
> ␛[0;31mE (116) boot: Failed to verify partition table␛[0m
> ␛[0;31mE (132) boot: load partition table error!␛[0m
> user code done

**Comment by ivankravets** [comment]
Added in https://github.com/platformio/platform-espressif32/blob/develop/boards/esp-wrover-kit.json
