### ISSUE TITLE
0x00001000... 0x00008000... 0x0000e000... Where are these three files? How do you merge the program with these three pieces of firmware?

### ISSUE THREAD

**Issue by hzhh110** [platformio/platform-espressif32#322]
Writing at 0x00001000... (100 %)
Wrote 15872 bytes (10319 compressed) at 0x00001000 in 0.3 seconds (effective 492.4 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 119...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (119 compressed) at 0x00008000 in 0.0 seconds (effective 2971.4 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...

Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 10819.8 kbit/s)...
Hash of data verified.
Compressed 770592 bytes to 420623...

**Comment by valeros** [comment]
See the build script for Arduino framework [in the official repository](https://github.com/espressif/arduino-esp32/blob/master/tools/platformio-build.py#L180).
