### ISSUE TITLE
Serial Issues 

### ISSUE THREAD

**Issue by giorgio80** [platformio/platform-espressif32#328]
Latest version installed. 

I'm having problem with serial port.  

Have a Pn532 NFC reader working on serial 1 and Serial for standard prints. 

Arduino side:  
Everything working ok 

Platformio side:

After Reboot Serial1 port does not work anymore and every request goes timeout. 

I'm having exactly problem as reported here: 

https://github.com/espressif/arduino-esp32/issues/662

does this solution has been implemented into release ?

**Comment by valeros** [comment]
Should be fixed in the latest version of the development platform. Please reopen if the problem persists.
