### ISSUE TITLE
upgrading to new netif code

### ISSUE THREAD

**Issue by DasVoelkel** [platformio/platform-espressif32#342]
Esp-IDF update v4.1 cahnged the netif instructions:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/tcpip_adapter_migration.html

When trying to use the new instructions and new headers specified on the page:
> Also replace #include "tcpip_adapter.h" with #include "esp_netif.h".

I get include errors as the headers cannot be found.
Where are these headers located or does PIO not link them at all currently?

I essence i want to switch from `tcpip_adapter_init` to `esp_netif_init` since im total the new event system gives more granular control.

Is only 4.0 and not 4.1 supported yet ?

**Comment by valeros** [comment]
Hi @DasVoelkel ! We support only the stable versions of frameworks. ESP-IDF `v4.1` hasn't been release yet. You can try to override the default package using the [platform_packages](https://docs.platformio.org/en/latest/projectconf/section_env_platform.html#platform-packages) option, but there is no guarantee that it'll work.

**Comment by DasVoelkel** [comment]
So I am guessing only when the next major will be released it will be supported by platformio?

**Comment by valeros** [comment]
That's correct.

**Comment by hassance3** [comment]
I hope this done soon!
Thank you.

**Comment by DasVoelkel** [comment]
they come in yearls cycles
