### ISSUE TITLE
Is platformio Framework-espidf doesn't support all compnents from ESP-IDF?

### ISSUE THREAD

**Issue by walidamriou** [platformio/platform-espressif32#343]
I tried an example from ESP-IDF (from here: https://github.com/espressif/esp-idf/tree/master/examples/protocols/sockets)  and the compiler returned " esp_netif.h: No such file or directory ", I took a long time searching about where the problem exacty is, after that I saw here: ".platformio/packages/framework-espidf/components", and I saw that there isn't folder of "esp_netif" and other folders (I found it in the original ESP-IDF).
So, I tried to copy the folder from the original ESP-IDF "~/esp-idf/components" to ".platformio/packages/framework-espidf/components" and now the compiler stopped working !!

**Doesn't platformio Framework-espidf support all components from ESP-IDF? Are there any solutions for this problem?**

**Comment by valeros** [comment]
Hi @walidamriou ! PlatformIO only supports the stable releases of frameworks. If I'm not mistaken, `esp_netif` [wasn't part of the ESP-IDF v4.0](https://github.com/espressif/esp-idf/tree/v4.0/components). You can try to use previous revision of the examples from here:
```
.platformio/packages/framework-espidf/examples/protocols/sockets
```
