### ISSUE TITLE
Error: Couldn’t find the main target of the project!  

### ISSUE THREAD

**Issue by wegunterjr** [platformio/platform-espressif32#345]
I saw that this was addressed with some code updates, but did this make it into the platformio espressif32 release yet?

**Comment by valeros** [comment]
Hi @wegunterjr ! What version of the `espressif32` platform are using? Please run `pio update` in the PlatformIO IDE terminal.

**Comment by valeros** [comment]
Closing as no further info provided. Feel free to reopen the issue if you're still experiencing the problem with the latest upstream version of the platform.
