### ISSUE TITLE
How do you add a pairing code to a bluetooth service?

### ISSUE THREAD

**Issue by hzhh110** [platformio/platform-espressif32#347]
How do you add a pairing code to a bluetooth service?

**Comment by hzhh110** [comment]
`void initBLE(const char*name){
  DebugPrint("initBLE");
  DebugPrintln(name);
  BLEDevice::init(name); 
  // BLEDevice::init(name,"12345678");
  // Create the BLE Server
	BLEServer *pServer = BLEDevice::createServer();

	pServer->setCallbacks(new MyServerCallbacks());
	
	// Create the BLE Service
	BLEService *pService = pServer->createService(SERVICE_UUID);


	
	// Create a BLE Characteristic
	// pTXCharacteristic = pService->createCharacteristic(CHARACTERISTIC_UUID_TX, BLECharacteristic::PROPERTY_NOTIFY);
  pTXCharacteristic = pService->createCharacteristic(CHARACTERISTIC_UUID_TX, BLECharacteristic::PROPERTY_NOTIFY);
	                 
	pTXCharacteristic->addDescriptor(new BLE2902());
	
	BLECharacteristic *pRXCharacteristic = pService->createCharacteristic(CHARACTERISTIC_UUID_RX, BLECharacteristic::PROPERTY_WRITE);
	
	pRXCharacteristic->setCallbacks(new MyCallbacks());
	
	// Start the service
	pService->start();
	
	// Start advertising
	pServer->getAdvertising()->start();
 ]
}`

**Comment by hzhh110** [comment]
How do you add a passkey to a bluetooth service?

**Comment by kschoos** [comment]
Which framework are you using?

**Comment by valeros** [comment]
Hi @romocitto88 ! This repository is not the right place to ask such generic questions not related to possible problems with the PlatformIO development platform for ESP32, please forward it to to https://gitter.im/espressif/arduino-esp32 or https://community.platformio.org/
