### ISSUE TITLE
toolchain-xtensa32 for ARM

### ISSUE THREAD

**Issue by pmaduarte** [platformio/platform-espressif32#35]
Hi,

I'm having this error on "run".

[Fri Aug 11 17:48:13 2017] Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: arduino)

PackageManager: Installing toolchain-xtensa32 @ ~1.50200.0
Error: Could not find a version that satisfies the requirement '~1.50200.0' for your system 'linux_armv7l'

How do i solve this?

**Comment by ivankravets** [comment]
@igrr do you plan to release ARMv6+ version of ESP32 toolchain??

**Comment by arunderwood** [comment]
I am also encountering this error.  Is this a bug, or a case of the toolchain-xtensa32 not being available for ARM platforms (ie. It is not supported to flash an ESP32 from a RaspberryPi)?

**Comment by tsathishkumar** [comment]
Any plan for this enhancement yet? We are planning to use a RaspberryPi as a CI machine and we are stuck with installing `toolchain-xtensa32`.

**Comment by tsathishkumar** [comment]
@ivankravets Is there a way to configure platformio to download the xtensa32 toolchain from custom link?

**Comment by tsathishkumar** [comment]
@ivankravets sorry, I forgot to publish the changes. Now it is available [here](https://bintray.com/tsathishkumar/toolchain-xtensa32/toolchain-xtensa32/2.50200.80#files)

**Comment by ivankravets** [comment]
Thanks! I've just deployed to our registry.
