### ISSUE TITLE
Esp32 flash size in menuconfig doesn’t work 

### ISSUE THREAD

**Issue by romocitto88** [platformio/platform-espressif32#353]
Hi,
I want to set flash size of my project from 4MB in 8MB, but it doesn’t change!!

This is the Setup in menuconfig:

![Cattura1](https://user-images.githubusercontent.com/61424922/83042077-80a77d00-a041-11ea-8f59-c7d77662f04f.PNG)

This is the error:

![Cattura](https://user-images.githubusercontent.com/61424922/83042087-8604c780-a041-11ea-9e2d-589031637db6.PNG)

Can someone help me?

**Comment by brad-colbert** [comment]
How did you get the 4MB?  Mine is still stuck at 1MB.

**Comment by valeros** [comment]
Have you tried to override the flash size directly in the `platformio.ini` file, e.g.:

```ini
board_upload.maximum_size = 8388608 
```

**Comment by romocitto88** [comment]
In the end I created a custom board file, with the flash size for my esp module.
I will close this issue. 

Thank you.
