### ISSUE TITLE
esp-netif folder is not present in framework-espif v4.0 and sys_platform == 'win32' requirement is not satisfied in v4.1

### ISSUE THREAD

**Issue by ORParga** [platformio/platform-espressif32#357]
I'm starting to use the esp32's wifi capabilities with the tutorials in esp-idf repository. 

I tried to compile the example [fast scan](https://github.com/espressif/esp-idf/tree/7d75213674b4572f90c68162ad6fe9b16dae65ad/examples/wifi/fast_scan) con Visual studio Code and with the esp-idf Command Prompt.

Using VisualStudio Code and platformio, compiler has difficulty identifying esp-netif own variables:

`In file included from src\main.c:6:
C:/Users/OSCAR/.platformio/packages/framework-espidf/components/esp_wifi/include/esp_wifi_default.h:31:41: error: unknown type name 'esp_netif_t'; did you mean 'esp_err_t'?
 esp_err_t esp_netif_attach_wifi_station(esp_netif_t *esp_netif);`

Compilando con la opción:

`platform_packages = 
    framework-espidf @ https://github.com/espressif/esp-idf.git#release/v4.1`

in platformio.ini to use esp-netif libraries the compilation error is another

`The following Python requirements are not satisfied:

esp-windows-curses; sys_platform == 'win32'`

This is the terminal output using 4.1:

`Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)
-------------------------------------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 1.12.1 > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, 
olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-espidf 84b5178
 - tool-cmake 3.16.5
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - tool-idf 1.0.1
 - tool-mconf 1.4060000.20190628 (406.0.0)
 - tool-mkspiffs 2.230.0 (2.30)
 - tool-ninja 1.9.0
 - toolchain-esp32ulp 1.22851.190618 (2.28.51)
 - toolchain-xtensa32 2.80200.200226 (8.2.0)
Reading CMake configuration...
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.25.1.windows.1") 
-- IDF_TARGET not set, using default target: esp32
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/OSCAR/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Users/OSCAR/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc.exe     
-- Check for working C compiler: C:/Users/OSCAR/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/OSCAR/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++.exe
-- Check for working CXX compiler: C:/Users/OSCAR/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Project version: 1
-- Building ESP-IDF components for target esp32
-- Checking Python dependencies...
The following Python requirements are not satisfied:

esp-windows-curses; sys_platform == 'win32'

Please follow the instructions found in the "Set up the tools" section of ESP-IDF Getting Started Guide

-- Configuring incomplete, errors occurred!
See also "E:/PROGRAMACION/ESP32/WIFI/Wifi_2/Wifi_2/.pio/build/esp32dev/CMakeFiles/CMakeOutput.log".

CMake Error at C:/Users/OSCAR/.platformio/packages/framework-espidf@src-53b7d36d17baac64a4ac510f18172271/tools/cmake/build.cmake:271 (message):
  Some Python dependencies must be installed.  Check above message for
  details.
Call Stack (most recent call first):
  C:/Users/OSCAR/.platformio/packages/framework-espidf@src-53b7d36d17baac64a4ac510f18172271/tools/cmake/build.cmake:397 (__build_check_python)
  C:/Users/OSCAR/.platformio/packages/framework-espidf@src-53b7d36d17baac64a4ac510f18172271/tools/cmake/project.cmake:396 (idf_build_process)
  CMakeLists.txt:3 (project)

============================================== [FAILED] Took 6.12 seconds ============================================== 
The terminal process terminated with exit code: 1`

**Comment by valeros** [comment]
Hi @ORParga ! We only support stable versions of frameworks.
