### ISSUE TITLE
Feature Request - Adding additional ESP32 boards - TTGO T4 and TTGO T7 Mini32

### ISSUE THREAD

**Issue by HaroldEmmers** [platformio/platform-espressif32#359]
**Feature Request**:

I would like suppport for the following two boards:
- LilyGO TTGO T4 V1.3 ESP32
- LilyGO TTGO T7 Mini32 V1.4 ESP32-WROVER

**Comment by valeros** [comment]
Please open an issue here https://github.com/espressif/arduino-esp32/issues in the first place, so the board will be added to the Arduino framework officially.
