### ISSUE TITLE
default I2C Pins

### ISSUE THREAD

**Issue by maxledfreak** [platformio/platform-espressif32#361]
Hello,

after init i2c, default pins are PIN16/PIN17. Documented are PIN21/PIN22 as default. board = fm-devkit.

#include <Arduino.h>
#include <Wire.h>

void setup() {
  Wire.begin();
  Serial.begin(115200);
  Serial.println("\nI2C Scanner");
}

**Comment by valeros** [comment]
Hi @maxledfreak ! This repository is not the right place to ask such generic questions not related to possible problems with the PlatformIO development platform for ESP32, please forward it to to https://gitter.im/espressif/arduino-esp32 or https://community.platformio.org/
