### ISSUE TITLE
espidf gen_esp32part.py the --flash-size parameter does not have "detect"

### ISSUE THREAD

**Issue by WallaceWilliam** [platformio/platform-espressif32#364]
https://github.com/platformio/platform-espressif32/blob/082951bacaf321329d4ffbddf3fa281d2c33bd1d/builder/frameworks/espidf.py#L811

if flash_size is not set in the board.json then **--flash-size** is set to **detect**

but in the original

https://github.com/espressif/esp-idf/blob/7d75213674b4572f90c68162ad6fe9b16dae65ad/components/partition_table/gen_esp32part.py#L456

allowed values are only ['1MB', '2MB', '4MB', '8MB', '16MB']

_gen_esp32part.py: error: argument --flash-size: invalid choice: 'detect' (choose from u'1MB', u'2MB', u'4MB', u'8MB', u'16MB')_

**Comment by valeros** [comment]
Thanks for pointing this out.
