### ISSUE TITLE
undefine symbol in generated file

### ISSUE THREAD

**Issue by lglof-vs** [platformio/platform-espressif32#368]
### Description:
Trying to set up logging with my own defined function using the `esp_log_set_vprintf()` function. This requires the `ESP_LOGx` functions to resolve to `esp_log_write`. They're currently resolving to the arduino logging version (`log_x`) which `esp_log_set_vprintf()` won't kick in for.
If I go into `/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/config/sdkconfig.h` and remove the line to define `CONFIG_ARDUHAL_ESP_LOG` then all my logging functions resolve correctly and I get the expected behavior from the function I used in `esp_log_set_vprintf()`.
I don't want to manually change a generated file for many reasons. Thus I've tried `#undef CONFIG_ARDUHAL_ESP_LOG` in many different places throughout my code to no avail.
Is there a way to prevent this from being set? (or to circumvent this issue entirely)

**Comment by valeros** [comment]
Hi @lglof-vs ! You can try to explicitly undefine this symbol using the `build_flags` option:
```
platform = espressif32
framework = arduino
board = ...
build_flags = -U CONFIG_ARDUHAL_ESP_LOG
```
Alternatively, you can override this file from an extra script as described here:
https://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#override-package-files
