### ISSUE TITLE
Python Process Still Running After ESP32 Upload

### ISSUE THREAD

**Issue by neilmendoza** [platformio/platform-espressif32#37]
On OSX uploading to the ESP32 sometimes leaves Python processes even after quitting Atom. They were taking almost 100% CPU each and making my laptop sound like it was about to take off.

**Comment by ivankravets** [comment]
Could you reproduce this issue with the latest version of IDE and PIO Core?

**Comment by ivankravets** [comment]
Please reopen if you still need help
