### ISSUE TITLE
New platformIo core can not upload spiffs files to ESP32

### ISSUE THREAD

**Issue by williamesp2015** [platformio/platform-espressif32#375]
PlatformIO Core: 4.3.4
ESP32 Arduino
previously, I was using F7 (Run Other Target) and by using upload SPIFFS image I could upload data directory to ESP32 but not it not possible.

**Comment by valeros** [comment]
Hi @williamesp2015 ! Could you please clarify what is the problem exactly? Do you see any error?

**Comment by williamesp2015** [comment]
Hi @valeros
There was an option by pressing F7 (run other target) to run Erase and Upload image file (data directory to ESP32 Spiffs) but now dispersed but I could run in the terminal both command:
platformio run --target erase
platformio run --target uploadfs
