### ISSUE TITLE
WiFiScan Compile Error

### ISSUE THREAD

**Issue by LuisPignataro** [platformio/platform-espressif32#382]
### When I try to compile the wifiscan example it doesn't work.
The problem seems to be related to the WiFi.h library, I found the same problem in issue #72  , but the solutions didn't work.

Adding
 lib_deps =
    WiFi
Generate other errors with the spi library SPI.h

## The compilation when running the example without modifications is:

Executing task: C:\Users\luis\.platformio\penv\Scripts\platformio.exe run <

Processing esp32dev (platform: espressif32; framework: arduino; board: esp32dev)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 1.12.4 > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10004.200129 (1.0.4)
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - toolchain-xtensa32 2.50200.80 (5.2.0)
Converting WiFiScan.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 37 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <WiFi> 1.2.7
|   |-- <SPI> 1.0
Building in release mode
Compiling .pio\build\esp32dev\src\WiFiScan.ino.cpp.o
Generating partitions .pio\build\esp32dev\partitions.bin
Compiling .pio\build\esp32dev\lib92a\SPI\SPI.cpp.o
Compiling .pio\build\esp32dev\libc8b\WiFi_ID870\WiFi.cpp.o
Compiling .pio\build\esp32dev\libc8b\WiFi_ID870\WiFiClient.cpp.o
Compiling .pio\build\esp32dev\libc8b\WiFi_ID870\WiFiServer.cpp.o
Compiling .pio\build\esp32dev\libc8b\WiFi_ID870\WiFiUdp.cpp.o
Compiling .pio\build\esp32dev\libc8b\WiFi_ID870\utility\server_drv.cpp.o
Compiling .pio\build\esp32dev\libc8b\WiFi_ID870\utility\spi_drv.cpp.o
Archiving .pio\build\esp32dev\lib92a\libSPI.a
Compiling .pio\build\esp32dev\libc8b\WiFi_ID870\utility\wifi_drv.cpp.o
P:/Arduino/PIO/ejemplos/platform-espressif32/examples/arduino-wifiscan/src/WiFiScan.ino: In function 'void setup()':
P:/Arduino/PIO/ejemplos/platform-espressif32/examples/arduino-wifiscan/src/WiFiScan.ino:14:10: error: 'class WiFiClass' has no member named 'mode'
     WiFi.mode(WIFI_STA);
          ^
P:/Arduino/PIO/ejemplos/platform-espressif32/examples/arduino-wifiscan/src/WiFiScan.ino:14:15: error: 'WIFI_STA' was not declared in this scope
     WiFi.mode(WIFI_STA);
               ^
P:/Arduino/PIO/ejemplos/platform-espressif32/examples/arduino-wifiscan/src/WiFiScan.ino: In function 'void loop()':
P:/Arduino/PIO/ejemplos/platform-espressif32/examples/arduino-wifiscan/src/WiFiScan.ino:41:55: error: 'WIFI_AUTH_OPEN' was not declared in this scope
             Serial.println((WiFi.encryptionType(i) == WIFI_AUTH_OPEN)?" ":"*");
                                                       ^
*** [.pio\build\esp32dev\src\WiFiScan.ino.cpp.o] Error 1
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\spi_drv.cpp: In static member function 'static char SpiDrv::spiTransfer(char)':
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\spi_drv.cpp:36:78: warning: integer overflow in expression [-Woverflow]
 #define DELAY_SPI(X) { int ii=0; do { asm volatile("nop"); } while (++ii < (X*F_CPU/16000000)); }
                                                                              ^
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\spi_drv.cpp:37:26: note: in expansion of macro 'DELAY_SPI'
 #define DELAY_TRANSFER() DELAY_SPI(10)
                          ^
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\spi_drv.cpp:76:5: note: in expansion of macro 'DELAY_TRANSFER'
     DELAY_TRANSFER();
     ^
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\spi_drv.cpp: In static member function 'static void SpiDrv::getParam(uint8_t*)':
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\spi_drv.cpp:36:78: warning: integer overflow in expression [-Woverflow]
 #define DELAY_SPI(X) { int ii=0; do { asm volatile("nop"); } while (++ii < (X*F_CPU/16000000)); }
                                                                              ^
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\spi_drv.cpp:37:26: note: in expansion of macro 'DELAY_SPI'
 #define DELAY_TRANSFER() DELAY_SPI(10)
                          ^
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\spi_drv.cpp:148:5: note: in expansion of macro 'DELAY_TRANSFER'
     DELAY_TRANSFER();
     ^
In file included from C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\spi_drv.cpp:22:0:
C:\users\luis\.platformio\lib\WiFi_ID870\src/utility/spi_drv.h: At global scope:
C:\users\luis\.platformio\lib\WiFi_ID870\src/utility/spi_drv.h:41:13: warning: 'initialized' defined but not used [-Wunused-variable]
 static bool initialized = false;
             ^
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\wifi_drv.cpp: In static member function 'static uint8_t WiFiDrv::getEncTypeNetowrks(uint8_t)':
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\wifi_drv.cpp:451:10: warning: converting to non-pointer type 'uint8_t {aka unsigned char}' from NULL [-Wconversion-null]
   return NULL;
          ^
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\wifi_drv.cpp: In static member function 'static int32_t WiFiDrv::getRSSINetoworks(uint8_t)':
C:\users\luis\.platformio\lib\WiFi_ID870\src\utility\wifi_drv.cpp:476:10: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
   return NULL;
          ^
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'P:\\Arduino\\PIO\\ejemplos\\platform-espressif32\\examples\\arduino-wifiscan\\.pio\\build\\esp32dev\\.sconsign37.db.dblite':
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\Script\Main.py", line 1381:
    _exec_main(parser, values)
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\Script\Main.py", line 1344:
    _main(parser)
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\Script\Main.py", line 1119:
    nodes = _build_targets(fs, options, targets, target_top)
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\Script\Main.py", line 1318:
    jobs.run(postfunc = jobs_postfunc)
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\Job.py", line 113:
    postfunc()
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\Script\Main.py", line 1315:
    SCons.SConsign.write()
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\SConsign.py", line 117:
    syncmethod()
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\dblite.py", line 161:
    self._os_unlink(self._file_name)
Exception ignored in: <function dblite.__del__ at 0x00000275EFA119D8>
Traceback (most recent call last):
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\dblite.py", line 143, in __del__
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\dblite.py", line 140, in close
  File "C:\Users\luis\.platformio\packages\tool-scons\script\..\engine\SCons\dblite.py", line 161, in sync
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'P:\\Arduino\\PIO\\ejemplos\\platform-espressif32\\examples\\arduino-wifiscan\\.pio\\build\\esp32dev\\.sconsign37.db.dblite'=========================================================================================== [FAILED] Took 3.13 seconds =========================================================================================== 
### Testing the examples from Ardiuno's ide works correctly.
I even did tests with other programs, specifically I am working with an esp32-cam board, I can compile from platformio but everything related to WiFi does not work.
The same program works compiling in Arduino ide. I think it is a problem with the WiFi library.

**Comment by kugelkopf123** [comment]
+1

**Comment by valeros** [comment]
Closing as no further info provided. Feel free to reopen the issue if you're still experiencing the problem with the latest upstream version of the platform.
