### ISSUE TITLE
Add support for M5Atom

### ISSUE THREAD

**Issue by doctortee** [platformio/platform-espressif32#389]
(I don't know if this should be posted here, or on the main repo...)

PlatformIO actually supports M5Stack and M5Stick, but doesn't yet support M5Atom. The configuration seems to be similar, but it has a dedicated library located here :
https://github.com/m5stack/M5Atom

Would it be possible to add a dedicated board configuration for them ? Many thanks !

**Comment by TimDeve** [comment]
For people like me who ended up here looking for how to use platformio with the atom, looking at the [M5 docs](https://docs.m5stack.com/#/en/core/atom_matrix)  you can see that the Arduino IDE board is the same as the M5Stick.

This example config works:
```ino
[env:atom]
platform = espressif32
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200

lib_deps =
  M5Atom@0.0.1
  FastLED@3.3.3
```

**Comment by szymoni** [comment]
Hi, were you able to connect M5Atom to WiFi on this board configuration (alternatively board=pico32)?

**Comment by TimDeve** [comment]
Yeah, no problem with the wifi, you can check out my [project](https://github.com/TimDeve/m5light/blob/edfc2ae2c61891ab9083ff2b23bac051dd9a0040/platformio.ini#L26-L33) for an example.

**Comment by eliabieri** [comment]
any updates on this?
