### ISSUE TITLE
xtensa-esp32-elf-g++: error: unrecognized command line option '-mfix-esp32-psram-cache-strategy=memw'

### ISSUE THREAD

**Issue by athusrv** [platformio/platform-espressif32#392]
I'm trying to use Platform IO with `arduino-esp32 [esp32s2 branch]` and `esp-idf [release/v4.2 branch]`.  This is my platform.io file:

```
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
platform_packages =
     framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#esp32s2
     framework-espidf @ https://github.com/espressif/esp-idf.git#release/v4.2
```

When trying to build the project, I got errors with the message: `xtensa-esp32-elf-g++: error: unrecognized command line option '-mfix-esp32-psram-cache-strategy=memw'`

If I use the default branch for those repo in platform_packages (by removing the part starting from #), then the errors are gone. 

How to make Platform IO be able to compile project using the arduino-esp32 from esp32s2 branch and the esp-idf release/v4.2?

**Comment by valeros** [comment]
Hi @athusrv ! We only support stable versions of software. We have some preliminary support for  `esp32s2`, so you need to specify the correct MCU in your `platformio.ini`:
```
[env:esp32s2dev]
platform = espressif32
board = esp32dev
board_build.mcu = esp32s2
...
```
But again I cannot guarantee it will work or even compile.
