### ISSUE TITLE
esp32_exception_decoder not decoding

### ISSUE THREAD

**Issue by sblantipodi** [platformio/platform-espressif32#393]
as title. I have my 
monitor_filters = esp32_exception_decoder, colorize
in my platformio.ini using an esp32 from lolin.

exceptions are not decoded:
```
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x4008a3aa  PS      : 0x00060c33  A0      : 0x8008c23e  A1      : 0x3ffb1d70  
A2      : 0x003ffb80  A3      : 0x0000abab  A4      : 0xb33fffff  A5      : 0x00000001  
A6      : 0x00060a20  A7      : 0x0000cdcd  A8      : 0x0000abab  A9      : 0x3ffb1e60  
A10     : 0x000005b4  A11     : 0x00000001  A12     : 0x00060220  A13     : 0x3ffc2be0  
A14     : 0x05fffffe  A15     : 0x00000000  SAR     : 0x0000000a  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x003ffb80  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  

Backtrace: 0x4008a3aa:0x3ffb1d70 0x4008c23b:0x3ffb1da0 0x4008c8af:0x3ffb1dc0 0x40084a48:0x3ffb1de0 0x40084a7d:0x3ffb1e00 0x40084f41:0x3ffb1e20 0x4000beaf:0x3ffb1e40 0x40139667:0x3ffb1e60 0x40139639:0x3ffb1e80 0x40158d43:0x3ffb1ea0 0x401414d6:0x3ffb1ee0 0x400d5e85:0x3ffb1f00 0x400d2cb6:0x3ffb1f20 0x400d4d72:0x3ffb1f40 0x400dc911:0x3ffb1fb0 0x4008939d:0x3ffb1fd0
```

is there a fix to this? thanks

**Comment by sblantipodi** [comment]
@wassfila thanks for the kind reply, I know it but I would like to use PlatformIO for the purpose since it recently added the feature.

**Comment by valeros** [comment]
Hi @Tasssadar, any chance you could take a look at this issue?

**Comment by Tasssadar** [comment]
Hello, the trace you posted there looks like it should match. Can you post longer output from the serial monitor, ideally including the output immediately after start of the serial monitor?

**Comment by SinglWolf** [comment]
I have the same problem.
`D:\WORK\ESP-IDF\ESP32-Radiola>platformio device monitor -f esp32_exception_decoder
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at http://bit.ly/pio-monitor-filters

Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html



Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html


--- Miniterm on COM5  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
et�R�n��╗ҰL°'��5SH��rs�'�Š     �]�O�%UM�)I��t��E3�i║U}FA*�e1�S�%=O�JC���K�gsZ� 0                                                                                                                                �
�I���x�YHh�k_��i0��)}d���0,�E�v���0���_�.��x�b�d����0,�}�r�'���C���:T��      ���k�V��C!��:��ff���0���:�C!��:��ff���4���:�Lj��0�W�l L&���m��H���d��Q0��0�ɕn�L&�C!��:��00���0�k�:���*�Y���╔0��8��*�I (30) boot:
 ESP-IDF 3.40100.200827 2nd stage bootloader
I (30) boot: compile time 17:59:15
I (30) boot: chip revision: 1
I (33) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (40) boot.esp32: SPI Speed      : 40MHz
I (45) boot.esp32: SPI Mode       : DIO
I (50) boot.esp32: SPI Flash Size : 4MB
I (54) boot: Enabling RNG early entropy source...
I (60) boot: Partition Table:
I (63) boot: ## Label            Usage          Type ST Offset   Length
I (70) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (78) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (85) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (93) boot:  3 ota_0            OTA app          00 10 00010000 001c0000
I (100) boot:  4 ota_1            OTA app          00 11 001d0000 001c0000
I (108) boot:  5 device           unknown          40 00 00390000 00001000
I (115) boot:  6 device1          unknown          42 00 00391000 00001000
I (123) boot:  7 stations         unknown          41 00 00392000 00010000
I (130) boot:  8 hardware         WiFi data        01 02 003a2000 00002000
I (138) boot: End of partition table
I (142) boot_comm: chip revision: 1, min. application chip revision: 0
I (150) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x43408 (275464) map
I (278) esp_image: segment 1: paddr=0x00053430 vaddr=0x3ffb0000 size=0x03f48 ( 16200) load
I (286) esp_image: segment 2: paddr=0x00057380 vaddr=0x40080000 size=0x00404 (  1028) load
I (286) esp_image: segment 3: paddr=0x0005778c vaddr=0x40080404 size=0x0888c ( 34956) load
I (310) esp_image: segment 4: paddr=0x00060020 vaddr=0x400d0020 size=0xb04a8 (722088) map
I (623) esp_image: segment 5: paddr=0x001104d0 vaddr=0x40088c90 size=0x16594 ( 91540) load
I (685) boot: Loaded app from partition at offset 0x10000
I (685) boot: Disabling RNG early entropy source...
I (686) psram: This chip is ESP32-D0WD
I (692) spiram: Found 64MBit SPI RAM device
I (695) spiram: SPI RAM mode: flash 40m sram 40m
I (700) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (708) cpu_start: Pro cpu up.
I (711) cpu_start: Application information:
I (716) cpu_start: Project name:     ESP32-Radiola
I (722) cpu_start: App version:      2.0.1
I (726) cpu_start: Compile time:     Sep 23 2020 17:57:14
I (732) cpu_start: ELF file SHA256:  7ed2f88232160cb4...
I (738) cpu_start: ESP-IDF:          3.40100.200827
I (744) cpu_start: Starting app cpu, entry point is 0x400833a4
I (0) cpu_start: App cpu up.
I (1636) spiram: SPI SRAM memory test OK
I (1637) heap_init: Initializing. RAM available for dynamic allocation:
I (1637) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1643) heap_init: At 3FFBC6C0 len 00023940 (142 KiB): DRAM
I (1649) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1656) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1662) heap_init: At 4009F224 len 00000DDC (3 KiB): IRAM
I (1668) cpu_start: Pro cpu start user code
I (1673) spiram: Adding pool of 4096K of external SPI memory to heap allocator
I (1695) spi_flash: detected chip: generic
I (1695) spi_flash: flash io: dio
I (1695) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (1704) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (1714) main: starting app_main()
I (1714) main: RAM left: 4420884
I (1724) main: Release 2.0, Revision 1
I (1724) main: SDK 3.40100.200827
I (1734) main: Heap size: 4420884
E (1744) main: Running partition type 0 subtype 16 (offset 0x00010000)
I (1774) main: Partition init done...
I (1874) main: audio input number 1
One of COMPUTER = 1, RADIO, BLUETOOTH
Log level is now ESP_LOG_INFO
I (1884) custom: Single device 2b0416c2168eff28 present

I (1894) custom: ds18b20Task task: 3ffbd3f4
I (1894) TDA7313: Init I2C driver, pins 21, 22
I (1894) TDA7313: Init I2C driver OK.
I (1894) custom: Single device optimisations enabled

I (1904) TDA7313: Start TDA7313
I (1914) TDA7313: Device at address 44 found
I (1914) TDA7313: TDA7313 it's OK.
I (1914) TDA7313: Keys for the TDA7313 in NVS founds.
I (1924) TDA7313: Loading values from keys to chip.
I (1944) vs1053: VS1053 LFreq: 1403508
I (1944) vs1053: VS1053 HFreq: 6153846
I (1944) gpio: GPIO[4]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 
I (1944) vs1053: VS1053/VS1003 detected. MP3Status: 40, Version: 4
I (2454) vs1053: SCI_Status  = 0x0
I (2454) vs1053: SCI_Mode (0x4800) = 0x802
I (2454) vs1053: SCI_ClockF = 0xB800
I (2454) vs1053: VS Version (VS1053 is 4) = 4
I (2454) vs1053: I2S Speed: 0
I (2464) VS1053 Patches: plugin size 8896 4448
I (2464) VS1053 Patches: plugin start: 7 1 8050 6

I (2794) main: hardware initialized
I (2794) main: Hardware init done...
I (2794) main: LCD Rotat 1
I (2794) addonucg: lcd init  Rotat: 1
I (2794) ucg_hal: UCG_COM_MSG_POWER_UP: 80 ns so in Hz: 12500000
I (2804) gpio: GPIO[2]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (2814) ucg_hal: ... Adding spi lcd bus  Speed= 25000000.
I (2894) addonucg: lcd init Color type
I (3064) addonucg: X: 320, yy: 240, y: 3

I (3074) main: Set Song buffer to 420k
I (3074) main: Set baudrate at 115200
I (3074) uart: queue free spaces: 20
I (3084) BT201: 0x3ffd01b4   4f 4b                                             |OK|
I (4084) BT201: 0x3ffd01b4   0d 0a 6f 00 00 41 54 2b  56 45 52 32 2e 33 2d 32  |..o..AT+VER2.3-2|
I (4084) BT201: 0x3ffd01c4   30 31 39 31 31 31 35 00                           |0191115.|
I (4094) BT201: 0x3ffd01b4   0d 0a 51 41 2b 31 31                              |..QA+11|
BT#: Current Volume: 11
I (4104) BT201: 0x3ffd01b4   0d 0a 51 4d 2b 30 30                              |..QM+00|
I (4114) BT201: 0x3ffd01b4   0d 0a 51 4e 2b 30 31                              |..QN+01|
I (4124) BT201: 0x3ffd01b4   0d 0a 51 4b 2b 30 31                              |..QK+01|
I (4134) BT201: 0x3ffd01b4   0d 0a 51 47 2b 30 31                              |..QG+01|
I (4144) BT201: 0x3ffd01b4   0d 0a 51 31 2b 30 31                              |..Q1+01|
I (4154) BT201: 0x3ffd01b4   0d 0a 52 42 2b 30 33                              |..RB+03|
I (4164) BT201: 0x3ffd01b4   0d 0a 43 35 2b 30 30                              |..C5+00|
I (4164) BT201: 0x3ffd01b4   0d 0a 52 56 2b 33 35                              |..RV+35|
I (4174) BT201: 0x3ffd01b4   0d 0a 51 4d 2b 30 31                              |..QM+01|
I (4184) BT201: 0x3ffd01b4   0d 0a 54 53 2b 30 30                              |..TS+00|
BT#: Bluetooth has not been connected successfully and is in a waiting pairing state
I (4584) BT201: VER2.3-20191115
I (5494) main: Volume set to 120
I (5494) main: t0 task: 3ffd13b4
I (5494) main: Starting WiFi
I (5504) wifi:wifi driver task: 3ffd5f70, prio:23, stack:6656, core=0
I (5504) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (5504) BT201: 0x3ffd01b4   0d 0a 54 4c 2b 30 31                              |..TL+01|
I (5504) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
BT#: BLE is idle.
I (5534) BT201: 0x3ffd01b4   0d 0a 54 4c 2b 30 32                              |..TL+02|
BT#: BLE is broadcasting.
I (5544) BT201: 0x3ffd01b4   0d 0a 54 31 2b 30 30                              |..T1+00|
I (5544) wifi:wifi firmware version: 3ea4c76
I (5544) BT201: 0x3ffd01b4   0d 0a 54 32 2b 30 31                              |..T2+01|
I (5554) wifi:config NVS flash: enabled
I (5564) BT201: 0x3ffd01b4   0d 0a 54 33 2b 30 31                              |..T3+01|
I (5564) wifi:config nano formating: disabled
I (5574) BT201: 0x3ffd01b4   0d 0a 54 34 2b 30 31                              |..T4+01|
I (5574) wifi:Init dynamic tx buffer num: 32
I (5584) BT201: 0x3ffd01b4   0d 0a 54 35 2b 30 31                              |..T5+01|
I (5594) wifi:Init data frame dynamic rx buffer num: 32
I (5594) BT201: 0x3ffd01b4   0d 0a 54 45 2b 30 30 30  30                       |..TE+0000|
I (5604) wifi:Init management frame dynamic rx buffer num: 32
I (5614) BT201: 0x3ffd01b4   0d 0a 54 44 2b 42 54 32  30 31 2d 41 55 44 49 4f  |..TD+BT201-AUDIO|
I (5614) wifi:Init management short buffer num: 32
I (5624) BT201: 0x3ffd01c4   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
I (5634) wifi:Init static tx buffer num: 16I (5644) BT201: 0x3ffd01d4   00 00 00                                          |...|

I (5654) wifi:Init static rx buffer size: 1600
I (5654) BT201: 0x3ffd01b4   0d 0a 54 41 2b 42 38 45  39 45 34 44 37 33 39 38  |..TA+B8E9E4D7398|
I (5654) wifi:Init static rx buffer num: 10I (5664) BT201: 0x3ffd01c4   30                                                |0|

I (5674) wifi:Init dynamic rx buffer num: 32
I (5684) BT201: 0x3ffd01b4   0d 0a 54 4d 2b 42 54 32  30 31 2d 42 4c 45 00 00  |..TM+BT201-BLE..|
I (5684) main: WiFi init done!
I (5694) BT201: 0x3ffd01c4   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
WIFI TRYING TO CONNECT TO SSID 1
I (5704) BT201: 0x3ffd01d4   00 00 00                                          |...|
I (5714) main: connecting OpenWrt
I (5714) BT201: 0x3ffd01b4   0d 0a 54 42 2b 42 39 45  39 45 34 44 37 33 39 38  |..TB+B9E9E4D7398|
I (5734) BT201: 0x3ffd01c4   30                                                |0|
I (5744) BT201: 0x3ffd01b4   0d 0a 54 36 2b 46 46 46  30                       |..T6+FFF0|
I (5744) BT201: 0x3ffd01b4   0d 0a 54 37 2b 46 46 46  31                       |..T7+FFF1|
I (5754) BT201: 0x3ffd01b4   0d 0a 54 38 2b 46 46 46  32                       |..T8+FFF2|
I (5764) BT201: 0x3ffd01b4   0d 0a 54 39 2b 46 46 46  33                       |..T9+FFF3|
I (5774) BT201: 0x3ffd01b4   0d 0a 54 52 2b 30 31 32  33 34 35 36 37 38 39     |..TR+0123456789|
I (5814) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
I (5814) wifi:mode : sta (b4:e6:2d:e0:91:e5)
I (7864) wifi:new:<13,2>, old:<1,0>, ap:<255,255>, sta:<13,2>, prof:1
I (8444) wifi:state: init -> auth (b0)
I (8454) wifi:state: auth -> assoc (0)
I (8464) wifi:state: assoc -> run (10)
I (8484) wifi:connected with OpenWrt, aid = 1, channel 13, 40D, bssid = e8:94:f6:5e:45:84
I (8484) wifi:security: WPA2-PSK, phy: bgn, rssi: -18
I (8484) wifi:pm start, type: 1

I (8484) main: Wifi connected
I (8574) wifi:AP's beacon interval = 102400 us, DTIM period = 2
I (9494) esp_netif_handlers: sta ip: 192.168.0.149, mask: 255.255.255.0, gw: 192.168.0.1
W (9504) main: DNS: 68.118.251.63  

I (9614) TDA7313: Keys for the TDA7313 keep to NVS.
I (9614) main: Initializing SNTP
I (10154) main: Waiting for system time to be set... (1/5)
W (13154) main: IP: 192.168.0.149


E (14734) main: mDNS Init ok
E (14734) main: mDNS Hostname: ESP32Radiola
I (20714) main: RAM left 3887760
I (20714) main: uartInterfaceTask task: 3ffc2ed0
I (20724) main: clientTask task: 3ffc3d14
I (20734) servers: watermark: 0xae4  2788
I (20734) servers: telnetServer_sock socket: 54, errno: 0
I (20734) servers: Webserver socket: 55, errno: 0
I (20734) main: serversTask task: 3ffc4a9c
I (20754) main: task_addon task: 3ffc54a0
I (20754) addon: rmt_nec_rx_task task: 3ffc5e70
I (20754) addon: task_lcd task: 3ffc6874
I (21384) main:  Init Done
READY. Type help for a list of commands
##CLI.ICY0#: IP 192.168.0.149
##CLI.ICY0#: ОЖИДАНИЕ
I (25024) BT201: 0x3ffd01b4   0d 0a 4d 55 2b 30 32                              |..MU+02|
BT#: USB disk pull-out.
CORRUPT HEAP: multi_heap.c:439 detected at 0x3ffd60f0
abort() was called at PC 0x4009384b on core 0

ELF file SHA256: 7ed2f88232160cb4

Backtrace: 0x4008e18d:0x3ffaf880 0x4008e539:0x3ffaf8a0 0x4009384b:0x3ffaf8c0 0x40086869:0x3ffaf8e0 0x400868a8:0x3ffaf900 0x40096bad:0x3ffaf920 0x40085fc1:0x3ffaf940 0x4014e149:0x3ffaf960 0x40157e1d:0x3ffaf980 0x40154f41:0x3ffaf9a0 0x400fe3f2:0x3ffaf9c0 0x400fe467:0x3ffaf9e0 0x4008fb8d:0x3ffafa00

CPU halted.`
My platform.ini
`[platformio]
src_dir = main
lib_dir = components
description = ESP32-Radiola

[env:esp-wrover-kit]
platform = https://github.com/platformio/platform-espressif32.git
board = esp-wrover-kit
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_flags = 
	--echo
	--raw

board_build.partitions = partitions.csv
build_flags = 
	-D FILENAME=ESP32Radiola
	-DCONFIG_SPIRAM_CACHE_WORKAROUND
	-Iinclude
	-Icomponents/audio_player/src
	-Icomponents/tda7313
	-Icomponents/fifo/src
	-Icomponents/ucglib/src
	-Icomponents/xpt2046
extra_scripts = pre:extra_script.py`
Why isn't decoding working?

**Comment by Gearme** [comment]
Same problem - added the `monitor_filters = esp32_exception_decoder` with `platform = https://github.com/platformio/platform-espressif32.git` but continue to get undecoded back traces.

**Comment by Gearme** [comment]
My issue has been resolved - for reference: I was missing a `build_type = debug`.

**Comment by ZweiEuro** [comment]
I am getting similar issues with the watchdog backtrace:

```
E (95132) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (95132) task_wdt:  - IDLE0 (CPU 0)
E (95132) task_wdt: Tasks currently running:
E (95132) task_wdt: CPU 0: btController
E (95132) task_wdt: CPU 1: IDLE1
E (95132) task_wdt: Print CPU 0 (current core) backtrace


Backtrace:0x4013B303:0x3FFBE790 0x40082FF9:0x3FFBE7B0 0x40188A40:0x3FFB5E90 0x40188FF9:0x3FFB5EB0 0x4008FED5:0x3FFB5EE0 

E (95132) task_wdt: Print CPU 1 backtrace


Backtrace:0x40081DC3:0x3FFBED90 0x40082FF9:0x3FFBEDB0 0x4000BFED:0x3FFBC870 0x40090135:0x3FFBC880 0x4013B5A7:0x3FFBC8A0 0x4013B5B3:0x3FFBC8D0 0x4013B669:0x3FFBC8F0 0x40090B0D:0x3FFBC910 0x4008FED5:0x3FFBC930 

E (100132) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (100132) task_wdt:  - IDLE0 (CPU 0)
E (100132) task_wdt: Tasks currently running:
E (100132) task_wdt: CPU 0: btController
E (100132) task_wdt: CPU 1: IDLE1
E (100132) task_wdt: Print CPU 0 (current core) backtrace


Backtrace:0x4013B303:0x3FFBE790 0x40082FF9:0x3FFBE7B0 0x40188A40:0x3FFB5E90 0x40188FF9:0x3FFB5EB0 0x4008FED5:0x3FFB5EE0 

E (100132) task_wdt: Print CPU 1 backtrace


Backtrace:0x40081DC3:0x3FFBED90 0x40082FF9:0x3FFBEDB0 0x4000BFED:0x3FFBC870 0x40090135:0x3FFBC880 0x4013B5A7:0x3FFBC8A0 0x4013B5B3:0x3FFBC8D0 0x4013B669:0x3FFBC8F0 0x40090B0D:0x3FFBC910 0x4008FED5:0x3FFBC930 

```

**Comment by sblantipodi** [comment]
> build_type = debug

my issue has been solved with this too. closing it.
