### ISSUE TITLE
Automatically include "monitor_speed = 115200" in "platformio.ini" file

### ISSUE THREAD

**Issue by walidamriou** [platformio/platform-espressif32#394]
We know that by default the Monitor works with 115200 baud speed with Platformio, why doesn't it include "monitor speed = 115200" automatically in "platformio.ini" file.

![Screenshot from 2020-08-22 00-27-55](https://user-images.githubusercontent.com/10174229/90940237-5da52300-e40e-11ea-8dbe-0235b687e2c1.png)

**Comment by valeros** [comment]
Hi @walidamriou ! Thanks for your suggestion, the project initialization routine is common for all platforms. if you need something specific you can use [--project-option](https://docs.platformio.org/en/latest/core/userguide/project/cmd_init.html#cmdoption-platformio-project-init-o) when creating a new project.

**Comment by walidamriou** [comment]
Hi @valeros Thank you
