### ISSUE TITLE
ESP-IDF release v4.1 support

### ISSUE THREAD

**Issue by kaizoku-oh** [platformio/platform-espressif32#397]
Any news on when to update the framework to support release v4.1 of esp-idf?

**Comment by valeros** [comment]
Hi @kaizoku-oh ! Thanks for reminding. I've just pushed updates for ESP-IDF, please retest your project with the upstream version:
```
[env:upstream_develop]
platform = https://github.com/platformio/platform-espressif32.git
framework = esp-idf
board = ...
```

**Comment by kaizoku-oh** [comment]
Thank you 😃
