### ISSUE TITLE
Support for Espressif ESP32-DevKitC V4 board with ESP32-WROOM-32D module

### ISSUE THREAD

**Issue by kfine100** [platformio/platform-espressif32#400]
I have the version with the ESP32-WROOM-32D module. Not sure if any of the existing boards on PlatformIO corresond to this board. Thanks

**Comment by valeros** [comment]
You should be able to use `esp32dev` board since the only difference is that `ESP32-WROOM-32D` has U.FL connector instead of an on-board antenna.

**Comment by cooley420** [comment]
esp32-wroom-32u has the antenna connector and 32d has on-board.
