### ISSUE TITLE
HX711 and ESP32

### ISSUE THREAD

**Issue by Barros32** [platformio/platform-espressif32#412]
Hello, I would like to understand if it's possible to use nanoframework and ESP32 to read HX711 converter ?
I'm asking this because in past I've try it using a similar platform using python and it was impossible or at least very difficult to achieve sincronism with HX711 due to vm task scheduling and minimal sleep value was 1ms so I was forced to do it using c/c++. 
I have many years of .NET desktop app development and I just met this platform so I was thinking about to migrate a small project I have into c# but I would like to understand from you if it is possible to achieve HX711 readings without issues. 

BR
Vitor

**Comment by maxgerhardt** [comment]
PlatformIO doesn't even support the C# nanoFramework (https://github.com/nanoframework/Home). Though I also don't think it's the best idea to run a C# interpreter or JIT on an ESP32 to execute something that must apparently be realtime. The project https://github.com/bogde/HX711 may be a good starting point for you.
