### ISSUE TITLE
Add debugging support for `Heltec WiFi Kit 32`.

### ISSUE THREAD

**Issue by hatsch001** [platformio/platform-espressif32#418]
What kind of issue is this?
Error: Currently, PlatformIO does not support debugging for `Heltec WiFi Kit 32`.
Please request support at https://github.com/platformio/platformio-core/issues  

Hi, it would be great if you could add debugging support for `Heltec WiFi Kit 32`. 

https://heltec.org/project/wifi-kit-32/

**Comment by valeros** [comment]
According to the [board schematic](http://resource.heltec.cn/download/WiFi_Kit_32/WIFI_Kit_32_Schematic_diagram_V2.pdf) the required  JTAG  TDO pin is used by the OLED display, so there is no easy way to debug this board.
