### ISSUE TITLE
heltec_wifi_lora_32.rst incorrectly lists this board as 4MB flash.  There are 8MB variants.  Please note.

### ISSUE THREAD

**Issue by scubachristopher** [platformio/platform-espressif32#419]
[https://heltec.org/project/wifi-lora-32/](url)

![image](https://user-images.githubusercontent.com/10871350/96177818-4c930280-0ee3-11eb-92ba-31d6afdf881a.png)

**Comment by valeros** [comment]
[Heltec WiFi LoRa 32 V2](https://docs.platformio.org/en/latest/boards/espressif32/heltec_wifi_lora_32_V2.html#id1) is the right board with 8MB.
