### ISSUE TITLE
Some files not updated in ESP-IDF v4.1 package

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-espressif32#426]
The latest `framework-espidf` package is `framework-espidf-3.40100.200827.tar.gz`, which is supposed to be the v4.1 release from August 27th, 2020. However, the package contains an outdated `esp_vfs_dev.h` which was changed on August 24th. Instead it has the last version before that from 'Aug 1, 2019'. According to the date in the package, the updated file should have been there, but it's not -- can an update for the package be released? 

This was noted in https://community.platformio.org/t/esp-idf-platformio-package-version-discrepancy/16989 first.

**Comment by valeros** [comment]
Explained in that community topic.
