### ISSUE TITLE
Increase looptask stack size

### ISSUE THREAD

**Issue by gonzabrusco** [platformio/platform-espressif32#431]
Hello. I would like to increase the stack size of the FreeRTOS task that handles the Loop() funcion in Arduino. Can you please tell me the best way to achieve this in PlatformIO?

The file in question is this one: 

`https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/main.cpp`

And I need to change this line:

`xTaskCreateUniversal(loopTask, "loopTask", 8192, NULL, 1, &loopTaskHandle, CONFIG_ARDUINO_RUNNING_CORE);`

To this

`xTaskCreateUniversal(loopTask, "loopTask", 16384, NULL, 1, &loopTaskHandle, CONFIG_ARDUINO_RUNNING_CORE);`

I can't figure out the best way to do this. In Arduino IDE I could just modify the file in my local copy. But platformIO only shows me the object files (*.o) of the framework and not the source.

I thought about cloning your repo, but you framework repository does no have any code (I guess the py scripts download directly from the official repository?). 

I also thought in cloning espressif repository and applying my changes and then point platformIO to it using **platform_packages**) but I first tried directly with the official repository (without any changes) using this (I need version 1.0.4):

`platform_packages = platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git@1.0.4`

But I receive the following error:
```
Submodule path 'libraries/AzureIoT': checked out '5e8ffb21115675f8c258e81bb287a9cd610e3205'
Error: Package version 0.0.0+sha.6d256b6 doesn't satisfy requirements 1.0.4 based on PackageMetaData <type=tool name=framework-arduinoespressif32 version=0.0.0+sha.6d256b6 spec={'owner': None, 'id': None, 'name': 'framework-arduinoespressif32', 'requirements': '1.0.4', 'url': 'git+https://github.com/espressif/arduino-esp32.git'}
```

I'm willing to work with PlatformIO but I'm lost at this point. How can I modify the framework? 

Thanks!

**Comment by valeros** [comment]
Hi @gonzabrusco ! You can find your local copy here:
```
Unix ~/.platformio/packages/framework-arduinoespressif32
Windows %HOMEPATH%\.platformio\packages\framework-arduinoespressif32
```
Keep in mind that it might be overridden with the next platform release.

**Comment by gonzabrusco** [comment]
Can you please explain me why version 1.0.4 taken from espressif repository does not compile? 

I would like to make my own repository with my own changes. But for that first I need to understand why version 1.0.4 is not compiling. Thanks.

**Comment by valeros** [comment]
> I would like to make my own repository with my own changes. But for that first I need to understand why version 1.0.4 is not compiling. Thanks.

What is the error message exactly?

**Comment by gonzabrusco** [comment]
It's on my original post. I did not expressed myself well. I meant it does not finish downloading the platform_packages because it tries to download another repository (AzureIoT) and because the version does not match it aborts. But the version specifier was for the espressif repo, not for all of them. I think this is related to the .gitmodules file in the espressif repository.

**Comment by valeros** [comment]
You need to use a tagged version of the repository:
```
platform_packages =
    platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#1.0.4
```
But keep in mind that the PlatformIO build script in that version is outdated, so you will need to use actual one from the original `framework-arduinoespressif32` package.

**Comment by gonzabrusco** [comment]
Thank you @valeros !! Cloning the espressif repo, branching 1.0.4 and cherry picking your platformio-build.py commits did the trick. I can now make my own modifications to the stack. Thanks for you help.
