### ISSUE TITLE
Trying to use bluetooth serial library

### ISSUE THREAD

**Issue by hrushikesh1024** [platformio/platform-espressif32#435]
<img width="1361" alt="Screenshot 2020-11-21 at 7 29 51 PM" src="https://user-images.githubusercontent.com/9022241/99879072-0e020d80-2c30-11eb-91e0-651c6eb668f7.png">

I am getting this warnings when I am using bluetooth serial library from Arduino.

When I compile the same code in Arduino It is compiling with out warnings and working fine.

Following is my code I am compiling, It is getting compiled but not working as it should. May be that is because of the Warnings.

Please suggest a fix

```cpp
#include <Arduino.h>

#include "BluetoothSerial.h"

#if !defined(CONFIG_BT_ENABLED) || !defined(CONFIG_BLUEDROID_ENABLED)
#error Bluetooth is not enabled! Please run `make menuconfig` to and enable it
#endif

BluetoothSerial SerialBT;
int incoming;
int v1,v2;
void setup() {
  // put your setup code here, to run once:
 Serial.begin(9600);
 SerialBT.begin("ESP32test"); //Bluetooth device name
 Serial.println("The device started, now you can pair it with bluetooth!"); 
}

void loop() {
  // put your main code here, to run repeatedly:
 if (SerialBT.available()){
  incoming = SerialBT.read();
  if (incoming == 40){
      v1= SerialBT.read();
      Serial.println(v1);
    }
  if (incoming == 50){
      v2= SerialBT.read();
      Serial.println(v2);
    }
    
  }
 // Serial.println(v1);
 // Serial.println(v2);
  delay(2000);

}
```

**Comment by valeros** [comment]
Hi @hrushikesh1024 ! That warnings shouldn't affect you application behavior. Please attach here two verbose logs from PlatformIO and Arduino IDE.
