### ISSUE TITLE
Adafruit Feather-S2 (ESP32-S2) support?

### ISSUE THREAD

**Issue by taf2** [platformio/platform-espressif32#445]
I saw https://github.com/platformio/platform-espressif32/issues/432 is still underway to support esp32-s2 chips but was not seeing references to feathers2 boards found here: https://www.adafruit.com/product/4769

Thanks!

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-espressif32/commit/7e5f3f56fada130e7b7bb4b29330ed45b72af626. Please retest with the upstream version of the platform:
```
[env:esp32dev]
platform = https://github.com/platformio/platform-espressif32.git
framework = espidf
board = esp32dev
monitor_speed = 115200
```
