### ISSUE TITLE
Ethernet spi support

### ISSUE THREAD

**Issue by giorgio80** [platformio/platform-espressif32#447]
hello, 

latest esp-idf 4.1 introduce support for spiritual ethernet ( dm9051 ) 
it is planned to port this into platformio ?  
when official 4.1 will be use as base ?

**Comment by valeros** [comment]
The support for ESP-IDF v4.1 was added in [v2.0.0](https://github.com/platformio/platform-espressif32/releases/tag/v2.0.0).
