### ISSUE TITLE
Toolchain xtensa32 missing for darwmin_arm64

### ISSUE THREAD

**Issue by clementnuss** [platformio/platform-espressif32#451]
Hi,

The `toolchain_xtensa32` package is missing for the new Mac's with the M1 chipset (`darwin_arm64`).
I am trying to build it myself, then I will publish a binary in this issue.

It would help if I had access to build instructions for `toolchain_xtensa32`, does anyone have that?

Have a good week!

**Comment by valeros** [comment]
Hi @clementnuss ! We appreciate that you want to help. The official instruction for compiling from sources can be found [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-setup-scratch.html#compile-the-toolchain-from-source).

**Comment by valeros** [comment]
Toolchains package have been updated to support darwin_arm64.
