### ISSUE TITLE
Could not find the package with 'platformio/tool-cmake @ ~3.16.0' requirements for your system 'linux_armv7l'"

### ISSUE THREAD

**Issue by cashoefman** [platformio/platform-espressif32#477]
PIO Core Call Error: "The current working directory /home/pi/Documents/PlatformIO/Projects/test will be used for the project.\n\nThe next files/directories have been created in /home/pi/Documents/PlatformIO/Projects/test\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatform Manager: Installing espressif32\nPlatform Manager: espressif32 @ 2.1.0 has been installed!\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.50200.0\nTool Manager: toolchain-xtensa32 @ 2.50200.80 has been installed!\nTool Manager: Installing platformio/tool-esptoolpy @ ~1.30000.0\nTool Manager: tool-esptoolpy @ 1.30000.201119 has been installed!\nThe platform 'espressif32' has been successfully installed!\nThe rest of the packages will be installed later depending on your build environment.\n\n\nError: Could not find the package with 'platformio/tool-cmake @ ~3.16.0' requirements for your system 'linux_armv7l'"

**Comment by valeros** [comment]
The CMake package for ARMv7 is now available, please try to compile your project again.
