### ISSUE TITLE
Please correct the description /boards/lolin_d32_pro.json

### ISSUE THREAD

**Issue by gmbo** [platformio/platform-espressif32#482]
Korregiere bitte die Beschreibung /boards/lolin_d32_pro.json.
Es gibt da 4 Dinge die Anders sind in der Datei.
Das Bord verfügt über psram
das könnte in den extra-Flags stehen (Zeile 7)
    "extra_flags": "-DARDUINO_LOLIN_D32_PRO -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue",

Die d32 pro Bords sind mit einem ESP32 -wrover bestückt (Zeile 21) 
    "openocd_board": "esp32-wrover.cfg"

Das Bord ist mit 4MB und mit 16 MB Flash erhältlich. (Zeile 31) 
    "maximum_size": 16777216,
deshalb ist    "maximum_size": 4194304,
 falsch.
Die URL der Beschreibung ist ein toter Link. (Zeile 35) 
Sie ist jetzt unter "url": "https://www.wemos.cc/en/latest/d32/d32_pro.html" erreichbar.

Vielen Dank

Please correct the description /boards/lolin_d32_pro.json.
There are 4 things that are different in the file.
The board has psram
that could be in the extra flags (line 7)
    "extra_flags": "-DARDUINO_LOLIN_D32_PRO -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue",

The d32 pro boards are equipped with an ESP32 -wrover (line 21) 
    "openocd_board": "esp32-wrover.cfg".

The board is available with 4MB and with 16 MB flash. (line 31) 
    "maximum_size": 16777216,
therefore "maximum_size": 4194304,
 wrong.
The URL of the description is a dead link. (line 35) 
It is now available at "url": "https://www.wemos.cc/en/latest/d32/d32_pro.html".

Thanks a lot

Translated with www.DeepL.com/Translator (free version)

**Comment by valeros** [comment]
Thanks for pointing it out. The only thing that wasn't fixed is flash memory size. As you mentioned there are two variations of this board with 4MB and 16MB, in our case 4MB will be the default choice, if your board has 16MB you need to configure it directly in the `platformio.ini` file:
```
board_upload.maximum_size = 16777216
board_upload.flash_size = 16MB
```
