### ISSUE TITLE
Cannot find board esp-wroom-32

### ISSUE THREAD

**Issue by Benedito821** [platformio/platform-espressif32#484]
Hello, I am trying to create a new project in vs code using platformio  for the board esp-wroom-32 but I can't find this board. How can I add it? I can only find esp-wroom-02

**Comment by ivankravets** [comment]
You can file a feature request at https://github.com/espressif/arduino-esp32/issues

**Comment by valeros** [comment]
You can safely use the `esp32dev` board as it's essentially a development kit from Espressif based on `esp-wroom-02`.

**Comment by Benedito821** [comment]
Thanks to everyone. It worked
