### ISSUE TITLE
TTGO T-Beam board build failed with v4.2 framework-arduinoespressif32

### ISSUE THREAD

**Issue by ddv2005** [platformio/platform-espressif32#488]
Hello,

In version 4.2 framework-arduinoespressif32 TTGO T-Beam board variant was renamed from t-beam to tbeam and failed to build because of missing pins_arduino.h .

**Comment by valeros** [comment]
Just adjust the board variant directly in your `platformio.ini`:
```ini
board_build.variant = tbeam
```
