### ISSUE TITLE
Looking for example of BLE server

### ISSUE THREAD

**Issue by Benedito821** [platformio/platform-espressif32#490]
Hello! Is there an example of BLE server/client for platformio-espressif32 ? I found the espidf-ble-eddystone example but it seems to be BLE client, besides that it seems not working(it starts scanning and never stops).

**Comment by Benedito821** [comment]
@valeros could you please give  a hint if possible? I think it is not a wide question

**Comment by valeros** [comment]
Hi @Benedito821 ! This repository is not the right place to ask such questions, but you can take a look at [these examples](https://github.com/espressif/esp-idf/tree/release/v4.2/examples/bluetooth/esp_hid_host).
