### ISSUE TITLE
Variants_dir

### ISSUE THREAD

**Issue by enrico1036** [platformio/platform-espressif32#500]
Please add support to variable variants_dir like you can do in framework-arduinoststm32.
It is useful to define a custom directory where to search for the variant you specify in board.json, if you want to create your custom board and customize also pin definition or any files variant related.

**Comment by valeros** [comment]
Hi @enrico1036 ! It's has been already implemented some time ago, so something like this should work:
```ini
[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32dev
board_build.variants_dir = custom_variants
board_build.variant = esp32dev-custom
```
