### ISSUE TITLE
Update framework-arduinoespressif32 package with hotfixes

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-espressif32#508]
After the release of the 1.0.5 Arduino-ESP32 core, a few important bugfixes have been made which also affect their usage in PlatformIO ([refer commit history](https://github.com/espressif/arduino-esp32/commits/master)). 

1. Creating a project with `board = firebeetle32` results in total compilation failure because of an error in the C++ code regarding duplicate pin definitions.  [Reported by user here](https://community.platformio.org/t/firebeetle-compiling/19758) and fixed in https://github.com/espressif/arduino-esp32/commit/6e7cc5210dd210603f4e49cf677ccfa8e055b531
2. 3 seperate users have reported seeing warnings stemming from the `c_cpp_properties.json` referencing a non-existing folder, `tools/sdk/include/nimbus`, in the Arduino core ([See reports](https://community.platformio.org/t/esp32-3-1-0-missing-files/19696)).  Fixed by my PR 2 days ago in [here](https://github.com/espressif/arduino-esp32/pull/4891). 

Thus I think it makes sense to repackage the Arduino-ESP32 core with these bugfixes -- I'm not sure if the Arduino core will release a 1.0.6 version for that or if they'll take longer.

**Comment by valeros** [comment]
Thanks for reporting, fixed directly in the framework package.

**Comment by maxgerhardt** [comment]
@valeros, a performance degradation was noted in https://community.platformio.org/t/very-bad-performance-if-i-compile-the-example-for-esp32-cam/19730/10?u=maxgerhardt 

>When I compile the example in Arduino I get around 15 fps from the camera.
If I import it into Platformio I get 0.2 fps

for which the PR https://github.com/espressif/arduino-esp32/pull/4911 is a fix. So I think a re-release is noted again. 

**But** it's also reported that other basic functionality like `String::replace()` is broken (https://github.com/espressif/arduino-esp32/issues/4920) so it seems like a rollercoast ride right now. Maybe you can just update the package with the PR from above to fix the performance regression.

**Comment by maxgerhardt** [comment]
Then maybe the user had an older version of the framework-arduinoespressif32 package that caused this, hm.

**Comment by me-no-dev** [comment]
@maxgerhardt the new version 1.0.6 will be released soon and will include the fixes. @valeros do I need to let you know?

**Comment by valeros** [comment]
@me-no-dev Would be great.

**Comment by me-no-dev** [comment]
@valeros 1.0.6 is out :)
