### ISSUE TITLE
SOLVED: After last update platform = espressif32_stage is not working anymore

### ISSUE THREAD

**Issue by beegee-tokyo** [platformio/platform-espressif32#53]
# SOLUTION

Please use 
```ini
[env:..]
platform = https://github.com/platformio/platform-espressif32.git#feature/stage
...
```

------

After the last update, if I have `platform = espressif32_stage` in my platformio.ini file I get the following error:
```
platformio run
[11/26/17 18:56:39] Processing esp32dev (build_flags: -O0; lib_deps: 1671; platform: espressif32_stage; board: esp32dev; framework: arduino; lib_ext
ra_dirs: B:\Projects\ESP32\ESP32Lib; upload_port: 192.168.0.106)
 
PlatformManager: Installing espressif32_stage
Error: Detected unknown package 'espressif32_stage'
```

`platform = https://github.com/platformio/platform-espressif32.git#feature/stage`
works as expected. 
Is this the expected behaviour???

**Comment by ivankravets** [comment]
Yes, that is normal. We dropped support for `espressif32_stage` to avoid an issue with LIbrary Dependency Finder which compares libraries for platform compatibility. As result, if library as compatible with `espressif32` it was not compatible with `espressif32_stage`.

**Comment by beegee-tokyo** [comment]
Thanks for explaining.
