### ISSUE TITLE
Wrong board used for compiling

### ISSUE THREAD

**Issue by yeckel** [platformio/platform-espressif32#541]
I'm using:
```    [env:ttgo]
    platform_packages = framework-arduinoespressif32 @ https://github.com/marcovannoord/arduino-esp32.git#idf-release/v4.0
    platform = espressif32
    framework = espidf, arduino
    board = ttgo-lora32-v2
    build_flags = 
            -D ESP32=1
            -D ARDUINO=200
    monitor_speed = 115200
    monitor_filters = esp32_exception_decoder
```

As config, however the build process chooses **/home/libor/.platformio/packages/framework-arduinoespressif32-src-a8a830ef46fb935b080bfdf62a3092dd/variants/esp32/pins_arduino.h** to include.

not what I would expect: **/home/libor/.platformio/packages/framework-arduinoespressif32-src-a8a830ef46fb935b080bfdf62a3092dd/variants/ttgo-lora32-v2/pins_arduino.h**

How to force platformio to use a proper board header? With **framework = arduino** it's working fine.

Part of the build output:
```
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/ttgo-lora32-v2.html
PLATFORM: Espressif 32 (3.2.0+sha.b9530d3) (git+https://github.com/platformio/platform-espressif32.git) > TTGO LoRa32-OLED V2
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
``` 
Also, the board definition is read properly, "just" the ```#include "pins_arduino.h"``` uses wrong file.

**Comment by valeros** [comment]
Hi @yeckel ! Unfortunately, the `ESP32` value is hardcoded as the variant in the `CMakeLists.txt` https://github.com/espressif/arduino-esp32/blob/master/CMakeLists.txt#L176, so you probably need to edit that file manually.

**Comment by yeckel** [comment]
I see, and it's not going to be fixed. Maybe a warning somewhere? When the parameter `board =` is used? I'm symlinking the file...
