### ISSUE TITLE
PlatformIo not working correctly with ESP32 through debbager (esp-prog, jlink etc ) 

### ISSUE THREAD

**Issue by hexffffffff** [platformio/platform-espressif32#548]
Problem essence:
(all problem arise when using esp-prog, jlink etc, it works fine only with comport)

If you use ESP with flash more 4MB after upload program not work (reboots all the time)
No work correctly select flash mode (qio, dio , flash frequency, etc)
No work Upload FileSystem image (reboots all the time after upload)
No work debugging (reboots all the time after upload)
In fact, we can say that platformIO does not work with ESP!!!
I found the cause of the problem:
The fact ESP32 to download programs through the com port, it is used esptool. But esptool does not load the bootloader directly, it changes the binary “on the fly” by substituting the necessary values into it. But for upload platformIo used OpenOCD (esp-prog, jlink etc). It changes nothing in bootloader.bin and writes it “as is”. Because of this, the wrong bootloader gets into the esp32 flash.

I see that this problem has not been solved for more than a year!

**Comment by dumarjo** [comment]
Hi,

I think this is exactly the same problem that I have and other too. Look here 

https://community.platformio.org/t/bootloop-when-trying-to-debug-esp32-with-custom-partitions-scheme-on-arduino-framework/17282/11
