### ISSUE TITLE
In template: no matching function for call to 'operator new'

### ISSUE THREAD

**Issue by lfuelling** [platformio/platform-espressif32#552]
Hi, 

I'm currently experiencing a very confusing bug. 
It's about the warning/error "`In template: no matching function for call to 'operator new'`" which is shown in CLion (but not visible in VSCode) when implementing a WebServer `.on` lambda (or when passing a function handle).

When compiling (regardless of CLion or VSCode), the code compiles and runs. (The crash I originally described was caused by something else.)

The warning/error in CLion has the following trace:
```
~/.platformio/packages/toolchain-xtensa32@2.50200.97/xtensa-esp32-elf/include/c++/5.2.0 /functional:2258:22
~/.platformio/packages/toolchain-xtensa32@2.50200.97/xtensa-esp32-elf/include/c++/5.2.0 /functional:1758:7
```

## Steps to reproduce
1. Install PlatformIO for CLion
2. Create a new ESP32 project with Arduino Framework
3. Paste the following code into `main.cpp`:

```c++
#include <Arduino.h>
#include <WebServer.h>

WebServer server(80);

void setup() {
    server.on("/", HTTP_GET, [](){
        
    });
}

void loop() {
}
```

This will cause the left parenthese (7:30) to be marked red with the above error message linking to the `functional` file in `toolchain-xtensa32`.

This also happens with other libraries instead of the Arduino `WebServer.h` (for example [ESP Async WebServer](https://platformio.org/lib/show/306/ESP%20Async%20WebServer)) so I suspect the bug is in the platform code.

**Comment by valeros** [comment]
Hi @lfuelling ! I'm not completely sure it has something to do with PlatformIO itself. It seems to be a CLion's Intellisense quirk as the code you attached looks perfectly valid  (VSCode also doesn't complain about it). Anyway, it's either a framework issue (then you'd better open an issue here https://github.com/espressif/arduino-esp32) or a CLion bug (then it might be a good idea to ping the CLion team here https://youtrack.jetbrains.com/issues/CPP).
