### ISSUE TITLE
esp_http_client_perform - memory leak

### ISSUE THREAD

**Issue by silardg** [platformio/platform-espressif32#553]
I'm using a simple http request.
After using `esp_http_client_perform` in each request, it always leaks 300 bytes. 
After` esp_http_client_perform` I'm always executing `esp_http_client_cleanup`, but still leaking.

**Comment by valeros** [comment]
Hi @silardg ! It seems that the problem is in the framework itself and has nothing to do with PlatformIO, so please forward your issue to https://github.com/espressif/esp-idf
