### ISSUE TITLE
Why is the examples so poor

### ISSUE THREAD

**Issue by daverathbone** [platformio/platform-espressif32#556]
Please stop adding any examples as none work except blink.
ESP with JTAG - ESP Wroom-32D PlatformIO many hours setting up to get GPIO working...
I rest my case.

**Comment by valeros** [comment]
Hi @daverathbone , could you please explain in more detail what's wrong exactly?

**Comment by valeros** [comment]
Closing as no further info provided. Feel free to reopen the issue if you're still experiencing the problem with the latest upstream version of the platform.
