### ISSUE TITLE
Incorrect IDF_VER in CMake from version.txt conflict

### ISSUE THREAD

**Issue by MauAbata** [platformio/platform-espressif32#558]
When building against esp-idf, the variable `IDF_VER` is set to the version of the `framework-espidf` package (in this case, `3.40001.200521`) instead of the actual version of esp-idf (`v4.xxx`).

Some CMakeList.txt files switch on this version info:

```cmake
IF (IDF_VER MATCHES "v4.")
idf_component_get_property(audio_board_lib audio_board COMPONENT_LIB)
set_property(TARGET ${audio_board_lib} APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${COMPONENT_LIB})

ELSEIF (IDF_VER MATCHES "v3.")
```

`IDF_VER` is set in `build.cmake` to either use `git describe` or `version.txt` [source](https://github.com/espressif/esp-idf/blob/1f54d17503ff17d830de75eed4eb47bc6a3aafc3/tools/cmake/build.cmake#L61-L64). 

Here, however, we write the version of the platformio package to that version.txt:
https://github.com/platformio/platform-espressif32/blob/b1a3c2853c150cc03580cffe7e3ad6f62077b037/builder/frameworks/espidf.py#L828-L832

There's a note about the generation of this file here: 
https://github.com/platformio/platform-espressif32/blob/b1a3c2853c150cc03580cffe7e3ad6f62077b037/builder/frameworks/espidf.py#L1012-L1015

Is version.txt required for platformio or could we set that to the proper esp-idf version?

**Comment by valeros** [comment]
Hi @MauAbata, thanks for bringing it up, should be fixed in the dev branch. The workflow with the `version.txt` is still the same, but the `IDF_VER variabl` now matches the original version of the ESP-IDF package.
