### ISSUE TITLE
Linking error: multiple definitions of app_main

### ISSUE THREAD

**Issue by ivorss** [platformio/platform-espressif32#559]
This issue was not fixed, so I am reopening it:
https://github.com/platformio/platform-espressif32/issues/164

The issue was closed without fixing it.

**Comment by valeros** [comment]
Hi @ivorss ! Please attach here your project configuration from the `platformio.ini` file.

**Comment by valeros** [comment]
Closing as no further info provided. Feel free to reopen the issue if you're still experiencing the problem with the latest upstream version of the platform.
