### ISSUE TITLE
How to enable LWIP_NETIF_LOOPBACK ?

### ISSUE THREAD

**Issue by vshymanskyy** [platformio/platform-espressif32#57]
Just a quick question here,
Is there any way (and if yes, how to) to enable `LWIP_NETIF_LOOPBACK` option when building my project?

**Comment by valeros** [comment]
Hi @vshymanskyy ! 
Have you tried to add `LWIP_NETIF_LOOPBACK` macro to your `platformio.ini`? Something like this:
```ini
build_flags = -DLWIP_NETIF_LOOPBACK=1
```

**Comment by vshymanskyy** [comment]
Thanks. Got it running. I just didn't notice it rebuilds LWIP during project build.
Resolved using your suggested method!
