### ISSUE TITLE
modbus example from esp-idf not working

### ISSUE THREAD

**Issue by silardg** [platformio/platform-espressif32#578]
I'm using the latest 3.3.0 and trying to run the esp-idf modbus slave and master example in serial mode. 
It is not working, but with esp-idf platform it is.

**Comment by valeros** [comment]
Hi @silardg ! What's the problem exactly?

**Comment by silardg** [comment]
Got it working, had to setup the pins, mode and characteristics. Used an arduino to make sure that my hardware is good.
