### ISSUE TITLE
Security status about wifi vulnerability: fragattacks

### ISSUE THREAD

**Issue by Rotzbua** [platformio/platform-espressif32#579]
## Description

The found information indicates a vulnerability, because espressif has not yet released idf v4.3.1 and platformio uses v4.3.

`Updated ESP-IDF to the latest stable 4.3 ` (https://github.com/platformio/platform-espressif32/releases/tag/v3.3.0)

It would be useful to keep the issue open until the fixed idf version is used by platformio.

## Reference

* Bug homepage: https://www.fragattacks.com/
* Bug report esp-idf: https://github.com/espressif/esp-idf/issues/7019

**Comment by valeros** [comment]
The ESP-IDF package has been updated to 4.3.2.
