### ISSUE TITLE
With v3.3.0 IDF 3.3.5-1 is used, but release notes mention ESP-IDF 4.3

### ISSUE THREAD

**Issue by TD-er** [platformio/platform-espressif32#580]
I just tried to update my project (ESPEasy) to use the latest espressif32 V3.3.0.
The reported SDK however states: ESP32 SDK v3.3.5-1-g85c43024c
This does seem to be the ESP IDF version as the exact string is mentioned in the IDF documentation for the 3.3.5 release.
But I would like to add support for ESP32-S2, and it seems that does need ESP-IDF 4.x

What has to be changed to get ESP-IDF 4.3?
I do use espressif/arduino-esp32 via PlatformIO.
The PIO config I use is in this PR: https://github.com/letscontrolit/ESPEasy/pull/3699

**Comment by valeros** [comment]
Hi @TD-er ! The latest stable Arduino for ESP32 is based on ESP-IDF v3.3.5. Although the Arduino framework uses ESP-IDF for the low-level implementation, they are still two different frameworks  that can be used independently.  The v4.3 you saw in the release notes only applies to projects that uses standalone ESP-IDF. 

FYI, there is a way to use the Arduino core that supports ESP32-S2 (see https://github.com/platformio/platform-espressif32/pull/483)
