### ISSUE TITLE
New project code blank

### ISSUE THREAD

**Issue by Deepblue1996** [platformio/platform-espressif32#583]
I create a new project code blank
![QQ截图20210710174619](https://user-images.githubusercontent.com/16926380/125158944-c8865680-e1a6-11eb-90ad-64689f1814e7.png)

**Comment by Deepblue1996** [comment]
The project looks like this
![QQ截图20210710174510](https://user-images.githubusercontent.com/16926380/125158961-e9e74280-e1a6-11eb-9869-a7a52f539ba3.png)

**Comment by Deepblue1996** [comment]
Change it to JLink and you can download it
![QQ截图20210710174523](https://user-images.githubusercontent.com/16926380/125158980-0daa8880-e1a7-11eb-8ec5-c1a11960d7d2.png)

**Comment by Deepblue1996** [comment]
But if I add a header file, I get an error, so how do I add my own code
![QQ截图20210710174918](https://user-images.githubusercontent.com/16926380/125159004-36cb1900-e1a7-11eb-9747-d4bc67c46270.png)

**Comment by valeros** [comment]
Hi @Deepblue1996 ! At the moment the integration with CLion doesn't support ESP-IDF, see https://docs.platformio.org/en/latest/integration/ide/clion.html#clion-with-esp-idf
