### ISSUE TITLE
Add support ESP32-S2 Arduino Framework

### ISSUE THREAD

**Issue by jonesfu** [platformio/platform-espressif32#585]
For current config, it will pop up error message when choice board esp32-s2-saola-1 with arduino framework.
PLATFORM: Espressif 32 (3.2.0) > Espressif ESP32-S2-Saola-1
HARDWARE: ESP32S2 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
Error: This board doesn't support arduino framework!

After I change two point, I can build esp32-s2 with arduino framwork:
1. change framework from ESP-IDF to arduino .platformio\platforms\espressif32\boards\esp32-s2-saola-1.json
2. update .platformio\packages\framework-arduinoespressif32 to newest

So, could you please help to support ESP32-S2 arduino build environment.

**Comment by valeros** [comment]
Hi @jonesfu ! There is no stable version of the Arduino framework that supports ESP32-S2, although it's possible to use the upstream version, see https://github.com/platformio/platform-espressif32/pull/483
