### ISSUE TITLE
Building on remote server and flashing controller locally

### ISSUE THREAD

**Issue by silardg** [platformio/platform-espressif32#595]
Hi!
I want to build my platformio project on my much more powerful server, rather than my laptop.
Of course, the controller I want to flash is always with me or can be hooked up to a raspberry pi.

Has anyone done something like this? Installing platformio on a Linux server is not the hard part, but what is the best way to combine the building with the flashing. 
The simplest idea is to have an SNTP transfer of the .bin file comes to my mind as a solution after which a script will flash it to the controller. 

Any ideas or suggestions?

**Comment by valeros** [comment]
Take a look at [PlatformIO Remote](https://docs.platformio.org/en/latest/plus/pio-remote.html).
