### ISSUE TITLE
Heltec not up to date

### ISSUE THREAD

**Issue by altoidaddict** [platformio/platform-espressif32#600]
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/releases/download/0.0.5/package_heltec_esp32_index.json

The above is the correct board for the heltec esp32 wifi kit.  Without this anything that references analogSetCycles or analogSetSamples wont compile.

**Comment by valeros** [comment]
This repository uses the official Arduino core for ESP32 https://github.com/espressif/arduino-esp32
