### ISSUE TITLE
How to use Arduino built external library with idf espressif firmware in vs code?

### ISSUE THREAD

**Issue by Zaki23madrid** [platformio/platform-espressif32#607]
Hi,
while i am trying to use an already installed library on platformio tool in vs code with idf espressif firmware, i got Arduino.h not recognized, is there any solution for that?

**Comment by valeros** [comment]
Hi @Zaki23madrid ! ESP-IDF and Arduino are two different frameworks, so you cannot use libraries meant for Arduino with ESP-IDF.  The only viable way is to use Arduino as a ESP-IDF component.

**Comment by Zaki23madrid** [comment]
If i use Arduino as a component, i got thousand of errors.... It doesn't work...
