### ISSUE TITLE
Custom ESP-IDF Bootloader

### ISSUE THREAD

**Issue by fbucafusco** [platformio/platform-espressif32#613]
Hi!
I was researching a little bit in order to change the bootloader that comes within the espressif framework, for other with some others behaviors in comparison with the “stardard” one.
My idea is to build the pio project and in that process, pio uses my code (so the final .bin is ready to deploy).
I’ve red [1] that placing the source from the bootloader within components folder locally to my project, will work so I've copied the bootloader folder from the original espidf repo to the projects components folder, but platformio is ignoring it.
Is it necesary to place some extra configuration within platformio.ini file? Perhaps it is necessary to touch CMakeLists.txt file in my project as well. 

[1] [Espressif IoT Development Framework — PlatformIO latest documentation](https://docs.platformio.org/en/latest/frameworks/espidf.html?highlight=component#esp-idf-components)

**Comment by valeros** [comment]
HI @fbucafusco ! Copying that bootloader folder doesn't seems like a good idea to me. I'm not sure whether you've seen this [example](https://github.com/espressif/esp-idf/tree/master/examples/custom_bootloader/bootloader_override) but it's a good starting point that shows how to override the bootloader. Please keep in mind that even though PlatformIO uses the internal ESP-IDF build system as much as possible, there are several edge cases in the current integration that requires some fine-tuning, so I cannot guarantee it will work out of the box with the PlatformIO.

**Comment by fbucafusco** [comment]
Hi! Thanks for the response! 
I've already checked the example you pointed out. The thing is that the source at bootloader_components is never compiled at all. So modifying it makes no sense. Somhow the build system do not take files from that folder. 
Let ignore PlatformIO for a moment. 
Using just the ESP-IDF (copmpiling from the vscode extension) and reading [this](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/bootloader.html#custom-bootloader) I would expect that copying the folder, as mentioned in the first link i've posted, would work, but doesn't. Perhaps I should post this within the espidf repo as an issue. :/

**Comment by TalSomech** [comment]
Hi , is there a solution to this on how we can override the bootloader?

**Comment by TalSomech** [comment]
@Jason2866  actually im using a custom bootloader which someone else wrote and right now i want to move the entire project to use platformio because its more stable so i havent tried to use it yet with platformio and since im new to platformio i havent gotten to how to integrate the custom bootloader files into the project ,is it something in the ini file options? the same way you use custom partition file ?

**Comment by Jason2866** [comment]
@TalSomech afaik there is no easy way to include a precompiled custom bootloader.
