### ISSUE TITLE
Store BLE Mesh Node configuration persistently leads to an error

### ISSUE THREAD

**Issue by bodyanych** [platformio/platform-espressif32#628]
Hello,

I want an ESP32 to be able to store provisioning data after power loss, so a device could be connected and not provisioned after power on.
When Component config --> Ble mesh Support --> **Store BLE Mesh Node configuration persistently in ON** -> device could not be provisioned (seen by nRF mesh app) anymore (esp boot log with the error attached).
When Component config --> Ble mesh Support --> **Store BLE Mesh Node configuration persistently in OFF** -> device could be provisioned, but should be provisioned again after reboot/power loss.

SDK config files are attached.

What could be the problem?
How could I keep the ability to provision the device once, and then reconnect to it?

I am working in VS code / Platformio.
**platformio.ini** file:

```
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = espidf
board_build.partitions = partitions.csv
build_flags = -std=c++17
build_unflags = -std=c++11
monitor_speed = 115200
lib_ldf_mode = chain
monitor_flags = 
	--raw
upload_protocol = esptool
```

This is from **c_pp_propertioe.json** file:

```
"defines": [
                "_GNU_SOURCE",
                "IDF_VER=\"4.3.0\"",
                "ESP_PLATFORM",
                "PLATFORMIO=50200",
                "ARDUINO_ESP32_DEV",
                ""
            ],
            "cStandard": "c99",
            "cppStandard": "c++11",
            "compilerPath": "C:/Users/xxx/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc.exe",
            "compilerArgs": [
                "-mlongcalls"
                ""
            ]
```
![Componet config -- Ble mesh Support ](https://user-images.githubusercontent.com/29886479/133736025-31cfd2a4-d7fd-431c-97f6-86e8d1a15e40.png)
![ESP_boot](https://user-images.githubusercontent.com/29886479/133736028-28da6046-5c44-4e4b-aa6b-ebb20cd5a3eb.png)

[sdkconfig.zip](https://github.com/platformio/platform-espressif32/files/7183213/sdkconfig.zip)

**Comment by valeros** [comment]
Hi @bodyanych ! This repository is not the right place to ask generic questions about frameworks. You'd better ask for help in the official ESP-IDF repository https://github.com/espressif/esp-idf or even the ESP32 forum here https://www.esp32.com.
