### ISSUE TITLE
Add debug support for M5Stack Core2

### ISSUE THREAD

**Issue by Zokol** [platformio/platform-espressif32#629]
### Description of problem
Uploading code works fine, but I would need the debug-functionality.
This would greatly increase the usability of this platform, as it is quite packed with peripherals, so the codebase can easily get large and complex.

### Additional info
There is no direct interface for JTAG in Core2.
You will need to solder two wires, for TDI and TDO (GPIO 12 and GPIO 15). These pins are used for LCD and speaker IO.
TMS and TCK are already wired to the M-BUS-connector, and TDI/TDO pins can be wired to unused pins of the connector.

Few pics of the required mods:

![Photo 16 9 2021, 15 48 27](https://user-images.githubusercontent.com/1899518/133881787-5b191f20-1b2f-4e7b-802b-b90b4dc81869.jpg)
![Photo 16 9 2021, 15 48 47](https://user-images.githubusercontent.com/1899518/133881788-05d8bf75-3389-4f9c-85fb-5eeca8cea921.jpg)

**Comment by Jason2866** [comment]
Easy to solve. Just do your own boards.json defintion for your modified core2 device and place it in folder `boards` in the root of your platformio project.

**Comment by li3p** [comment]
Any updates on this thread?
