### ISSUE TITLE
Add suport to Franzininho WiFi (ESP32-S2) Board

### ISSUE THREAD

**Issue by FBSeletronica** [platformio/platform-espressif32#636]
Please add support for the Franzininho WiFi (ESP32-S2) Board

This board is already included in the Espressif Arduino v2.0 package: [link](https://github.com/espressif/arduino-esp32)

Board details: [link](https://github.com/Franzininho/Franzininho-WIFI)

Framework: 
Arduino 
ESP-IDF

**Comment by xmz0916** [comment]
Update strongly recommended
