### ISSUE TITLE
What version of ESP-IDF

### ISSUE THREAD

**Issue by 9a4gl** [platformio/platform-espressif32#64]
> Arduino-ESP32 used precompiled binaries from ESP-IDF

Where we can find what version of ESPIDF we use ? I am fighting with issues related to change baudrate on uart2, and I have found that https://github.com/espressif/esp-idf/commit/4052803e161ba06d1cae8d36bc66dde15b3fc8c7 should fix the issue. How can I know if this is in current release ?

**Comment by ivankravets** [comment]
We use stable ESP-IDF. The latest version is 2.1.1

![screen shot 2018-02-09 at 13 34 23](https://user-images.githubusercontent.com/1760209/36026140-75e029b8-0d9e-11e8-8726-d2c0a384a3e9.png)
