### ISSUE TITLE
WiFi.mode not returning status at boot

### ISSUE THREAD

**Issue by Ikity** [platformio/platform-espressif32#647]
During my use of esp8266 i was able to get last credentials and last esp mode via WiFi.SSID(),WiFi.psk(),WiFi.mode() now even if i set mode and credentials i got nothing at WiFi.SSID() and 0 at WiFi.mode, WiFi.psk() still returns last password. How can i get my last Wifi configs now, i know it stores somewhere since i can still reconnect via  WiFi.reconnect, but mode i have to provide every time

**Comment by valeros** [comment]
Hi @Ikity ! This repository is not the right place to ask generic questions about frameworks. You'd better ask for help in the official Arduino ESP32 repository https://github.com/espressif/arduino-esp32
