### ISSUE TITLE
BLE Reconnect

### ISSUE THREAD

**Issue by ipodsync** [platformio/platform-espressif32#658]
Between release 3.0.0 and 3.2 onward, BLE appears to have broke.  

You can connect to the BLE server, but after disconnecting, you cannot reconnect without restarting the device.

I am using the BLE_server example code as is and using PlatformIO

If I specify a version in the platformio.ini of 3.0.0 everything works, but anything newer does not
platform = espressif32@3.0.0

**Comment by doudar** [comment]
I'm noticing the same thing.

**Comment by valeros** [comment]
Should be fixed in the latest version of the development platform. Please reopen if the problem persists.

**Comment by demirschmid61** [comment]
Is this problem solved, i am facing this problem in 6.0.1 version.
