### ISSUE TITLE
debug_svd_path work only for PLATFORM_ROOT/misc/svd directory

### ISSUE THREAD

**Issue by ad7718** [platformio/platform-espressif32#660]
If I try to put a SVD file for example in project directory there is no path error in terminal, but svdPath string in launch.json is not generated.

**Comment by valeros** [comment]
You need to use the [debug_svd_path](https://docs.platformio.org/en/latest/projectconf/section_env_debug.html#debug-svd-path) option.

**Comment by ad7718** [comment]
I'm using it, and it doesn't work as said in title

**Comment by valeros** [comment]
Have you tried to specify absolute path to your svd file?

**Comment by ad7718** [comment]
Yes, same result, no error, but no svdPath string is generated in launch.json.
Forgot to say that I'm on Linux.
