### ISSUE TITLE
debugger don't start

### ISSUE THREAD

**Issue by MHz000** [platformio/platform-espressif32#663]
my configuration:
WIN10  PlatformIO: Core 5.2.0·Home 3.3.4
crashed with:
...
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Error: libusb_claim_interface() failed with LIBUSB_ERROR_NOT_SUPPORTED
Error: unable to open ftdi device with vid 0403, pid 6010, description '*', serial '*' at bus location '*'
Error: no device found
Error: unable to open ftdi device with vid 0403, pid 6014, description '*', serial '*' at bus location '*'
Assertion failed!
...
Zadig: Dual RS232-HS (Interface 0) Driver set to WinUSB (v6.11.7600.16385)

platformio.ini: 
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

Any suggestion what to do?
Thank-you!

**Comment by valeros** [comment]
This board doesn't have an integrated debug probe, so you need to explicitly configure what probe is connected via the [debug_tool](https://docs.platformio.org/en/latest/projectconf/section_env_debug.html#debug-tool) option.
