### ISSUE TITLE
Uable to run espidf on RPi4 ubuntu 64 bit

### ISSUE THREAD

**Issue by gadepall** [platformio/platform-espressif32#666]
Following is the error:

Error: Could not find the package with 'platformio/toolchain-esp32ulp @ ~1.22851.0' requirements for your system 'linux_aarch64'

**Comment by valeros** [comment]
Hi @gadepall ! Unfortunately, the ESP-IDF team doesn't provide ULP toolchain packages for [the ARM64 architecture](https://github.com/espressif/esp-idf/blob/master/tools/tools.json#L337-L363). Please forward your request for ARM64 support in the native ESP-IDF development environment and submit it to the https://github.com/espressif/esp-idf repository.
