### ISSUE TITLE
Could not find toolchain file toolchain-esp32-ulp.cmake - Wrong esp-idf in platform file?

### ISSUE THREAD

**Issue by Kampi** [platformio/platform-espressif32#667]
I use the following platform and frameworks to build a project that contains ULP code:

```
platform = espressif32
framework = espidf, arduino
```

PlatformIO use the following packages for this task:

```
 - framework-arduinoespressif32 0.0.0+sha.29fc584
 - framework-espidf 3.40001.200521 (4.0.1)
 - tool-cmake 3.16.4
 - tool-esptoolpy 1.30100.210531 (3.1.0)
 - tool-idf 1.0.1
 - tool-mconf 1.4060000.20190628 (406.0.0)
 - tool-ninja 1.9.0
 - toolchain-esp32ulp 1.22851.191205 (2.28.51)
 - toolchain-xtensa32 3.80200.200512 (8.2.0)
```

But the build process results in an error:

```
CMake Error at C:/Users/Danie/.platformio/packages/tool-cmake/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file:
  C:\Users\Danie\.platformio\packages\framework-espidf\components\ulp\cmake\toolchain-esp32-ulp.cmake
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)
 ```

The error comes from the ULP part of the project. The project compiles without issues after removing the ULP part. 

I have figured out that the installed `esp-idf` only contains a file `components\ulp\cmake\toolchain-ulp.cmake`. The project (including the ULP code) compiles successfully after renaming the file to `toolchain-esp32-ulp.cmake`.

I also checked the `ulp.py` build script and found this part in `generate_ulp_config`

```
        + os.path.join(
            FRAMEWORK_DIR,
            "components",
            "ulp",
            "cmake",
            "toolchain-%s-ulp.cmake" % idf_variant,
        ),
```

According to the `platform.json` PlatformIO I assume that PlatformIO should install version 4.3 first (I´m not sure about the notation for the version number).

```
    "framework-espidf": {
      "type": "framework",
      "optional": true,
      "owner": "platformio",
      "version": "~3.40300.0",
      "optionalVersions": ["~3.40001.0"]
    },
```

`v4.3` of the `esp-idf` uses the naming scheme for the ULP files (see [repo](https://github.com/espressif/esp-idf/tree/release/v4.3/components/ulp/cmake)) from the Python script.

I came up with the following questions:

- Why is PlatformIO installing `v4.0.1` when this should be the `optionalVersion`? 
- How can I force PlatformIO to install `v4.3` of the `esp-idf`?
- I´m right with the suggestion that the optional version number in the `platform.json` isn´t the right one for the used builder script? I think the minimum version should be `v.2`.

**Comment by Jason2866** [comment]
Try this. Arduino Core 2.0.2 and IDF 4.4
```
platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.2idf/platform-espressif32-2.0.2.zip
```
