### ISSUE TITLE
Guide to help keeping upto date with esp-idf

### ISSUE THREAD

**Issue by danielcrowley** [platformio/platform-espressif32#68]
Hey, 
Is it worth getting a guide going to help with the steps to keep upto date with the esp-idf?
I'm guessing it's not a fully repeatable process each time, but the list of things to change must be 80% the same each time? Then a small number of gotchas.

Is this the case or am I totally wrong?
If so, if anyone has help with getting 2.1 working, and can add some notes, then I'd be happy to give a go at moving across to 3.0

**Comment by valeros** [comment]
Closing as the latest espressif32 platform uses native CMake build system as the source of build configuration https://docs.platformio.org/en/latest/frameworks/espidf.html#project-structure
