### ISSUE TITLE
Error SD VFSImpl::open was called at PC 0x400871b7 on core 1

### ISSUE THREAD

**Issue by ortegafull87** [platformio/platform-espressif32#686]
I'm usin SD.h library and after some minuetes after begin loop() function, The esp32 abort with de error "was called at PC 0x400871b7 on core 1" my code it does save each 250ms a line in log file.  I noticed that this started to happen after updating to the version Espressif 32 (3.4.0)

The log is next:

`abort() was called at PC 0x400871b7 on core 1

ELF file SHA256: 0000000000000000

Backtrace: 0x40088f50:0x3ffb1bc0 0x400891cd:0x3ffb1be0 0x400871b7:0x3ffb1c00 0x400872d1:0x3ffb1c20 0x4000bde5:0x3ffb1c40 0x40001ef0:0x3ffb1c60 0x40145f63:0x3ffb1c80 0x40146005:0x3ffb1cb0 0x401757b5:0x3ffb1cd0 0x401760b3:0x3ffb1cf0 0x400d2e19:0x3ffb1d70 0x400d2eb8:0x3ffb1da0 0x400d7482:0x3ffb1dc0 0x400d23ee:0x3ffb1e30 0x400dc1c9:0x3ffb1fb0 0x4008a1de:0x3ffb1fd0
  #0  0x40088f50:0x3ffb1bc0 in invoke_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715
  #1  0x400891cd:0x3ffb1be0 in abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715
  #2  0x400871b7:0x3ffb1c00 in lock_init_generic at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/locks.c:81
  #3  0x400872d1:0x3ffb1c20 in _lock_init_recursive at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/locks.c:95
  #4  0x4000bde5:0x3ffb1c40 in ?? ??:0
  #5  0x40001ef0:0x3ffb1c60 in ?? ??:0
  #6  0x40145f63:0x3ffb1c80 in _fopen_r at /Users/ivan/e/newlib_xtensa-2.2.0-bin/newlib_xtensa-2.2.0/xtensa-esp32-elf/newlib/libc/stdio/../../../.././newlib/libc/stdio/fopen.c:138
  #7  0x40146005:0x3ffb1cb0 in fopen at /Users/ivan/e/newlib_xtensa-2.2.0-bin/newlib_xtensa-2.2.0/xtensa-esp32-elf/newlib/libc/stdio/../../../.././newlib/libc/stdio/fopen.c:181
  #8  0x401757b5:0x3ffb1cd0 in VFSFileImpl::VFSFileImpl(VFSImpl*, char const*, char const*) at /Users/victorortega/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/vfs_api.cpp:241
  #9  0x401760b3:0x3ffb1cf0 in void __gnu_cxx::new_allocator<VFSFileImpl>::construct<VFSFileImpl, VFSImpl*, char const*&, char const*&>(VFSFileImpl*, VFSImpl*&&, char const*&, char const*&) at /Users/victorortega/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/ext/new_allocator.h:120
      (inlined by) std::enable_if<std::__and_<std::allocator_traits<std::allocator<VFSFileImpl> >::__construct_helper<VFSFileImpl, VFSImpl*, char const*&, char const*&>::type>::value, void>::type std::allocator_traits<std::allocator<VFSFileImpl> >::_S_construct<VFSFileImpl, VFSImpl*, char const*&, char const*&>(std::allocator<VFSFileImpl>&, VFSFileImpl*, VFSImpl*&&, char const*&, char const*&) at /Users/victorortega/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/alloc_traits.h:256
      (inlined by) decltype (_S_construct({parm#1}, {parm#2}, (forward<VFSImpl*>)({parm#3}), (forward<char const*&>)({parm#3}), (forward<char const*&>)({parm#3}))) std::allocator_traits<std::allocator<VFSFileImpl> >::construct<VFSFileImpl, VFSImpl*, char const*&, char const*&>(std::allocator<VFSFileImpl>&, VFSFileImpl*, VFSImpl*&&, char const*&, char const*&) at /Users/victorortega/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/alloc_traits.h:402
      (inlined by) std::__shared_ptr<VFSFileImpl, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<VFSFileImpl>, VFSImpl*, char const*&, char const*&>(std::_Sp_make_shared_tag, std::allocator<VFSFileImpl> const&, VFSImpl*&&, char const*&, char const*&) at /Users/victorortega/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/shared_ptr_base.h:1129
      (inlined by) std::shared_ptr<VFSFileImpl>::shared_ptr<std::allocator<VFSFileImpl>, VFSImpl*, char const*&, char const*&>(std::_Sp_make_shared_tag, std::allocator<VFSFileImpl> const&, VFSImpl*&&, char const*&, char const*&) at /Users/victorortega/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/shared_ptr.h:319
      (inlined by) std::shared_ptr<VFSFileImpl> std::allocate_shared<VFSFileImpl, std::allocator<VFSFileImpl>, VFSImpl*, char const*&, char const*&>(std::allocator<VFSFileImpl> const&, VFSImpl*&&, char const*&, char const*&) at /Users/victorortega/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/shared_ptr.h:614
      (inlined by) std::shared_ptr<VFSFileImpl> std::make_shared<VFSFileImpl, VFSImpl*, char const*&, char const*&>(VFSImpl*&&, char const*&, char const*&) at /Users/victorortega/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/shared_ptr.h:630
      (inlined by) VFSImpl::open(char const*, char const*) at /Users/victorortega/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/
  #10 0x400d2e19:0x3ffb1d70 in fs::FS::open(char const*, char const*) at /Users/victorortega/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/FS.cpp:258
  #11 0x400d2eb8:0x3ffb1da0 in fs::FS::open(String const&, char const*) at /Users/victorortega/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/FS.cpp:258
  #12 0x400d7482:0x3ffb1dc0 in SDUtil::appendInFile(String) at lib/SDUtil/SDUtil.cpp:130
  #13 0x400d23ee:0x3ffb1e30 in loop() at src/main.cpp:453 (discriminator 1)
  #14 0x400dc1c9:0x3ffb1fb0 in loopTask(void*) at /Users/victorortega/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:23
  #15 0x4008a1de:0x3ffb1fd0 in vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)`

mi caller code is next:

`void SDUtil::appendInFile(const String text)
{
    time_t t = now();
    bool isNew = false;
    if(!SD.exists(DEFAULT_LOG_PATH + SF(LOG_FILE_NAME_FORMAT, year(t), month(t), day(t)))){
        isNew = true;
    }
    File dataFile = SD.open(DEFAULT_LOG_PATH + SF(LOG_FILE_NAME_FORMAT, year(t), month(t), day(t)), FILE_APPEND);
    if (dataFile)
    {
        if (isNew)
        {
            SLOG.info("Writting Header");
            dataFile.println(SF(HEADERS_FILE));
        }
        dataFile.print(text);
        dataFile.close();
    }
}`

I'am using platformio on macOS Bigsur

**Comment by valeros** [comment]
Should be fixed in the latest version of the development platform that uses Arduino core v2.0.2, please update your packages via `pio update `. Feel free to reopen the issue if the problem persists.
