### ISSUE TITLE
add option for xRingbufferCreateStatic to use PSRAM

### ISSUE THREAD

**Issue by bhupiister** [platformio/platform-espressif32#688]
Want to create a static ring buffer to use PSRAM on esp32. With the inbuilt FreeRTOS, there is no option to create xRingbufferCreateStatic.
```
  //Allocate memory for ring buffer data structure
  StaticRingbuffer_t *buffer_struct = (StaticRingbuffer_t *)heap_caps_malloc(sizeof(StaticRingbuffer_t), MALLOC_CAP_SPIRAM);
  //Allocate memory for ring buffer's data storage area
  uint8_t *buffer_storage = (uint8_t *)heap_caps_malloc(sizeof(uint8_t) * buffSizeInBytes, MALLOC_CAP_SPIRAM);
  //Set your buffer type
  RingbufferType_t buffer_type = RINGBUF_TYPE_NOSPLIT;
  buf_handle = xRingbufferCreateStatic(buffSizeInBytes, buffer_type, buffer_storage, buffer_struct);
```

**Comment by valeros** [comment]
Hi @bhupiister , This repository is not the right place to ask such generic questions,  please forward it to the official ESP-IDF repository https://github.com/espressif/esp-idf

**Comment by daz** [comment]
Is there an updated way to do this? The `feature/arduino-upstream` branch is currently 2 years behind the dev branch, but I haven’t found any other way to get of the error:

` error: implicit declaration of function 'xQueueCreateStatic';`

**Comment by daz** [comment]
My fix was in `FreeRTOSConfig.h` specifically setting`configSUPPORT_STATIC_ALLOCATION`

**Comment by bhupiister** [comment]
@daz you must be using esp idf to make changes to freertos.
