### ISSUE TITLE
Please update IDF to stable v4.3.2

### ISSUE THREAD

**Issue by FaBjE** [platformio/platform-espressif32#704]
Please upgrade to the latest stable ESP-IDF v4.3.2 

It contains features and fixes for the ESP32-C3 (including console over JTAG UART support)

As a temporal workaround I have forked the ESP-IDF and added the package.json file.
I have found no issues so far.

```
[env:esp32-c3]
platform = espressif32
framework = espidf
platform_packages =
  ; use upstream forked ESP-IDF to use V4.3.2 until official platformIO support
  framework-espidf@https://github.com/FaBjE/esp-idf#v4.3.2-platformio
```

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-espressif32/commit/fcde8613031837b917fc881d22ba38853a3ad544
