### ISSUE TITLE
Toolchain broken on Windows, please update to esp-2021r2-patch2

### ISSUE THREAD

**Issue by FaBjE** [platformio/platform-espressif32#705]
The included toolchain esp-2021r2 contains a "bug" (missing dll's) that cause it not to run (properly) on windows.
Especially the GDB server of the RISCV architecture will exit without an error message.
Causing the PlatformIO debugger to not start without any error message.

Espressif has fixed this.  https://github.com/espressif/crosstool-NG/releases/
Please update the toolchain to: esp-2021r2-patch2

**Comment by valeros** [comment]
Hi @FaBjE ! Do you use the upstream version of the Espressif32 platform? The Espressif team maintains their own packages within the PlatformIO ecosystem (e.g. https://registry.platformio.org/tools/espressif/toolchain-xtensa-esp32/versions). The 2021r2 version was officially released in October and they pushed updated toolchains to PlatformIO Registry in November, so I guess the packages should contain all required patches.

**Comment by FaBjE** [comment]
Hi @valeros 

Yes, sorry I forgot to mention that I use https://github.com/platformio/platform-espressif32/commit/fcde8613031837b917fc881d22ba38853a3ad544 with the IDF upgraded v4.3.2 I requested in #704

I did a fresh "install" and and indeed got the esp-2021r2 version. 
This does not contain the patches that fixes the windows builds. the Linux toolchain works fine.

It makes sense in a way that they name the first release just "r2" and the patches "r2-patchX"
If you download the "r2" version from the [releases](https://github.com/espressif/crosstool-NG/releases/) page you get the version without patches.
My guess is that they didn't generate the PlatformIO packages for the patches.

**Comment by FaBjE** [comment]
@valeros 

Espressif updated/released the toolchain in the package repository.
I verified it using this config:

```
[env]
platform = https://github.com/platformio/platform-espressif32.git#fcde8613031837b917fc881d22ba38853a3ad544
framework = espidf
platform_packages =
  ; use upstream toolchain
  toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch2
  toolchain-xtensa-esp32s2 @ 8.4.0+2021r2-patch2
  toolchain-riscv32-esp @ 8.4.0+2021r2-patch2
```

It now works out of the box on windows and still works on Linux too.
Could you update the references in platform.json?
