### ISSUE TITLE
Select task to run

### ISSUE THREAD

**Issue by haberturdeur** [platformio/platform-espressif32#71]
Hi,
when I'm using PIO on VSCode on windows, when I try to build/upload It shows me "Select task to run" with three options: 
![bez nazvu](https://user-images.githubusercontent.com/30172420/36326356-18867e26-135b-11e8-834e-11b35e79e85a.png)

(and the build/upload won't start)

**Comment by ivankravets** [comment]
Please check your `platformio.ini`. Does it work if you type in VSCode terminal `pio run`?

**Comment by rob-lutrons** [comment]
I had this too. After comparing with a working project I noticed that the com port wasnt set
![image](https://user-images.githubusercontent.com/48070705/62762896-1b6aa700-ba82-11e9-92d0-80649d3f21bc.png)

Clicking on this opens a drop down at the top of the editor. Selecting a port solved my problem.

**Comment by ivankravets** [comment]
Please uninstall conflicted Arduino extension.
