### ISSUE TITLE
Add support for Wemos S2 Mini

### ISSUE THREAD

**Issue by jh-maker** [platformio/platform-espressif32#715]
Can it be possible to add support for Wemos S2 Mini?

**Comment by dvisser** [comment]
Board info can be found here

[https://www.wemos.cc/en/latest/s2/s2_mini.html](https://www.wemos.cc/en/latest/s2/s2_mini.html)

I would also love support for this board also please :-)

**Comment by colde** [comment]
Adding to that, i would also love support for the S2 Pico. It seems to work well in the Arduino IDE when using the "ESPS2 Native USB" board.

**Comment by dvisser** [comment]
I just submitted a PR #722 for the Wemos S2 Mini.

**Comment by Rotzbua** [comment]
@valeros Can be closed. Solved by #736

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-espressif32/pull/736
