### ISSUE TITLE
ESP32 DOIT DEVKIT V1 - 1MB flash size instead of 4MB

### ISSUE THREAD

**Issue by Sladerix** [platformio/platform-espressif32#719]
Hi everyone,
i've a big problem.

I can't upload the code to my ESP32 because it says i finished the flash memory... the problem is that it thinks is 1MB, but actually the board provides 4MB.

In the board manager (and project manager) PlatformIO says 4MB 
![Schermata 2022-02-03 alle 13 07 09](https://user-images.githubusercontent.com/6717214/152343415-d3c80c3a-dd71-4cff-bbfd-45dd04d9dd9a.png)

And also in the documentation:
![Schermata 2022-02-03 alle 13 33 27](https://user-images.githubusercontent.com/6717214/152343637-31ba8e27-e49d-4f11-9441-ac6b64d3948a.png)

**BUT** in the Inspect page it says 1MB:

![Schermata 2022-02-03 alle 13 35 42](https://user-images.githubusercontent.com/6717214/152344019-cc80e5a6-bd2d-499b-9e9c-9e936c9fdc3d.png)

and also in the terminal when i compile:

![Schermata 2022-02-03 alle 13 37 39](https://user-images.githubusercontent.com/6717214/152344221-a2e99ef6-4fc5-4aab-82c4-ff80dab8b069.png)

Thanks in advance

**Comment by valeros** [comment]
Hi @Sladerix ! Just use a bigger[partition table](https://docs.platformio.org/en/latest/platforms/espressif32.html#partition-tables), e.g.:
```ini
[env:esp32doit-devkit-v1]
platform = espressif32
framework = arduino
board = esp32doit-devkit-v1

board_build.partitions = no_ota.csv
```
