### ISSUE TITLE
BOARD_HAS_PSRAM affects boot time

### ISSUE THREAD

**Issue by ashald** [platformio/platform-espressif32#729]
I noticed that defining `BOARD_HAS_PSRAM` at compile time increases time to 1st log message from ~15ms to ~900ms (both hardware reset and deep sleep) on my ESP32-WROVER.
I suspected memtest but disabling it didn't make any difference.
Couldn't find any explanations about this - is it an expected behavior? What takes that time and if there is any control over it?

**Comment by Jason2866** [comment]
This is not related to platformio. It is a Arduino Esp32 related. https://github.com/espressif/arduino-esp32/commit/1bbe61ab6f96263ba138a065801ac889f81b1ce1

**Comment by ashald** [comment]
Thanks a lot!
