### ISSUE TITLE
c_cpp_properties.json should not have comments

### ISSUE THREAD

**Issue by cyberman54** [platformio/platform-espressif32#732]
The auto-generated file `c_cpp_properties.json` shows a comment at the top:
```
//
// !!! WARNING !!! AUTO-GENERATED FILE!
// PLEASE DO NOT MODIFY IT AND USE "platformio.ini":
// https://docs.platformio.org/page/projectconf/section_env_build.html#build-flags
//
```
But JSON is data only. Thus, VScode complains _"comments are not permitted in JSON"_ .

**Comment by ivankravets** [comment]
How to reproduce this issue? `c_cpp_properties.json` is not a generic JSON file, comments are allowed here. Do you use a custom JSON plugin that verifies files?

![Screen Shot 2022-02-21 at 17 55 36](https://user-images.githubusercontent.com/1760209/154989104-692448a2-c7d4-4890-95c3-2703a5b357a1.png)

**Comment by cyberman54** [comment]
Indeed it was a JSON plugin. Deinstalled it, now all fine. Sorry for wrong addressing this here. Closed.
