### ISSUE TITLE
Error Debug No source filename

### ISSUE THREAD

**Issue by esstampida** [platformio/platform-espressif32#733]
when I select an interrupt point the debug gives me an error that you do not exist the file “No source file named” the absolute address but the file exists
Add Console debug
´´´
Reading symbols from [c:\Users\oscar.lluch\OneDrive]() - Fundaci� Sant Hospital\Documentos\PlatformIO\Projects\prueba_debug\.pio\build\esp_wroom\firmware.elf...
done.
PlatformIO Unified Debugger -> [https://bit.ly/pio-debug]()
PlatformIO: debug_tool = esp-prog
PlatformIO: Initializing remote target...
Open On-Chip Debugger  v0.10.0-esp32-20210721 (2021-07-21-13:35)
Licensed under GNU GPL v2
For bug reports, read
	[http://openocd.org/doc/doxygen/bugs.html]()
adapter speed: 5000 kHz

WARNING: boards/esp-wroom-32.cfg is deprecated, and may be removed in a future release.
adapter speed: 500 kHz

add Error

```
no source file named (Absolute PATH)

**Comment by valeros** [comment]
Hi @esstampida! Could you please provide a minimal project to reproduce the issue?
