### ISSUE TITLE
Can't compile Arduino SPIFFS example sketch

### ISSUE THREAD

**Issue by djObsidian** [platformio/platform-espressif32#734]
I am trying to compile and run this example
https://github.com/espressif/arduino-esp32/blob/master/libraries/SPIFFS/examples/SPIFFS_Test/SPIFFS_Test.ino
But i'm getting following compilation error
```
src\main.cpp: In function 'void listDir(fs::FS&, const char*, uint8_t)':
src\main.cpp:30:34: error: 'class fs::File' has no member named 'path'
                 listDir(fs, file.path(), levels -1);
                                  ^
*** [.pio\build\esp32dev\src\main.cpp.o] Error 1
============================================================================================================================== [FAILED] Took 2.96 seconds ==============================================================================================================================
```
Upon opening FS.h i see no `path()` method, which is weird, because it is present in latest esp32 arduino core
https://github.com/espressif/arduino-esp32/blob/2884215f8519a236c4cebb71bdc72ebbe69942bf/libraries/FS/src/FS.h#L76

platformio.ini is configured following way
```
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
```

I have 3.5.0 version of Espressif 32 installed

**Comment by Jason2866** [comment]
You can not compile this example since it needs Arduino core 2.0.x
Platformio 3.5.0 is Arduino core 1.0.6

**Comment by praphullorahi** [comment]
getting error for espressif 3.5.0 but same program compiled successfully for 3.3.0 , kindly me to resolve it plz....


Linking .pio\build\bluesky\firmware.elf
c:/users/ultimate/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\bluesky\src\provisioning.o:(.literal.provisioningStart+0x0): undefined reference to `wifi_prov_scheme_ble'
c:/users/ultimate/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\bluesky\src\provisioning.o:(.literal.provisioningStart+0x4): undefined reference to `wifi_prov_scheme_ble_event_cb_free_btdm'
c:/users/ultimate/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\bluesky\src\provisioning.o:(.literal.provisioningStart+0x34): undefined reference to `wifi_prov_scheme_ble_set_service_uuid'
c:/users/ultimate/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\bluesky\src\provisioning.o: in function `provisioningStart':
C:\Users\Ultimate\Desktop\bluesky-firmware/src/provisioning.c:122: undefined reference to `wifi_prov_scheme_ble_set_service_uuid'
collect2.exe: error: ld returned 1 exit status

**Comment by Jason2866** [comment]
@praphullorahi  Sorry your problem has nothing to do with this issue nor is it platformio related. There are forums to ask for coding help.

**Comment by valeros** [comment]
Hi @praphullorahi, please forward your question https://community.platformio.org/
