### ISSUE TITLE
Store data in a relative firmware address

### ISSUE THREAD

**Issue by romocitto88** [platformio/platform-espressif32#738]
Hello everyone,
I need to store read-only data (100kbyte) in a relative firmware address of the file, to be able to update both firmware and data with a single file. Also I must have the ability to update via OTA with the double partition.

I haven’t found any help documentation. Can anyone point me to a link or give me a suggestion?

Thanks in advance.

**Comment by valeros** [comment]
Hi @romocitto88 ! This repository is not the right place to ask such generic questions not related to possible problems with the PlatformIO development platform for ESP32, please forward it to to https://gitter.im/espressif/arduino-esp32 or https://community.platformio.org/
