### ISSUE TITLE
espidf 2.211.0: /components/heap/ missing

### ISSUE THREAD

**Issue by mutex36** [platformio/platform-espressif32#74]
So espidf.py adds the `heap` folder:
`join(FRAMEWORK_DIR, "components", "heap", "include"),`

But it's missing in the `framework-espidf/components` folder.
`esp_heap_caps.h` should be a part of espidf 2.211.0 , right?

Is there any way to use a staging version of espidf **directly from github** (like [espidf v3](https://github.com/espressif/esp-idf/tree/release/v3.0))?

**Comment by ivankravets** [comment]
Should be fixed in https://github.com/platformio/platform-espressif32/issues/63
