### ISSUE TITLE
ESP32 (CH9102X) not auto-detected

### ISSUE THREAD

**Issue by moussie369** [platformio/platform-espressif32#741]
### Configuration

**Operating system**: Ubuntu 21.10, kernel is 5.13.0-1020-raspi

**PlatformIO Version** (`platformio --version`): 5.2.5

### Description of problem
ESP32 (CH9102X) is not present in the devices tab nor auto-detected with serial monitor/upload

#### Steps to Reproduce

Select serial monitor/upload option or refresh the connected devices list

### Actual Results

Only port ttyAMA0 is detected (regardless if the board present or not)

### Expected Results

Port ttyAMA0 and port ttyCH343USB0 detection

### Additional info

Drivers installed: https://github.com/WCHSoftGroup/ch343ser_linux
The board is registered as ttyCH343USB0 with ls /dev/tty* and I'm able to connect to it if I ad the upload/monitor_port lines in platformio.ini, looks like it's simply filtered/not detected

**Comment by FernandoGarcia** [comment]
Hi!

For me with Ubuntu 18.04 the board is detected and can use the serial monitor. Running `pio device list` I have:

```
/dev/ttyACM0
------------
Hardware ID: USB VID:PID=1A86:55D4 SER=5424032785 LOCATION=2-10:1.0
Description: USB Single Serial
```

In device list I have:

![Captura de tela de 2022-03-24 11 34 56](https://user-images.githubusercontent.com/2778501/159940173-f358a8e2-5a31-4e22-9a3d-f1b4afd7ec1f.png)

In windows I have:

<img width="520" alt="serial" src="https://user-images.githubusercontent.com/2778501/159946733-6a8615d9-02a9-4ba8-bb99-0221bb132acb.png">

For now I had no luck to compile a code for my `M5stack stamp C3` in PIO.


Best regards.

**Comment by Jason2866** [comment]
@FernandoGarcia We can track down if this is a problem generated from the CH9102.
Trying this platform build. It supports for IDF/Arduino the ESP32, C3, S2 and S3
```
platform = https://github.com/Jason2866/platform-espressif32.git
```
