### ISSUE TITLE
How to load the .a file into it and compile it?

### ISSUE THREAD

**Issue by hzhh110** [platformio/platform-espressif32#758]
![image](https://user-images.githubusercontent.com/19906209/162188366-153c4317-8723-4bf0-a515-3af74cfe3cd7.png)
![image](https://user-images.githubusercontent.com/19906209/162188477-c5492c88-bf32-451f-84b4-9b4cb2d761c6.png)

**Comment by ivankravets** [comment]
You need https://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-flags

```
build_flags -lPPCS_API -Llib
```
