### ISSUE TITLE
USB Host library missing

### ISSUE THREAD

**Issue by Spongman** [platformio/platform-espressif32#761]
as described here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/usb_host.html

```
#include "usb/usb_host.h"
```

I created a new project:
```
[env:featheresp32-s2]
platform = espressif32
board = featheresp32-s2
framework = espidf
```

but `usb_host.h` is not found.

**Comment by Spongman** [comment]
the whole `usb` directory is missing: https://github.com/espressif/esp-idf/tree/master/components/usb

**Comment by valeros** [comment]
This component was only added in ESP-IDF v4.4. Unfortunately, there is no support for this version at the moment. The status is tracked here https://github.com/platformio/platform-espressif32/issues/710
