### ISSUE TITLE
Board Support: WEMOS LOLIN C3 Mini

### ISSUE THREAD

**Issue by vedsmith92** [platformio/platform-espressif32#762]
Request for support on this board from WEMOS.
https://www.wemos.cc/en/latest/c3/c3_mini.html

**Comment by moridin1138** [comment]
Seconded, please add support.  Id much prefer to use platformio vs arduino IDE

**Comment by Jason2866** [comment]
You will not be happy with this board. It has massive issues. The HF part is borked.

**Comment by moridin1138** [comment]
@Jason2866 Can you explain what you mean by "HF part is borked".    I've poked around online and have not found anything substantial.

**Comment by Jason2866** [comment]
@moridin1138  Look in there official store (Aliexpress) for the user feedbacks.
And we have many feedbacks, opened a discussion [here](https://github.com/arendst/Tasmota/discussions/15443)
