### ISSUE TITLE
Error: The program size (1623094 bytes) is greater than maximum allowed (1310720 bytes)

### ISSUE THREAD

**Issue by sinmim** [platformio/platform-espressif32#764]
Error: The program size (1623094 bytes) is greater than maximum allowed (1310720 bytes)
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1

**Comment by valeros** [comment]
You need to use a partition table with a bigger section for your application, for example `huge_app.csv`:
```ini
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
board_build.partitions = huge_app.csv
```
