### ISSUE TITLE
Update esptool.py to v3.3

### ISSUE THREAD

**Issue by Jason2866** [platformio/platform-espressif32#770]
since the toolchains `patch3` needs the latest esptool to generate valid firmware files.
Using the v3.1 generates issues.

**Comment by valeros** [comment]
Hi @Jason2866 ! Thanks for the info, will be updated shortly.  Meanwhile, could you please share a bit more information about the issues v3.1 generates?

**Comment by Jason2866** [comment]
The linking of elf sections has changed for the newer ESP32 S2x

**Comment by valeros** [comment]
Thanks, updated.
