### ISSUE TITLE
Add support for generic Esp32 WRoom devkit with 16Mb 

### ISSUE THREAD

**Issue by Bascy** [platformio/platform-espressif32#780]
Config is the same as in `esp32dev.json` with the following changes:

`
  "flash_size": "16MB",
  "maximum_size": "maximum_size": 16777216,
`

**Comment by valeros** [comment]
Hi @Bascy ! Simply use the default `esp32dev` ID and override the `flash_size` and `partitions` options in your `platformio.ini`:
```ini
platform = espressif32
board = esp32dev
framework = arduino

board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
```
