### ISSUE TITLE
gpio_hold_en not working with versions >= 4.0.0 on plateform espressif32

### ISSUE THREAD

**Issue by dynek** [platformio/platform-espressif32#782]
Hey guys,

Got a working piece of code to hold gpio state using `gpio_hold_en` when going into deep sleep mode on 3.5.0 (espressif32) but since I upgraded to 4.0.0 and 4.1.0 it doesn't work anymore.

Not sure if it's related to plateform io's extension or Espressif's SDK but there's obviously a regression.

Behavior works as expected with 3.5.0 but with >= 4.0.0 as soon as the ESP wakes up, GPIOs are reset to their default state.

Thank you

**Comment by Jason2866** [comment]
It is IDF / Arduino framework related not related to Platformio

**Comment by dynek** [comment]
Is there any difference "espressif-wise" between 4.0.0 and 4.1.0 then ?
Because I was having i2c issues with 3.5.0 and 4.0.0 that are resolved in 4.1.0 but I can't seem to grasp the difference between 4.0.0 and 4.1.0 that would explain such a thing.

**Comment by Jason2866** [comment]
There are many fixes from IDF 4.4.0 to IDF 4.4.1. Later Arduino Core use more actual IDF 4.4.1 version.
So all fixes in IDF 4.4.x are in newer Arduino builds. Yes, there are changes in IDF 4.4.1 regarding GPIOs which may causes regressions. If you want to know more details you have to follow espressif IDF and Arduino issues

**Comment by enfo** [comment]
I got the same issue, has anyone found a fix for this other than downgrading?

**Comment by dynek** [comment]
Haven't found any fix, haven't checked with Espressif directly (yet) and can't downgrade because it breaks i2c, at least when there are multiple i2c devices on the same bus, even when using semaphore.

**Comment by Jason2866** [comment]
This is the wrong github for issues with Arduino espressif code.
Needs to be opened [there](https://github.com/espressif/arduino-esp32)

**Comment by dynek** [comment]
You're totally right @Jason2866, closing this.

**Comment by dynek** [comment]
@Jason2866 have you tried with v4.2.0 released 10 days ago ? Issue persists ?

**Comment by enfo** [comment]
> @enfo have you tried with v4.2.0 released 10 days ago ? Issue persists ?

Yes, I have and it still persists

**Comment by dynek** [comment]
I'm really sorry for not being able to find out the info by myself but I'd like to raise an issue on arduino-esp32's github repo but I'm unable to find valuable information for them to investigate.
What is version "~3.10006.0" in `platform.json` ? It doesn't match any release in arduino-esp32's repo, currently at 2.0.3 🤔
