### ISSUE TITLE
Extremely poor SD card performance with <SD.h>

### ISSUE THREAD

**Issue by RasmusAPedersen** [platformio/platform-espressif32#789]
I am facing read/write speeds similar to the ones reported for Arduino core 2.0.2 as reported here: https://github.com/espressif/arduino-esp32/issues/6475

Currently, my PIO project is completely update to date (unsure of the arduino core version, but "pio update" states everything is up to date).

Is there a way I can implement the fix as is suggested in the issue I link to? I'm on an Ubuntu machine if that matters.

Thanks for your work and effort.

**Comment by valeros** [comment]
Hi @RasmusAPedersen ! PlatformIO uses only stable versions of the packages. As a workaround you can patch your Arduino package manually as described [here](https://docs.platformio.org/en/latest/scripting/examples/override_package_files.html) or simply use the upstream version of the framework as described [here](https://docs.platformio.org/en/latest/platforms/espressif32.html#using-arduino-framework-with-staging-version).
