### ISSUE TITLE
PIO Inspect Code Fails

### ISSUE THREAD

**Issue by mrengineer7777** [platformio/platform-espressif32#792]
VS Code 1.66.2
PIO IDE Plugin 2.4.3
PIO Core 5.2.5
PIO Home 3.4.1
Framework arduino-esp32 v2.0.3
platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3/platform-espressif32-2.0.3.zip
Severity: Low. Would be nice if it worked.

Inspect partially fails.  Works if "Inspect Memory" is on.  Fails if "Check Code" is selected.
Issue appears to be with `toolchain-xtensa32@2.50200.97`.  There may be a syntax error on line 144.
I see PIO also includes a package for `toolchain-xtensa-esp32@8.4.0+2021r2-patch3`. Not sure why Inspect uses the old version.

![image](https://user-images.githubusercontent.com/44048235/166786183-0a1a0f25-18ab-4976-8160-a83c40e9765b.png)

```
Error: Found a breaking defect 'syntax error' in C:\Users\David\.platformio\packages\toolchain-xtensa32@2.50200.97\xtensa-esp32-elf\include\c++\5.2.0\bits\exception_ptr.h:144
Please note: check results might not be valid!
Try adding --skip-packages

"severity=error<&PIO&>message=syntax error<&PIO&>file=C:\Users\David\.platformio\packages\toolchain-xtensa32@2.50200.97\xtensa-esp32-elf\include\c++\5.2.0\bits\exception_ptr.h<&PIO&>line=144<&PIO&>column=24<&PIO&>callstack=[C:\Users\David\.platformio\packages\toolchain-xtensa32@2.50200.97\xtensa-esp32-elf\include\c++\5.2.0\bits\exception_ptr.h:144]<&PIO&>cwe=0<&PIO&>id=syntaxError"

Error: cppcheck failed to perform check! Please examine tool output in verbose mode.

========================= [FAILED] Took 16.83 seconds =========================
Environment Tool Status Duration
--------------------- -------- -------- ------------
featheresp32ard cppcheck FAILED 00:00:16.827
featheresp32ard-debug cppcheck IGNORED
==================== 1 failed, 0 succeeded in 00:00:16.827 ====================
```

Thank you for your consideration.

**Comment by Jason2866** [comment]
You have probably thiy old toolchain in your `.platformio\packages` folder.
Delete the `packages` and the `platform` folder. Platformio will rebuild.
Anyways the actual toolchains seems not to be compatible with Project Inspect.
I get a error message regarding the toolchains similar yours.

**Comment by valeros** [comment]
Hi @mrengineer7777 ! Could you please try the [`check_skip_packages = yes`](https://docs.platformio.org/en/latest/projectconf/section_env_check.html#check-skip-packages) option in your project configuration?

**Comment by mrengineer7777** [comment]
@Jason2866 Deleting....over 5GB of data.  After loading everything again, check still fails:
```
Error: Found a breaking defect 'syntax error' in C:\Users\David\.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\include\c++\8.4.0\bits\exception_ptr.h:150
Please note: check results might not be valid!
Try adding --skip-packages
```

Using the PIO CLI in VSCode:
```
PS C:\Users\David\OneDrive\Documents\PlatformIO\Projects\D4500> pio check --skip-packages
Checking featheresp32ard > cppcheck (board: featheresp32; framework: arduino; platform: https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3/platform-espressif32-2.0.3.zip)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------lib\PagePort\PagePort.h:83: [low:style] Class 'AsyncPagePortServer' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
src\main.cpp:60: [low:style] The scope of the variable 'heap_highwater_mark' can be reduced. [variableScope]
src\main.cpp:61: [low:style] The scope of the variable 'heap_lowwater_mark' can be reduced. [variableScope]
src\main.cpp:58: [low:style] Unused variable: buf [unusedVariable]
src\main.cpp:59: [low:style] Unused variable: len [unusedVariable]
src\main.cpp:57: [low:style] The function 'loop' is never used. [unusedFunction]
src\main.cpp:36: [low:style] The function 'setup' is never used. [unusedFunction]
====================================================================================== [PASSED] Took 0.14 seconds ====================================================================================== 
....
.....
Environment            Tool      Status    Duration
---------------------  --------  --------  ------------
featheresp32ard        cppcheck  PASSED    00:00:00.139
featheresp32ard-debug  cppcheck  PASSED    00:00:00.146
```

Adding `check_skip_packages = yes` to my platformio.ini:
![image](https://user-images.githubusercontent.com/44048235/167222230-fef843e3-76a4-4e33-90b9-113f9cc9bc6e.png)

Works for me, and gives helpful feedback.  Thanks!

**Comment by mickeyl** [comment]
Good that it works for you now, but I'd like to know what the underlying problem is and whether it could be perhaps fixed instead?

**Comment by hitecSmartHome** [comment]
I have no success with `check_skip_packages = yes`
I get `Error: The program size (3165101 bytes) is greater than maximum allowed (3145728 bytes)`

**Comment by Jason2866** [comment]
@hitecSmartHome change your partition.csv so that the compiled firmware does fit in the APP slot
Not an PIO inspect issue

**Comment by hitecSmartHome** [comment]
The app fits. How would it compile and run if not?

**Comment by Jason2866** [comment]
With PIO Inspect it compiles in debug mode and the firmware is way bigger. It does not fit as the message shows :-)

**Comment by hitecSmartHome** [comment]
I see. Thanks for the tip. Will try to calculate a new partition table specifically for Inspect.
