### ISSUE TITLE
ESP32 SD card not working in v4.2, but in v3.5

### ISSUE THREAD

**Issue by Rai-Sp** [platformio/platform-espressif32#797]
The problem has been introduced by a modification in
     ...../packages/framework-arduinoespressif32/libraries/SD/src/sd_diskio.cpp
The function ff_sd_status in v3.5.0 contained just a simple
     return s_cards[pdrv]->status;
 whereas in v4.2.0 a send status request has been inserted before.

For me the problem is solved by removal of this send status request.
I don't understand, why this modification was made, and I wonder in
which environment the modification has been tested successfully.

MY ORIGINAL BUG REPORT WAS:

I have a problem to get SD card working on ESP32 with PlatformIO v4.2 the same way it worked with v3.5 before.
Fisrt indication of problems was an extreme slowdown of SD card operation. After including
build_flags =
    -DCORE_DEBUG_LEVEL=5
in platformio.ini these details showed up:
[  2485][W][sd_diskio.cpp:180] sdCommand(): crc error
[  2590][W][sd_diskio.cpp:174] sdCommand(): no token received
[  2693][W][sd_diskio.cpp:174] sdCommand(): no token received
[  2794][W][sd_diskio.cpp:180] sdCommand(): crc error
[  2895][W][sd_diskio.cpp:180] sdCommand(): crc error

Here is my example code:

/* Example showing problems on ESP32 with SD card in PlatformIO v4.2.0
   which did not exist in PlatformIO v3.5.0

The program was run on Espressif ESP-WROVER-KIT;
with external SD card (as built-in SD card slot is connected to pins,
which conflict with JTAG debugging).

NOTE: You will only see a direct indication of the problems, if you include

build_flags =
    -DCORE_DEBUG_LEVEL=5

in platformio.ini.

Otherwise the only effect is an extreme slowdown of SD card operation.

The output generated by the program is:
[  2058][W][sd_diskio.cpp:174] sdCommand(): no token received
[  2171][W][sd_diskio.cpp:174] sdCommand(): no token received
[  2274][W][sd_diskio.cpp:174] sdCommand(): no token received
[  2384][W][sd_diskio.cpp:174] sdCommand(): no token received
/sd/Test.txt has been written
[  2485][W][sd_diskio.cpp:180] sdCommand(): crc error
[  2590][W][sd_diskio.cpp:174] sdCommand(): no token received
[  2693][W][sd_diskio.cpp:174] sdCommand(): no token received
[  2794][W][sd_diskio.cpp:180] sdCommand(): crc error
[  2895][W][sd_diskio.cpp:180] sdCommand(): crc error
Read 13 Bytes from /sd/Test.txt
*/

#include <SD.h>

#define MY_SCLK 26
#define MY_MISO 34
#define MY_MOSI 0
#define MY_CS   27

SPIClass my_spi(HSPI);

void setup() {
  Serial.begin(115200);
  my_spi.begin(MY_SCLK, MY_MISO, MY_MOSI, MY_CS);
  SD.begin(MY_CS, my_spi, 10000000);

  delay(2000);
  FILE *fp = fopen("/sd/Test.txt", "wb");
  if(fp != NULL) {
    fprintf(fp, "Hello World!\n");
    fclose(fp);
    Serial.printf("/sd/Test.txt has been written\n");
  }
  else {
    Serial.printf("ERROR: Could not write /sd/Test.txt\n");
  }
}

void loop() {
  FILE *fp = fopen("/sd/Test.txt", "rb");
  if(fp != NULL) {
    char buffer[100];
    size_t len = fread(buffer, 1, sizeof(buffer), fp);
    fclose(fp);
    Serial.printf("Read %u Bytes from /sd/Test.txt\n", len);
  }
  else {
    Serial.printf("ERROR: Could not read /sd/Test.txt\n");
  }

  delay(1000);
}

**Comment by valeros** [comment]
Hi @Rai-Sp ! Could you please try the upstream version of the dev-platform with the latest Arduino core v2.0.3? For example:
```
[env:esp32dev]
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
board = esp32dev
monitor_speed = 115200
```
