### ISSUE TITLE
esp32 Takes too long to read from the sd card

### ISSUE THREAD

**Issue by arslan437** [platformio/platform-espressif32#804]
I have simple code that reads from the SD card around 500 to 600 bytes but it takes more than 3 seconds some times it take 4 seconds.

But in previous version of the platform it was not taking this long.

**Comment by valeros** [comment]
Hi @arslan437 ! Could you please try the upstream version of the dev-platform with the latest Arduino core v2.0.3? For example:
```
[env:esp32dev]
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
board = esp32dev
monitor_speed = 115200
```

**Comment by arslan437** [comment]
@valeros I have compiled the code with the platform link its much better much but not as fast it is in the 3.5.0 version.

**Comment by valeros** [comment]
Does it work better in the Arduino IDE?

**Comment by arslan437** [comment]
I have not test on Arduino IDE

**Comment by valeros** [comment]
@arslan437  Please retest your sketch in Arduino IDE.
