### ISSUE TITLE
Does not Boot/Start with 8MB partitions

### ISSUE THREAD

**Issue by savejeff** [platformio/platform-espressif32#817]
First of all, I'm super happy the new 4.3.0 version is out with final official Arduino support for C3 and S2!

I started testing the new version and I found that it works for the standard 4MB partition no problem. Tested Wifi, BLE, SD Card ...
But I found that when switching to 8MB partition the processor does not start
`board_build.partitions = default_8MB.csv`

Interestingly I don't get any output on the serial port. even after the press of the resetbutton I don't bet any boot msg. 

I Tested this on a ESP32 Haltec LoRa board ([this one](https://heltec.org/project/wifi-lora-32/))
I've created a basic hello world example that can be tested on any ESP32 with 8MB or more to demonstrate the problem

[Test_ESP32_430.zip](https://github.com/platformio/platform-espressif32/files/8777450/Test_ESP32_430.zip)

My first guess would be that it is caused by different start addresses, maybe together with the OTA partitions second app. 

EDIT: I tested 16MB partitions on a TTGO-SIM7000 board with 16MB and I get constant reboots with this msg:
```
[...]

rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:12784
load:0x40080400,len:3032
entry 0x400805e4
ets Jul 29 2019 12:21:46

rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:12784
load:0x40080400,len:3032
entry 0x400805e4
ets Jul 29 2019 12:21:46

rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:12784
load:0x40080400,len:3032
entry 0x400805e4
ets Jul 29 2019 12:21:46

[...]
```

**Comment by valeros** [comment]
Hi @savejeff ! Have you updated your flash memory size accordingly? For example:
```ini
...
board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB
```

**Comment by savejeff** [comment]
Hi @valeros ! 
No i have not. Is this a new option? 

It works with with the `board_upload.flash_size = 8MB` very nice.

Thx!
