### ISSUE TITLE
Consider updating Arduino-ESP32 after important fixes

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-espressif32#818]
* The cause of https://github.com/platformio/platform-espressif32/issues/815 is a bug in the builder script linking the variant folder as a `.a` archive instead of an `.o` object file, causing weak function to not work. For some boards, the crucial initVariant() function is thus not called when using PlatformIO and thus sketches have different behavior compared to the Arduino IDE. Fixed in https://github.com/espressif/arduino-esp32/pull/6809
* A cosmetic bug where a non-existing folder was added to the include path, causing an entry in the "Problems" view in VSCode, was fixed in https://github.com/espressif/arduino-esp32/pull/6798

Especially for the first reason, the `framework-arduinoespressif32` package should be updated, at least to include the builder script fixes (but still all other files from the 2.0.3 stable version).

**Comment by valeros** [comment]
Thanks, updated!
