### ISSUE TITLE
# fatal error: esp_netif.h: No such file or directory

### ISSUE THREAD

**Issue by skdush** [platformio/platform-espressif32#824]
hello guys,
when i run a code in the Arduino ide
i get this error :

C:\Users\Dell\Documents\Arduino\libraries\WiFi\src\WiFiSTA.cpp:44:23: fatal error: esp_netif.h: No such file or directory
compilation terminated.
exit status 1
Error de compilation pour la carte DOIT ESP32 DEVKIT V1
 i am using esp32 and i am running a code where i will use wifi.
please help me to fix this error !

**Comment by Jason2866** [comment]
This Platformio. Questions with Arduino IDE should be asked there.

**Comment by valeros** [comment]
Please forward to https://github.com/espressif/arduino-esp32
