### ISSUE TITLE
flash_size and upload maximum_size in board definitions

### ISSUE THREAD

**Issue by vanniaz** [platformio/platform-espressif32#83]
Hello,

I see that for most esp32-based boards the "upload" section of the board definition file declares a flash size of 4MB but a maximum size of around 1MB:
  "upload": {
    "flash_size": "4MB",
    "maximum_size": 1310720,

while for esp8266-based boards like the NodeMCU there is no "flash_size" entry but "maximum_size" is declared to be 4MB:
  "upload": {
    "maximum_size": 4194304,

The examples above are taken from esp32dev.json and nodemcuv2.json.

Moreover, in the "board explorer" all esp32 based boards are listed with a ROM size of 1MB, despite the fact that many of these use 4MB flash chips.
Can you help me understand all this?

Thanks
Giovanni

**Comment by BorisFR** [comment]
It is due to partition of the memory. Have a look at issue #58 .

**Comment by vanniaz** [comment]
@BorisFR 
Ok thanks, now it is clear.
Perhaps in the board explorer it would be better to indicate the flash size, not the partition size (all ESP32 boards are listed as "1MB" flash, also in the online table: https://platformio.org/boards)
