### ISSUE TITLE
Adafruit boards using tinyuf2 are missing partitions-4MB-tinyuf2.csv in boards.json

### ISSUE THREAD

**Issue by Jason2866** [platformio/platform-espressif32#832]
which is in folder https://github.com/espressif/arduino-esp32/blob/master/variants/adafruit_feather_esp32s2/partitions-4MB-tinyuf2.csv

**Comment by valeros** [comment]
I believe it's just renamed `partitions.csv` currently available in 2.0.3:
![image](https://user-images.githubusercontent.com/886732/174763934-372a6299-cda6-413f-bc6b-e5e6b921f300.png)

**Comment by Jason2866** [comment]
No, it is not a renamed partitions.csv
```

# ESP-IDF Partition Table
# Name,   Type, SubType, Offset,  Size, Flags
# bootloader.bin,,          0x1000, 32K
# partition table,          0x8000, 4K

nvs,      data, nvs,      0x9000,  20K,
otadata,  data, ota,      0xe000,  8K,
ota_0,    0,    ota_0,   0x10000,  1408K,
ota_1,    0,    ota_1,  0x170000,  1408K,
uf2,      app,  factory,0x2d0000,  256K,
ffat,     data, fat,    0x310000,  960K,
```

**Comment by valeros** [comment]
Got it, will be updated once a new stable Arduino core is released.

**Comment by Jason2866** [comment]
Maybe "scanning" the Arduino `variants` dir after a *.csv is a way to do (in `platformio-build.py`)?

**Comment by valeros** [comment]
Related PR https://github.com/espressif/arduino-esp32/pull/6887 has been submitted.
