### ISSUE TITLE
BluetoothSerial with ESP32 S3 (sp32-s3-devkitc-1) build fails

### ISSUE THREAD

**Issue by fabiencomte** [platformio/platform-espressif32#839]
Hello,
I get this output.

c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libe96/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL8_stop_btv+0x18): undefined reference to `esp_spp_disconnect'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libe96/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL8_stop_btv+0x1c): undefined reference to `esp_spp_deinit'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libe96/libBluetoothSerial.a(BluetoothSerial.cpp.o): in function `_stop_bt()':
C:/Users/comte/.platformio/packages/framework-arduinoespressif32/libraries/BluetoothSerial/src/BluetoothSerial.cpp:716: undefined reference to `esp_spp_disconnect'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32/libraries/BluetoothSerial/src/BluetoothSerial.cpp:717: undefined reference to `esp_spp_deinit'

**Comment by Jason2866** [comment]
S3 has no classic BT! So no BluetoothSerial.
