### ISSUE TITLE
platformio.ini ignore multiple monitor_port parameter

### ISSUE THREAD

**Issue by BorisFR** [platformio/platform-espressif32#84]
Version: home=0.9.5, Core=3.5.3b3
Mac OS 10.13.4
Using Visual Studio Code 1.23.0

In my project I have multiple env section in platform.ini
`
[env:featheresp32]
platform = https://github.com/platformio/platform-espressif32.git#feature/stage
board = featheresp32
framework = arduino
build_flags = -fpermissive -DESP32 -DHUZZAH32
 -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
monitor_baud = 115200
monitor_port = /dev/cu.SLAB_USBtoUART
upload_port = /dev/cu.SLAB_USBtoUART

[env:heltec_wifi_kit_32]
platform = https://github.com/platformio/platform-espressif32.git#feature/stage
board = heltec_wifi_kit_32
framework = arduino
build_flags = -fpermissive -DESP32 -DHELTEC_WK32
 -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
monitor_baud = 115200
monitor_port = /dev/cu.SLAB_USBtoUART12
upload_port = /dev/cu.SLAB_USBtoUART12
`

When I "upload and monitor" the second, heltec_wikfi_kit_32, **upload** is done on the right upload_port (/dev/cu.SLAB_USBtoUART12), but **monitor** try to open port of featheresp32 (/dev/cu.SLAB_USBtoUART), not the one from heltec section (/dev/cu.SLAB_USBtoUART12).

**Comment by ivankravets** [comment]
You need one of:

* http://docs.platformio.org/en/latest/projectconf/section_platformio.html#env-default
* http://docs.platformio.org/en/latest/userguide/cmd_device.html#cmdoption-platformio-device-monitor-e

**Comment by ivankravets** [comment]
Have you tried to run monitor in different terminal windows?
- http://docs.platformio.org/en/latest/userguide/cmd_device.html#platformio-device-monitor

```
pio monitor -b 115200 -p /dev/cu.SLAB_USBtoUART
pio monitor -b 115200 -p /dev/cu.SLAB_USBtoUART12
```

**Comment by BorisFR** [comment]
For sure that will work. But it does not solve that 'monitor_port' in [env] section of platformio.ini is just ignored...

**Comment by ivankravets** [comment]
* pio device monitor -e heltec_wifi_kit_32
* pio device monitor -e featheresp32

We can't run simultaneously 2 monitors from the single terminal. Later, we will plan to implement advanced serial port monitor in PIO Home

**Comment by BorisFR** [comment]
Ok. So close this issue. No problem.
