### ISSUE TITLE
esp32-s2-devkitc-1 

### ISSUE THREAD

**Issue by romocitto88** [platformio/platform-espressif32#842]
Hi everyone,
On PlatformIO there's not support for esp32-s2-devkitc-1. Is the same if I use esp32-s3-devkitc-1?

Thanks

**Comment by valeros** [comment]
Hi @romocitto88 ! 

> Is the same if I use esp32-s3-devkitc-1?

No, they aren't the same. The nearest alternative is `esp32-s2-saola-1`.
