### ISSUE TITLE
CONFIG_FREERTOS_HZ=1000 should be added to sdkconfig.defaults for examples

### ISSUE THREAD

**Issue by egnor** [platformio/platform-espressif32#846]
If the scheduler HZ is <1000, then small calls to the Arduino delay() function (such as delay(5)) will return immediately. The default HZ is 100. I recommend adding CONFIG_FREERTOS_HZ=1000 to the sdkconfig.defaults for espidf-arduino-blink and espidf-arduino-wifiscan, since people often clone these projects. I'm happy to create a PR for this if you think it makes sense.

(Also, the Arduino core should be better implemented so it works even with chunkier scheduling HZ. I'll file a separate bug about that.)

**Comment by egnor** [comment]
Note, https://github.com/espressif/arduino-esp32/pull/6955 (if accepted) will force this issue.

**Comment by wawan-ikhwan** [comment]
Yeah I thought so, I expect I get current millisecond from this function`xTaskGetTickCount` , But what I get is centisecond lol. Turns I need set to `CONFIG_FREERTOS_HZ=1000` in sdkconfig,

**Comment by Jason2866** [comment]
Please close. Feature is added in espressif32 Arduino github.
