### ISSUE TITLE
ESP32 - RSSI check throws away incoming UDP packets

### ISSUE THREAD

**Issue by dexter323i** [platformio/platform-espressif32#849]
Hi!

Board is ESP32 WROVER-E 16MB flash version. I have an application what did the folowing: It checked if there is any incoming UDP packets using WiFiUdp.h with calling parsePacket(), and check if the result is greater than 0. In the same loop also checked signal strength to show as a bar on a screen. (calling WiFi.RSSI()). When an UDP package was received, it stopped checking RSSI, to focus on handling UDP communication, and only went back to read RSSI too after a second of no incoming UDP messages.

This application was built long-long time ago with 3.2.0 or something Espressif32 platform version (VS Code, Arduino framework.), and worked flawlessly.
Since then I've did several updates (currently on 5.0.0), and just found out my application misbehaves. When the source starts sending UDP packages, my application does not get it. parsePacket() function returns 0 for several seconds (sometimes even for half a minute)! (UDP send rate is 60Hz!) When I flash my old hex on ESP32, then my old build works correctly again. (When the source sends UDP messages, it gets them all, and instantly, no pacakage loss.)

It took me weeks to find out, that frequent WiFi.RSSI() calls what causing UDP package loss. My current patch is to check RSSI once in every 4-5 seconds, and now it is very-very rare to have UDP message loss. (Still occurs sometimes) I could not notice package loss when I did not call WiFi.RSSI() at all.

I don't know if it is a bug or feature, but maybe you should check it. The old behaviour feels better.

Dexter

**Comment by valeros** [comment]
Hi @dexter323i ! Any chance you could test your project in the Arduino IDE? Just to ensure that there is nothing wrong with the Arduino framework itself.
