### ISSUE TITLE
How to add more examples to the  platform-espressif32 framework

### ISSUE THREAD

**Issue by hit-wpc** [platformio/platform-espressif32#850]
I notice that the examples in the espidf are more than examples in PIO ，how can I add the espidf examples to  platform-espressif32 framework

**Comment by valeros** [comment]
Hi @hit-wpc ! There is no sense to duplicate the same projects in this development platform and the IDF framework itself. The dev-platform contains only essential project examples that serve as a starting point for new users. You can navigate to the framework directory somewhere here `c:\YOUR_USER\.platformio\packages\framework-espidf\examples`, just copy paste any example you like and then open it in the editor.
