### ISSUE TITLE
How to use the latest platform 5.0 and C++20?

### ISSUE THREAD

**Issue by VioletGiraffe** [platformio/platform-espressif32#856]
Is it possible to use C++20 (`-std=gnu++20` or `-std=gnu++2a`) yet? If it is, what needs to be specified in `platformio.ini`?
This is what I've tried:
```
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
board = esp32dev
```
This is what got downloaded:
```
Platform Manager: Installing git+https://github.com/platformio/platform-espressif32.git
git version 2.37.1.windows.1
Cloning into 'C:\Users\User\.platformio\.cache\tmp\pkg-installing-lpe96j5y'...
remote: Enumerating objects: 558, done.
remote: Counting objects: 100% (558/558), done.
remote: Compressing objects: 100% (425/425), done.
remote: Total 558 (delta 244), reused 324 (delta 112), pack-reused 0
Receiving objects: 100% (558/558), 442.72 KiB | 810.00 KiB/s, done.
Resolving deltas: 100% (244/244), done.
Platform Manager: espressif32@5.0.0+sha.019ee09 has been installed!
Tool Manager: Installing espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Unpacking  [####################################]  100%
Tool Manager: toolchain-xtensa-esp32@8.4.0+2021r2-patch3 has been installed!
Tool Manager: Installing platformio/framework-arduinoespressif32 @ ~3.20003.0
Unpacking  [####################################]  100%
Tool Manager: framework-arduinoespressif32@3.20003.220626 has been installed!
```
And compiling throws an error:
`unrecognized command line option '-std=gnu++20'; did you mean '-std=gnu++2a'?`
Unfortunately, this compiler does know `gnu++2a` but doesn't support `consteval` (which my libraries use), obviously the number of supported C++20 features is quite small. So the real question is: can I get a more recent compiler for ESP32?

The deployed compiler is based on GCC 8.4.0, which really is very old by now. GCC 10 would be workable, GCC 12 - perfect.

**Comment by valeros** [comment]
Hi @VioletGiraffe ! Unfortunately, GCC 8.4.0 is the only available version at the moment:
https://registry.platformio.org/tools/espressif/toolchain-xtensa-esp32/versions

It means there is no easy way to override the toolchain package, but I believe you can download these binaries https://github.com/espressif/crosstool-NG/releases and replace the old toolchain in `c:\YOUR_USER\.platformio\packages\toolchain-xtensa-esp32`, just keep the old `package.json` and `.piopm` files.
