### ISSUE TITLE
Bootloader built with at least INFO level for build_type = debug ?

### ISSUE THREAD

**Issue by lranders** [platformio/platform-espressif32#857]
Would it be possible to have an extra set of 2nd stage bootloaders available in
`~\.platformio\packages\framework-arduinoespressif32\tools\sdk\<variant>\bin`,
built with at least INFO message-level
and then have pio use them when one sets `build_type = debug` in platformio.ini?

Personally, right now, I have built a dummy ESPIDF project with bootloader log level set to INFO
and I then "transplant" that loader to Arduino projects, whenever I am in doubt
as to what my partition layout looks like.

Perhaps it's a beginner-level thing to do (and I am), but I like being able to see what my ESP is doing at startup.
Furthermore, I am seeing a fair amount of people get tripped up with wrong partition tables,
#837 is just an example, so I think this could be a helpful feature.

It is also possible that one is able to rebuild bootloaders, but so far I have missed the
instructions for that completely. Feel free to enlighten me if that is the case.

**Comment by valeros** [comment]
Hi @lranders ! As you correctly noticed, the Arduino core for ESP32 is shipped with prebuilt bootloaders that cannot be adjusted. So unfortunately, there is no other way than manually compiling a bootloader with required settings elsewhere and replacing the binary in the framework folder (as you already doing now). 

Anyway, it may be a good idea to ask this question here https://github.com/espressif/arduino-esp32, maybe someone can suggest a workaround.
