### ISSUE TITLE
ESP32 Board support for ESP_AT_Lib Library

### ISSUE THREAD

**Issue by Sireevenkat** [platformio/platform-espressif32#858]
Hi,
I am working with Libraries related to WIFI using Platform IO IDE in Visual Studio Code.
For ESP_AT_Lib library in its GIT Repository they mentioned It won't support ESP32 Board.But in Platform IO IDE mentioned its works for ESP32 Board also.Can you check and guide me whether ESP_AT_Lib supports ESP32 board or not if it supports can you tell me for which library version ESP32 board supports that library.

**Comment by valeros** [comment]
Hi @Sireevenkat ! Only the author of that library is responsible for the list of supported hardware as PlatformIO only provides a convenient way of using libraries. You'd better ask this question in the library repository in case there is an inconsistency.
