### ISSUE TITLE
Compile error with latest development version

### ISSUE THREAD

**Issue by lucadentella** [platformio/platform-espressif32#86]
Hi

new project, changed the platformio.ini file to use the development version:

    [env:lolin32]
    platform = https://github.com/platformio/platform-espressif32.git
    board = lolin32
    framework = espidf

the compile process fails with the following error:
```
In file included from C:/Users/luca/.platformio/packages/framework-espidf/components/mbedtls/port/include/mbedtls/esp_config.h:2665:0,
from C:/Users/luca/.platformio/packages/framework-espidf/components/mbedtls/include/mbedtls/sha256.h:29,
from C:\Users\luca\.platformio\packages\framework-espidf\components\bootloader_support\src\bootloader_sha.c:22:
C:/Users/luca/.platformio/packages/framework-espidf/components/mbedtls/include/mbedtls/check_config.h:73:2: error: #error "MBEDTLS_CTR_DRBG_C defined, but not all prerequisites"
#error "MBEDTLS_CTR_DRBG_C defined, but not all prerequisites"
^
*** [.pioenvs\lolin32\bootloader_support\src\bootloader_sha.o] Error 1
```

**Comment by lucadentella** [comment]
I also noticed that, everytime I run the compile process, it says:

    Warning! Detected an outdated "sdkconfig.h" file. The old "sdkconfig.h" will be replaced by the new one.

and creates a .bak file... even if I delete it

**Comment by ivankravets** [comment]
Please run `pio update` in PIO IDE for VSCode. It should work now.

**Comment by lucadentella** [comment]
fixed, thanks!
