### ISSUE TITLE
ESP-C3-32S-KIT-2M。After burning the program, it cannot run normally, but uploading the program in arduinoide is available.

### ISSUE THREAD

**Issue by xiezhoubin** [platformio/platform-espressif32#862]
![image](https://user-images.githubusercontent.com/75734559/180652301-3bc6e01d-6580-4687-a5cc-c148c2d020b8.png)
![image](https://user-images.githubusercontent.com/75734559/180652310-e16429fd-24e2-43a0-a7c7-3ea1ab8e0a85.png)
![image](https://user-images.githubusercontent.com/75734559/180652318-8ee97a9b-5383-49e1-a245-0b719320e695.png)
![image](https://user-images.githubusercontent.com/75734559/180652325-b6ee2252-431b-4b09-909c-996d01411d7d.png)
![image](https://user-images.githubusercontent.com/75734559/180652330-1c75f116-ff5b-4d18-b6fb-306aed8bfb78.png)
![image](https://user-images.githubusercontent.com/75734559/180652440-165b9dbf-31dc-421b-87c3-602b541f5dd8.png)
![image](https://user-images.githubusercontent.com/75734559/180652464-b2af9f14-f44f-4795-b4dd-e786704b17d5.png)

**Comment by ivankravets** [comment]
Do you use the same version of Arduino Core for ESP32? See related issue https://community.platformio.org/t/why-the-ble-client-example-works-on-arduino-ide-but-dont-work-on-the-vscode-platformio/28857

**Comment by xiezhoubin** [comment]
Still not.
![image](https://user-images.githubusercontent.com/75734559/180926296-8e0bb3d9-40fe-4cd9-a001-1d901d7f7f58.png)
![image](https://user-images.githubusercontent.com/75734559/180926347-b5534f81-6ba8-4e74-b536-ea5687357d99.png)
![image](https://user-images.githubusercontent.com/75734559/180926373-65a1f4e6-998b-4345-8f85-b8bda6243c0d.png)

**Comment by xiezhoubin** [comment]
Arduino for esp32 version is 2.0.4.
![image](https://user-images.githubusercontent.com/75734559/180928317-35f37c3d-1812-49a9-b3bc-39cd9aeccbc4.png)

**Comment by maxgerhardt** [comment]
Seems to work when creating a board JSON file that has 2MByte set as `flash_size`. Setting it via the platformio.ini still somehow results in PIO using the original board JSON file's 4MByte value, and this crashes the boot process. See [here](https://community.platformio.org/t/esp-c3-32s-kit-2m-after-burning-the-program-it-cannot-run-normally-but-uploading-the-program-in-arduinoide-is-available/28910/8?u=maxgerhardt).

**Comment by valeros** [comment]
Shouldn't it be `board_upload.flash_size = 2MB` instead of `board_build.flash_size = 2MB`?

**Comment by xiezhoubin** [comment]
> board_upload.flash_size = 2MB

you are right.
![image](https://user-images.githubusercontent.com/75734559/180972196-d07d52d5-51c9-4ee4-9a7c-d02f6a23b8ed.png)

**Comment by xiezhoubin** [comment]
> Shouldn't it be `board_upload.flash_size = 2MB` instead of `board_build.flash_size = 2MB`?
So what is the function of "board_build.flash_size"?

**Comment by valeros** [comment]
> So what is the function of "board_build.flash_size"?

It's a typo, there is no `flash_size` option in the `build` section of the board manifest.

**Comment by xiezhoubin** [comment]
> Ohh indeed. Technically that should also be `board_upload.maximum_size`, but this is dynamically recalculated by PIO anyways.

Do you need to set "board_build.maximum_size"? Or will it be generated automatically?

**Comment by xiezhoubin** [comment]
In addition, where can I find relevant instructions about configuration parameters such as "board_upload" or "board_build"?

**Comment by valeros** [comment]
> Do you need to set "board_build.maximum_size"? Or will it be generated automatically?

It might be a good idea to be consistent and update `maximum_size` as well. 

> In addition, where can I find relevant instructions about configuration parameters such as "board_upload" or "board_build"?

More info available here https://docs.platformio.org/en/latest/platforms/espressif32.html#configuration

**Comment by xiezhoubin** [comment]
ok,thanks very much.
