### ISSUE TITLE
PPP support removed

### ISSUE THREAD

**Issue by Pablo2048** [platformio/platform-espressif32#865]
Support for PPP protocol (ie PPPoS netif interface for GSM modems) was removed from version 4.1.0 onwards. My question is if this was for some reason ad if the PPP support can be re-enabled in next release. Thank You.

**Comment by valeros** [comment]
Hi @Pablo2048 ! The PlatformIO team doesn't remove or add any functionality, this decision rests with the framework/library maintainers, so it might be a good idea to forward your question to them.
