### ISSUE TITLE
esp32-c3-devkitm-1 Arduino Framework

### ISSUE THREAD

**Issue by Saasi-FPV** [platformio/platform-espressif32#873]
According to the documentation of the esp32-c3-devkitm-1[https://github.com/platformio/platformio-docs/blob/f79c01f6f3825d413e9e6f92b9c3cba899860c8b/boards/espressif32/esp32-c3-devkitm-1.rst](url) it should be compatible with the Arduino Framework. But it won't compile with this error:
PACKAGES:
 - framework-arduinoespressif32 @ 3.10006.210326 (1.0.6)
 - tool-esptoolpy @ 1.30100.210531 (3.1.0)
 - toolchain-riscv-esp @ 1.80400.0 (8.4.0)
Error: This board doesn't support arduino framework!

Is there a workaround?

Thanks
Jan

**Comment by valeros** [comment]
You need to update your development platform, just run `pio platform update espressif32` in the IDE terminal.
