### ISSUE TITLE
Exceptions not working in ESP-IDF 3.0 framework (build 9080ace)

### ISSUE THREAD

**Issue by FoxKeys** [platformio/platform-espressif32#88]
ESP-IDF anounced exceptions support. But, they doesn't work under platformio.
Throw exception resets CPU ("abort() was called at PC 0x400d0797 on core 0")

**Test code:** 
```
#include "esp_log.h"
#define tag "ExceptionsTest"
extern "C" void app_main(void)
{
	ESP_LOGI(tag, "Before try");
	try {
		ESP_LOGI(tag, "Before throw");
		throw false;
		ESP_LOGI(tag, "After throw");
	} catch ( bool val ){
		ESP_LOGI(tag, "catch");
	}
	ESP_LOGI(tag, "After try");
}
```

**platformio.ini**
```
[env:upstream_develop]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32dev
framework = espidf
build_flags = -fexceptions
```

**ESP32 output:**
ad:0x3fff0018,len:4
load:0x3fff001c,len:5508
load:0x40078000,len:0
load:0x40078000,len:12488
entry 0x40078fd4
I (28) boot: ESP-IDF 2.300.0 2nd stage bootloader
I (28) boot: compile time 17:22:42
I (29) boot: Enabling RNG early entropy source...
I (33) boot: SPI Speed      : 40MHz
I (37) boot: SPI Mode       : DIO
I (41) boot: SPI Flash Size : 4MB
I (45) boot: Partition Table:
I (49) boot: ## Label            Usage          Type ST Offset   Length
I (56) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (64) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (71) boot:  2 factory          factory app      00 00 00010000 00100000
I (79) boot: End of partition table
I (83) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x0cb00 ( 51968) map
I (110) esp_image: segment 1: paddr=0x0001cb28 vaddr=0x3ffc0000 size=0x01ee4 (  7908) load
I (113) esp_image: segment 2: paddr=0x0001ea14 vaddr=0x40080000 size=0x00400 (  1024) load
I (117) esp_image: segment 3: paddr=0x0001ee1c vaddr=0x40080400 size=0x011f4 (  4596) load
I (128) esp_image: segment 4: paddr=0x00020018 vaddr=0x400d0018 size=0x12c74 ( 76916) map
I (162) esp_image: segment 5: paddr=0x00032c94 vaddr=0x400815f4 size=0x06408 ( 25608) load
I (172) esp_image: segment 6: paddr=0x000390a4 vaddr=0x400c0000 size=0x00000 (     0) load
I (177) boot: Loaded app from partition at offset 0x10000
I (177) boot: Disabling RNG early entropy source...
I (182) cpu_start: Pro cpu up.
I (186) cpu_start: Starting app cpu, entry point is 0x40080e2c
I (178) cpu_start: App cpu up.
I (197) heap_init: Initializing. RAM available for dynamic allocation:
I (203) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (209) heap_init: At 3FFC26F0 len 0001D910 (118 KiB): DRAM
I (216) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (222) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (228) heap_init: At 400879FC len 00018604 (97 KiB): IRAM
I (235) cpu_start: Pro cpu start user code
I (252) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (254) ExceptionsTest: Before try
I (254) ExceptionsTest: Before throw
abort() was called at PC 0x400d0797 on core 0

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/platforms/espressif32.html#enable-c-exceptions
