### ISSUE TITLE
Blaster USB Altra debugger support

### ISSUE THREAD

**Issue by roberttestter** [platformio/platform-espressif32#891]
Support  Blaster USB Altra for debugging , 
Its a cheap debugger and many one can buy it 
, can any one tell me if i can use this debugger now and how ?

**Comment by valeros** [comment]
Hi @roberttestter ! Unfortunately, we don't this debug probe at hand so we cannot test that it works correctly with the ESP32 targets. You can manually configure [a custom debug server](https://docs.platformio.org/en/latest/projectconf/section_env_debug.html#debug-server) to check if it works. Roughly, it should look something like this for ESP32:
```ini
[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32dev
monitor_speed = 115200
debug_init_break = thb app_main
debug_init_cmds =
    define pio_reset_halt_target
        monitor reset halt
        flushregs
    end
    define pio_reset_run_target
        monitor reset
    end
    target extended-remote $DEBUG_PORT
    $LOAD_CMDS
    pio_reset_halt_target
    $INIT_BREAK
debug_tool = custom
debug_server =
    ${platformio.packages_dir}/tool-openocd-esp32/bin/openocd
    -s
    ${platformio.packages_dir}/tool-openocd-esp32/share/openocd/scripts
    -f
    interface/altera-usb-blaster.cfg
    -f
    target/esp32.cfg
```
