### ISSUE TITLE
ESPhome dev ESP32-S3 not working with neopixel

### ISSUE THREAD

**Issue by kj4dxk** [platformio/platform-espressif32#895]
esp32:
  board: adafruit_qtpy_esp32s3_nopsram
  variant: esp32s3
  framework:
    type: arduino
    version: 2.0.4
    platform_version: 5.1.1
	
light:
  - platform: fastled_clockless
    chipset: WS2812 #WS2812B
    pin: GPIO39 # NEOPIXEL qt py esp32-s3
    num_leds: 1
    rgb_order: BRG
    name: "FastLED WS2811 Light"
	  

This is what I have in ESPhome-DEV and it works without the light but with the light I get compiler errors no matter which method I choose if I use - platform: neopixelbus or if I use  - platform: fastled_clockless.

Is there a certain configuration that I can use?

**Comment by valeros** [comment]
Hi @kj4dxk ! This repository is not the right place for such questions, please forward it to https://github.com/esphome/esphome
