### ISSUE TITLE
Cannot pair BLE to Windows 11 or Android with WROOM 32

### ISSUE THREAD

**Issue by LIUHanyang96** [platformio/platform-espressif32#898]
Hi team,
I cannot pair BLE to Windows 11 or Android with WROOM 32. However, it can pair to Macbook easily.

I am using ESP-WROOM-32.

My config:
[env:denky32]
platform = espressif32
board = denky32
framework = arduino
monitor_speed = 115200
lib_deps = 
	t-vk/ESP32 BLE Keyboard@^0.3.2
	NimBLE-Arduino
build_flags = -D USE_NIMBLE

May anyone help?

**Comment by valeros** [comment]
Hi @LIUHanyang96 ! This repository is not the right place for such questions. Please forward to https://community.platformio.org/ or https://github.com/espressif/arduino-esp32
