### ISSUE TITLE
How do I load (.a) static library?

### ISSUE THREAD

**Issue by hzhh110** [platformio/platform-espressif32#900]
How do I load (.a) static library?

**Comment by valeros** [comment]
Hi @hzhh110 ! The usual workflow for adding a static archive to the build process is to use the [build_flags](https://docs.platformio.org/en/latest/projectconf/section_env_build.html) option (see the `-L, -l` flags). Please keep in mind that this repository is not the right place for generic questions, please ask the community https://community.platformio.org/ next time.
