### ISSUE TITLE
how to use ESP-IDF v4.4.2 

### ISSUE THREAD

**Issue by looping84** [platformio/platform-espressif32#906]
https://github.com/espressif/esp-idf/releases

espidf v4.4.2 fixed lots of bugs。 it's a stable version

platformio only has v4.4.0 version and v5.0 beta

<img width="994" alt="image" src="https://user-images.githubusercontent.com/1137549/188355694-58067348-60fc-4405-bdc5-5d69a7ede662.png">

**Comment by Jason2866** [comment]
In short, no easy way. Either Platformio or IDF needs a (small) change.
You have to wait for a official release or you can try my build in this [fork](https://github.com/Jason2866/platform-espressif32/tree/Tasmota/205)
Use with:
```
platform = https://github.com/Jason2866/platform-espressif32.git#Tasmota/205
```

**Comment by RoscoeTheDog** [comment]
> In short, no easy way. Either Platformio or IDF needs a (small) change. You have to wait for a [official release](https://github.com/platformio/platform-espressif32/issues/889#issuecomment-1234637631) or you can try my build in this [fork](https://github.com/Jason2866/platform-espressif32/tree/Tasmota/205) Use with:
> 
> ```
> platform = https://github.com/Jason2866/platform-espressif32.git#Tasmota/205
> ```

Could you kindly add board definitions for `esp32-s2-saola-1` on your branch? I'd like to use it as well but that is the board variant I am working with.

**Comment by Jason2866** [comment]
Board esp32-s2-saola-1 is there!

**Comment by RoscoeTheDog** [comment]
> Board esp32-s2-saola-1 is there!

Graci. I tried last night and it wouldn't build. Funny it should work now unless you added it overnight upon request. Regardless, everythings working as expected. Thanks!

**Comment by Jason2866** [comment]
@RoscoeTheDog  I did not change anything.
