### ISSUE TITLE
lib I2Cdev::readBytes will be block start from V4.1.0

### ISSUE THREAD

**Issue by gary-ygl** [platformio/platform-espressif32#909]
espressif32 @~4.1.0
Wire @ 2.0.0

Wire.beginTransmission(devAddr);
Wire.write(regAddr);
Wire.endTransmission();
Wire.beginTransmission(devAddr);

will be block start from V4.1.0

**Comment by valeros** [comment]
Hi @gary-ygl ! Does your code work as expected in the Arduino IDE?
