### ISSUE TITLE
esp32s3box  sdkconfig.h  no such file

### ISSUE THREAD

**Issue by txp666** [platformio/platform-espressif32#912]
### Actual Results
![image](https://user-images.githubusercontent.com/52451470/190035160-0da40ac5-1a44-43b8-91cd-09a6f8004bd7.png)

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:esp32s3box]
platform = espressif32
board = esp32s3box
framework = arduino
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

**Comment by txp666** [comment]
it's not worked

**Comment by maxgerhardt** [comment]
Compiles just fine with your platformio.ini + code. 

```
Linking .pio\build\esp32s3box\firmware.elf
Retrieving maximum program size .pio\build\esp32s3box\firmware.elf
Checking size .pio\build\esp32s3box\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [          ]   3.9% (used 12924 bytes from 327680 bytes)
Flash: [==        ]  15.5% (used 203477 bytes from 1310720 bytes)
```

If it still fails, your files still have a problem. Delete the folders `C:\Users\<user>\.platformio\.cache`,
`C:\Users\<user>\.platformio\packages`, and `C:\Users\<user>\.platformio\platforms` folders and build the project again to get a clean download.

**Comment by txp666** [comment]
![image](https://user-images.githubusercontent.com/52451470/190131609-5ea638a4-abeb-466d-9173-ecfc2854f537.png)
the version is 5.1.1   I build the projet failed on two computers

**Comment by maxgerhardt** [comment]
Oh, you're actually right. On 5.1.1 it's broken. Use 

```
platform = espressif32@5.0.0
```
in the `platformio.ini` for a workaround.

**Comment by txp666** [comment]
ok thank u  
i foud a way it's also worked 
![image](https://user-images.githubusercontent.com/52451470/190133780-b70e57e9-092c-43a3-b4fb-2785fa4c5a9d.png)

**Comment by Jason2866** [comment]
@valeros ALL S3 entrys for `"memory_type"` needs to be checked since the naming changed from core 2.0.3 to actual core 2.0.4
