### ISSUE TITLE
I upgraded the ESP32 PICO D4 firmware to  ESP32 PICO V3 ，Has been unable to start

### ISSUE THREAD

**Issue by K-LG** [platformio/platform-espressif32#919]
It keeps printing the following in a loop
rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)

![1663729015374](https://user-images.githubusercontent.com/113994010/191404400-e9e8c33b-e7fa-4f66-a4ab-f52f34be023a.png)
![1663729223703](https://user-images.githubusercontent.com/113994010/191404717-92468ea3-0a2d-435c-b791-c0724c083659.png)
![1663729268050](https://user-images.githubusercontent.com/113994010/191404814-a7225be4-8d4f-426f-9343-ea22b272f750.png)

I hope you can help me. Thank you

**Comment by K-LG** [comment]
I suspect that there is no bootloader.bin file for ESP32 PICO V3

**Comment by Jason2866** [comment]
You use a old platform framework. Pico is not supported there. Use latest platform!

**Comment by K-LG** [comment]
@Jason2866 Thanks for your reply,  I tried the 5.1.0 version and there were other problems

**Comment by K-LG** [comment]
I experienced Guru Meditation Error after using 5.1.0:
![image](https://user-images.githubusercontent.com/113994010/191462733-955176be-189f-4ef5-a3b2-e780bbe6de16.png)

**Comment by K-LG** [comment]
There are flash frequency issues
I have tried to modify it, but I don't know whether it is normal
board_build.f_flash = 40000000L

**Comment by Jason2866** [comment]
It is your sketch or a used library causing the problems. I have a board with a pico v3 which does work without issues.

**Comment by valeros** [comment]
Hi @K-LG ! Does it work as expected in the Arduino IDE?

**Comment by slaesh** [comment]
Guess [this](https://github.com/platformio/platform-espressif32/issues/947) is related?
