### ISSUE TITLE
Is it possible to manage memory for boards in projects (arduino)

### ISSUE THREAD

**Issue by wegunterjr** [platformio/platform-espressif32#92]
There are times when you might want to adjust your memory from the defaults.csv and boards (I think there is a json file, but not sure).   But if you change it on one dev machine, those changes aren't kept for the life of the project (ie, in version control) -  one, what all files need to be changed to allow platform compiler to compile larger programs, and is it possible to make those changes in the project and be maintained in version control?

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/platforms/espressif32.html#partition-tables

**Comment by wegunterjr** [comment]
ah dang.  I thought I searched for that.  Thanks!
