### ISSUE TITLE
Need advice for ESP32S3-WROOM-1 (4MB)

### ISSUE THREAD

**Issue by ams-hh** [platformio/platform-espressif32#934]
Configuration: Windows 10, Visual Studio Code 1.71.2, Platform ESP32 5.0.0 and 5.2.0

Hello,
I use to flash bare ESP models like ESP8266-12, ESP32-WROOM-32 and ESP32-S3-WROOM-1.
Never used ready boards, which are mostly referenced in platformio.ini >> board

With ESP32-S3 I startet recently with buying some ESP32-S3-WROOM-1N4 with 4MB Flash.
I startet to (try to) flash them with the following platformio.ini:

[platformio]
default_envs = esp32S3

[env]
framework = arduino
monitor_speed = 115200
upload_speed = 921600

`[env:esp32S3]
build_flags = 
  -D CORE_DEBUG_LEVEL=0
platform = espressif32
board = esp32-s3-devkitc-1

`
I then realized quickly, that the referenced board (a "naked" ESP32-WROOM-1N4 seems not to available) has 8MB of flash, not 4MB and an error message told me so..... I then created an own board file esp32-s3-wr-1-4MB.json which is a changed esp32-s3-devkitc-1.json:
(changed lines marked)

`{
  "build": {
    "arduino":{
      "ldscript": "esp32s3_out.ld",
      "partitions": "default.csv"
    },
    "core": "esp32",
    "extra_flags": [
      "-DARDUINO_ESP32S3_DEV",
      "-DARDUINO_USB_MODE=1",
      "-DARDUINO_RUNNING_CORE=1",
      "-DARDUINO_EVENT_RUNNING_CORE=1"
    ],
    "f_cpu": "240000000L",
    "f_flash": "40000000L", <<<<<<<<<<<
    "flash_mode": "dio",
    "hwids": [
      [
        "0X303A",
        "0x1001"
      ]
    ],
    "mcu": "esp32s3",
    "variant": "esp32s3"
  },
  "connectivity": [
    "wifi"
  ],
  "debug": {
    "default_tool": "esp-builtin",
    "onboard_tools": [
      "esp-builtin"
    ],
    "openocd_target": "esp32s3.cfg"
  },
  "frameworks": [
    "arduino",
    "espidf"
  ],
  "name": "ESP32S3 WROOM-1N4, 4MB, No PSRAM", <<<<<<<<<<<
  "upload": {
    "flash_size": "4MB", <<<<<<<<<<<
    "maximum_ram_size": 327680,
    "maximum_size": 4194304, <<<<<<<<<<<
    "require_upload_port": true,
    "speed": 460800
  },
  "url": "https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html",
  "vendor": "Espressif"
}

`
and placed it in a new folder "boards" in my project.
After that, I received a new error message that says, that bootloader_dio_40m.bin wasn't found. I searched and found under
....<framework>\tools\sdk\esp32s3\bin all available bootloaderX.bin files. But in contrast to the esp32\bin folder, where the 
bootloader_dio_40m.bin is there, here in \esp32s3\bin it is not.... ?
I tried then to compile and flash my program with the original Arduino IDE ... and it worked.This file is named there as "HelloWord.ino.bootloader.bin". I copied this file to ....<framework>\tools\sdk\esp32s3\bin as bootloader_dio_40m.bin (with bad feelings!). But it worked. I could now compile and flash my programs on a bare ESP32S3-WROOM-1N4.

But .... then came platform ESP32 release 5.2.0.
And from now on one more file is requested: bootloader_dio_40m.elf. As before, the 80m and 120m variants of the bootloaderX files are available under ....\esp32S3\bin, but nothing for 40m.

Now I am at the end of the street amd needs some help with the following questions:

1) What is the correct way to program bare ESP-Modules. All available "boards" only address complex developer PCB.
2) Is it the right way to create own board .json files?
3) How do I generate the right way bootloaderX files (.bin AND .elf !!). Or must I wait until they are delivered with a release?
4) Why are these files available under \esp32\bin but not under \esp32S3\bin?
5) What are these requested .elf variants, that wasn't necessary until 5.0.0?

Thank you for helping!
Regards
Andree

**Comment by Jason2866** [comment]
Every S3 supports flash frequency 80Mhz. Revert that change and the matching prebuild bootloader will be used. There is no 40Mhz build.

**Comment by ams-hh** [comment]
Hello Jason8266!
Sorry, my fault. By 80m or 40m I thought on MegaByte.... 

But which changes do I have to revert?
If I revert everything and only take this for platformio.ini:

`
[platformio]
default_envs = esp32S3

[env]
framework = arduino
monitor_speed = 115200
upload_speed = 921600

`[env:esp32S3]
build_flags =
-D CORE_DEBUG_LEVEL=0
platform = espressif32
board = esp32-s3-devkitc-1

`
then it ends in a boot-loop, that tells me (as written before) that my ESP32S3-WROOM-1N$ has only 4MB. (What is true so far...)

`
ELF file SHA256: 0000000000000000
15:18:50.624 >
15:18:50.624 > Rebooting...
15:18:50.625 > ␀�ESP-ROM:esp32s3-20210327
15:18:50.634 > Build:Mar 27 2021
15:18:50.635 > rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
15:18:50.640 > Saved PC:0x4037723c
15:18:50.642 > SPIWP:0xee
15:18:50.643 > mode:DIO, clock div:1
15:18:50.645 > load:0x3fce3808,len:0x43c
15:18:50.647 > load:0x403c9700,len:0xbec
15:18:50.650 > load:0x403cc700,len:0x2a3c
15:18:50.652 > entry 0x403c98d8
15:18:50.707 > **E (82) spi_flash: Detected size(4096k) smaller than the size in the binary image header(8192k). Probe failed.**
15:18:50.718 >
15:18:50.718 > assert failed: do_core_init startup.c:298 (flash_ret == ESP_OK)
15:18:50.723 >
15:18:50.724 >
15:18:50.724 > Backtrace:0x40377632:0x3fceb1800x4037a3e5:0x3fceb1a0 0x4037f9f5:0x3fceb1c0 0x4200a5ae:0x3fceb2f0 0x40376f9d:0x3fceb320 0x403cd6ef:0x3fceb350 0x403cd9ae:0x3fceb380 0x403c992d:0x3fceb4b0 0x40045c01:0x3fceb570  |<-CORRUPTED

`
So, what should I do then?
A.

**Comment by Jason2866** [comment]
Try this
```
{
  "build": {
    "arduino":{
      "ldscript": "esp32s3_out.ld",
      "memory_type": "qio_qspi"
    },
    "core": "esp32",
    "extra_flags": "-DARDUINO_USB_MODE=1",
    "f_cpu": "240000000L",
    "f_flash": "80000000L",
    "flash_mode": "qio",
    "mcu": "esp32s3",
    "variant": "esp32s3"
  },
  "connectivity": [
    "wifi"
  ],
  "debug": {
    "openocd_target": "esp32s3.cfg"
  },
  "frameworks": [
    "arduino",
    "espidf"
  ],
  "name": "ESP32-S3 4MB No PSRAM",
  "upload": {
    "flash_size": "4MB",
    "maximum_ram_size": 327680,
    "maximum_size": 4194304,
    "use_1200bps_touch": true,
    "wait_for_upload_port": true,
    "require_upload_port": true,
    "speed": 460800
  },
  "url": "https://blabla",
  "vendor": "espressif"
}
```

**Comment by ams-hh** [comment]
Sorry for boring you .... but now I am just where I was before.
I followed the steps you provided and then be trapped by:

`
Compiling G:\ANDREE\Projekte\PIO\TESTS\TESTS_COMMON\Blink\.pio\build\esp32s3_4MB\src\Blink.cpp.o
*** [G:\ANDREE\Projekte\PIO\TESTS\TESTS_COMMON\Blink\.pio\build\esp32s3_4MB\bootloader.bin] Source `C:\Users\amshh\.platformio\packages\framework-arduinoespressif32\tools\sdk\esp32s3\bin\bootloader_dio_40m.elf' not found, needed by target `G:\ANDREE\Projekte\PIO\TESTS\TESTS_COMMON\Blink\.pio\build\esp32s3_4MB\bootloader.bin'.

`
As before, bootloader_dio_40m.elf can't be found

**Comment by Jason2866** [comment]
Your platformio setup is probably borked.  There is nowhere 40Mhz as flash frequency now!
Delete the hidden folder `.platformio` to clean it. Platformio will rebuild,
