### ISSUE TITLE
How to use ESP IDF Component Manager in platformIO?

### ISSUE THREAD

**Issue by modi12jin** [platformio/platform-espressif32#935]
I don't know how to add the components in the ESP IDF component manager in platformIO? Or can I only add components and dependencies manually?

**Comment by Jason2866** [comment]
The component manager is "in" PlatformIO since this [commit](https://github.com/platformio/platform-espressif32/commit/0abe8d30e1d0590ee6deb055757450062f9586e9). So using should work as in "native "IDF.

**Comment by Jason2866** [comment]
Example with "LittleFS" https://github.com/Jason2866/Arduino_IDF_LittleFS
