### ISSUE TITLE
Question concerning boardfile/partition dependency

### ISSUE THREAD

**Issue by ams-hh** [platformio/platform-espressif32#938]
Hello,
can someone please confirm or clarify if wrong:

- If the boardfile (json) says ""flash_size": "4MB"", then from ...platformio\packages\frameworkXXX\tools\partitions the file default.csv is taken, processed and stored as partitions.bin in project subdirectory .pio\build\<environment> (and flashed from there)
- If the boardfile (json) says ""flash_size": "8MB"", then from ...  the file default_8MB.csv is taken, processed and stored as partitions.bin in project subdirectory .pio\build\<environment>
- If the boardfile (json) says ""flash_size": "16MB"", then from ...  the file default_16MB.csv is taken, processed and stored as partitions.bin in project subdirectory .pio\build\<environment>

If I want to deviate from this, I have to provide a custom .csv file IN THE  ...platformio\packages\frameworkXXX\tools\partitions directory and include in platformio.ini in the [env:xxx] 
board_build.partitions = myCustomPartitions.csv

Do I really have to insert this custom file in this "delivered" directory or is there a chance to direct platformio to custom directory with my custom partition files? (like boards_dir = xxx for custom boards files)

Thank you
Andree

**Comment by Jason2866** [comment]
Platformio always uses the default.csv. Only a other one is used when you specify.
You can put your custom.csv in the root directory of the Platformio project.
Platformio will search there and use it.
