### ISSUE TITLE
Error on creating SPIFFS image with PlatformIO 

### ISSUE THREAD

**Issue by D1sconnected** [platformio/platform-espressif32#941]
Hey guys, thanks for all the work you've done with PlatformIO. 

I've been looking for web server example with JavaScrypt and decided to try official [restful-server example](https://github.com/espressif/esp-idf/tree/master/examples/protocols/http_server/restful_server) from ESP-IDF repo.

It works and compiles perfect according to `readme.md` and I succesfully flashed it on my ESP32-WROOM board for testing.
Then I decided to port this example to PlatformIO enviroment.

The main application builds just fine, but I ran into a problem, when trying to create SPIFFS image, which contains server sources (html, css, js, png)

![image](https://user-images.githubusercontent.com/33172683/195621290-a7c6321f-d625-4780-bf1a-655c0a9c9150.png)

- At the begining it was `SPIFFS_write error(-10010)`, and I figured it by shorten filenames. Not sure if it's the right way to do it.
- Then I faced another problem `SPIFFS_write error(-10001): File system is full`, but my SPIFFS partition is 2 MB, and source size is about 1.7 MB.

Anyway, there are no problems when building-flashing with `idf.py`. I've also tried to modify app in PlatformIO enviroment, rebuild it and flash only app, it's working okay with pre-flashed spiffs image from `idf.py` enviroment.

If you have any ideas, what should I try next please let me know.

**Comment by Jason2866** [comment]
Mhh, why SPIFFS? It is deprecated. LittleFS is faster and is maintained.

**Comment by D1sconnected** [comment]
@Jason2866 heh, didnt know it's depricated. I am kinda new to ESP32. Official example has no LittleFS support, but maybe it's not a big deal to modify it. Other options referenced in example are SD card or PC host via JTAG. But it does not suit my application for now.

I upload my code on [public repo](https://github.com/D1sconnected/restful-server-platformio), it should compile without problems, but let me know if something missing. Thanks!

**Comment by Jason2866** [comment]
@D1sconnected  Will try. Maybe i find no time before weekend.
Btw. Working LittleFs for IDF (used as component to compile Arduino) is here https://github.com/joltwallet/esp_littlefs

**Comment by Jason2866** [comment]
@D1sconnected  Platformio does not support IDF 5.0. You have https://github.com/D1sconnected/restful-server-platformio/blob/master/src/idf_component.yml which forces IDF 5.0

**Comment by Jason2866** [comment]
The issue is the partitions_example.csv. The choosen SPIFFS partition is to small. Use the following and it will work.
```
# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x6000,
phy_init, data, phy,     0xf000,  0x1000,
factory,  app,  factory, 0x10000, 0xC0000,
storage,  data, spiffs,  ,        0x250000,
```

**Comment by D1sconnected** [comment]
@Jason2866 hey, thanks a lot. I really misschek esp-idf version, now spiffs generation is okay. The change in partion size seems kinda strange for me, but it's okay for demo.

For now I am struggle to upload Filesystem Image. 
It seems like only `firmware.bin` was flashed without `spiffs.bin`. I use this algorithm:

1. Clean All
2. Build
3. Build Filesystem Image
4. Upload Filesystem Image

![image](https://user-images.githubusercontent.com/33172683/195799375-a4546454-d79d-4045-879f-df992e173c40.png)
![image](https://user-images.githubusercontent.com/33172683/195799430-8ccfbdf0-d562-4b8d-a3fc-55ec21482708.png)

And there is no upload after flash erasing. Seems like there is not files at spiffs section.

![image](https://user-images.githubusercontent.com/33172683/195799829-baf0936c-6ab9-4109-8629-a483838c6a3a.png)

Any thoughts what could be wrong?
