### ISSUE TITLE
Using ESP32S2 RISCV ULP with .c files in espidf

### ISSUE THREAD

**Issue by dS98765** [platformio/platform-espressif32#961]
Hello,
I'm looking for a way to use c files for the RISCV ULP. I've found the documentation [here](https://docs.platformio.org/en/stable/frameworks/espidf.html) for uploading using assembly for what I assume is the FSM ULP of the ESP32. I have tried using the same method but simply replacing the assembly with C to no avail. There also seems to be some missing ulp component headers, specifically ulp_riscv_utils.h & ulp_riscv_gpio.h

I have also tried following the standard espidf method described [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/system/ulp-risc-v.html)

My current CMakeLists.txt located in src/
```
idf_component_register(SRCS "main.cpp"
                        INCLUDE_DIRS "."
                        REQUIRES soc nvs_flash ulp driver)

set(ulp_app_name ulp_main)
set(ulp_riscv_sources "../ulp/ulpMain.c")
set(ulp_exp_dep_srcs "main.cpp")
ulp_embed_binary(${ulp_app_name} "${ulp_riscv_sources}" "${ulp_exp_dep_srcs}")
```

Thank you

**Comment by Jason2866** [comment]
This [riscv ULP example](https://github.com/Jason2866/platform-espressif32/tree/Tasmota/205/examples/espidf-ulp-riscv) is working in my fork.
