### ISSUE TITLE
How can I increase the heap size?

### ISSUE THREAD

**Issue by CharlesXSong** [platformio/platform-espressif32#962]
I'm using the ESP32D0WD with 520KB RAM. But the print log shows that all free heap size is `266552` returned by function `ESP.getHeapSize()`.
Which will cause the `abort()` fault when I'm trying to allocate some heap size.
SO, is there any way to increase the heap size in platformio?o(╥﹏╥)o
SOS!!!!!!!!!!!!!

**Comment by valeros** [comment]
Hi @CharlesXSong, Unfortunately, you cannot increase the heap size, `266552` is all you've got freely accessible after compiling your sketch. You can add additional storage only via an external PSRAM via SPI.
