### ISSUE TITLE
Could not initialize project ESP32-S3

### ISSUE THREAD

**Issue by SynonZelra** [platformio/platform-espressif32#967]
What kind of issue is this?

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Arch Linux x64 5.18.8

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.0.2

### Description of problem
can't initialize esp32-s3 project, 

#### Steps to Reproduce
New Project -> esp32-s3-devkitc -> espressif framework -> finish

### Actual Results
PIO Core Call Error: "The current working directory /mnt/Project/test project/testtest will be used for the project.\n\nThe next files/directories have been created in /mnt/Project/test project/testtest\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nResolving esp32-s3-devkitc-1 environment packages...\n\n\nError: Unknown board ID 'esp32-s3-devkitc-1'"

**The content of `platformio.ini`:**
```ini
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
```

**Comment by ggalisky** [comment]
I also am having this issue, working on fixing it

**Comment by ivankravets** [comment]
@valeros, could you help here?

**Comment by martinberlin** [comment]
In case it helps anyone I could make it work with S3 correctly.
There is a working example including platformio.ini and custom board in my [ESP32S3 Epub reader fork](https://github.com/martinberlin/IT8951-esp32-epub-reader).

**Comment by valeros** [comment]
Hi @martinberlin, I guess your restriction on the platform version `platformio/espressif32@^4.3` is the reason why the board is not found. ESP-IDF support for S3 was added in the platform version v5.0. As for the docs, it implies that the latest development platform is used. 

Anyone who is facing the similar issues, please double check that you're using the latest version of the `espressif32` platform.
