### ISSUE TITLE
Firmware binaries are missing SHA256 hash of the original ELF for arduino framework

### ISSUE THREAD

**Issue by paclema** [platformio/platform-espressif32#972]
The same issue (https://github.com/platformio/platform-espressif32/issues/272) was previously resolved but further changes seem to have brake it while building for the Arduino framework.

**Comment by Jason2866** [comment]
Thats how it works when using Arduino. Not possible to add a valid sha since Arduino uses always the same precompiled libs. The same behaviour as when using Arduino IDE. Arduino != IDF

**Comment by paclema** [comment]
Fixed here: https://github.com/espressif/arduino-esp32/commit/161b1673d9ad2804ff5a60a8db89464ad9bf69e7
