### ISSUE TITLE
Add arm64 support for ULP projects

### ISSUE THREAD

**Issue by schiermi** [platformio/platform-espressif32#977]
I want to help to make it possible to build projects using ULP on arm64 RPis.
I've found general support was added in this latest commit https://github.com/espressif/binutils-esp32ulp/commit/9bb46bab6b2e1ef1a246c3700f0a9ed791bfe477
Does someone have ideas how to make this "usable" and provide me the required pointers?

**Comment by Jason2866** [comment]
@schiermi It is already done with #924
