### ISSUE TITLE
Feature Request: Support for IDF 5.0

### ISSUE THREAD

**Issue by Jason2866** [platformio/platform-espressif32#979]
Espressif released IDF 5.0 a while ago.

**Comment by zapta** [comment]
Not sure how to vote for it so supporting it here with a comment.

IDF 5 has support for continuous ADC adc_continuous.h which we need.  

Having to develop with an old SDK that doesn't match the latest documentation and feature set set is difficult.

**Comment by Pespiri** [comment]
> Having to develop with an old SDK that doesn't match the latest documentation and feature set set is difficult.

The documentation for ESP-IDF 4.4.2 can be found here ([ESP-IDF 4.4.2 Docs](https://docs.espressif.com/projects/esp-idf/en/v4.4.2))  
You can change target and version on the top right

**Comment by valeros** [comment]
Integration of IDF v5.0 is already in the works and will be publically available next week.

**Comment by grisharav** [comment]
Thanks, shall this release include toolchain upgrade to GCC 11.2?

**Comment by Jason2866** [comment]
IDF 5.0 won't work without actual tool chains, it is a dependency. So, yes.

**Comment by zapta** [comment]
Can you please add more information on how to use it?  Looking at platformio's documentation it still mentions V4 as the current version.

https://docs.platformio.org/en/latest/frameworks/espidf.html

**Comment by grisharav** [comment]
I also don't see a release, is it upcoming?

**Comment by valeros** [comment]
If nothing goes wrong, a new release will be published by the end of this week. The latest changes with IDF 5.0 can be pulled via the upstream version of the development platform, e.g.:
```ini
[env:esp32dev]
board = https://github.com/platformio/platform-espressif32.git
platform = espressif32
framework = espidf
```
Note: You should have a Git client installed in your system.

**Comment by flavioroth** [comment]
The snippet from @valeros doesn't work me. It breaks with the error: `Error: Unknown board ID 'https://github.com/platformio/platform-espressif32.git'` 

Did you mean ?
```ini
[env:esp32dev]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32dev
framework = espidf
```

**Comment by Coobik** [comment]
hi all! i have updated Espressif 32 platform to version 6.0.0 in platformio in vscode
build fails with error:
```
 File "/Users/USER/.platformio/packages/framework-espidf/tools/ldgen/ldgen.py", line 16, in <module>
    from ldgen.entity import EntityDB
  File "/Users/USER/.platformio/packages/framework-espidf/tools/ldgen/ldgen/entity.py", line 12, in <module>
    from pyparsing import (Group, Literal, OneOrMore, ParseException, SkipTo, Suppress, White, Word, ZeroOrMore, alphas,
ImportError: cannot import name 'rest_of_line' from 'pyparsing' (/Users/USER/.platformio/penv/lib/python3.9/site-packages/pyparsing.py)
Compiling .pio/build/esp32dev/bootloader/bootloader_support/src/flash_partitions.o
*** [.pio/build/esp32dev/sections.ld] Error 1
```
--
i have esp-idf toolchain (v5) configured and it is able to build the project from command line
any suggestions?
thanks!

**Comment by valeros** [comment]
Hi @Coobik, please open a new issue with detailed instructions on how to reproduce the issue.

**Comment by ghost711** [comment]
@Coobik , I just got past the same issue.  Just had to activate the platformio virtualenv, and then update pyparsing. 
On my system that looks like this:
```
source ~/.platformio/penv/bin/activate
pip install -U pyparsing
```

**Comment by MrSniffer** [comment]
When will I be able to access ESP32 5.0 APIs using platform.io and framework=arduino? Right now I am stuck at ver 4.x APIs.

**Comment by Jason2866** [comment]
@MrSniffer  First espressif Arduino crew needs to port Arduino based on IDF 5.0. The started to work on this.

**Comment by MrSniffer** [comment]
Is the espressif Arduino work ready for prime time, so we can use IDF 5.0 with Arduino framework projects under Platformio?

**Comment by Jason2866** [comment]
The started the work. Probably late this year
