### ISSUE TITLE
unable to build project Error: Couldn't find the main target of the project!

### ISSUE THREAD

**Issue by TalSomech** [platformio/platform-espressif32#994]
using CLION ide with esp-idf framework and i cannot build the project in any way, from what i've read i saw that platformIO and espidf both use CMAKE which conflict , but it saw this was the bug 3 years ago , the solution was to revert to platform espressif32 v3.3 
but i am using esp32-s3-devkit which was added in v5.0 , help is very much welcome.
![Capture](https://user-images.githubusercontent.com/73115681/211338461-8cde84bf-f25c-469f-a027-6f227f5f56ca.PNG)

**Comment by valeros** [comment]
Hi @TalSomech ! Unfortunately, there is still no proper integration of ESP-IDF and at the moment and not ETA for it. The only workaround is to use a different IDE (e.g. VSCode).
